import React,{useEffect,useMemo,useState}from'react'
import'./admin-plans.css'

const EMPTY={code:'pro',name:'',description:'',price_monthly:'',price_yearly:'',sort_order:0,active:true,features:{}}
const LIMITS=[['photos','Mídias por ciclo'],['items','Produtos e serviços por ciclo'],['promotions','Promoções por ciclo']]
const TOGGLES=[
 ['business_profile','Perfil comercial'],
 ['analytics','Analytics comercial'],
 ['featured','Destaque nas buscas'],
 ['verified','Selo de verificação'],
 ['premium_ads','Publicidade Premium'],
 ['city_instagram','Instagram da cidade'],
 ['advanced_analytics','Estatísticas avançadas'],
 ['review_management','Reputação + respostas às avaliações']
]
const fmt=v=>v==null||v===''?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const normalize=n=>Math.max(0,Number.isFinite(Number(n))?Number(n):0)

export default function AdminPlansPage({supabase}){
 const[plans,setPlans]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editor,setEditor]=useState(null),[message,setMessage]=useState({text:'',error:false})
 const toast=(text,error=false)=>{setMessage({text,error});window.clearTimeout(window.__vlPlansToast);window.__vlPlansToast=window.setTimeout(()=>setMessage({text:'',error:false}),3500)}
 async function load(){setLoading(true);const{data,error}=await supabase.from('plans').select('id,code,name,description,price_monthly,price_yearly,features,active,sort_order,created_at,updated_at').order('sort_order').order('price_monthly');if(error)toast(error.message||'Não foi possível carregar os planos.',true);setPlans(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const openNew=()=>setEditor({...EMPTY,mode:'new',id:null})
 const openEdit=row=>setEditor({mode:'edit',id:row.id,code:row.code,name:row.name||'',description:row.description||'',price_monthly:row.price_monthly??'',price_yearly:row.price_yearly??'',sort_order:row.sort_order||0,active:Boolean(row.active),features:{...(row.features||{})}})
 const close=()=>setEditor(null)
 const update=(key,value)=>setEditor(cur=>({...cur,[key]:value}))
 const updateFeature=(key,value)=>setEditor(cur=>({...cur,features:{...(cur?.features||{}),[key]:value}}))
 const resetDefaults=code=>setEditor(cur=>({...cur,description:code==='premium'?'Máxima presença, reputação avançada e recursos exclusivos, incluindo resposta às avaliações e estatísticas avançadas.':code==='pro'?'Mais destaque e recursos para crescer com sua empresa.':'Presença básica e recursos essenciais para começar no VitrineLocal.'}))
 async function save(e){e.preventDefault();if(!editor)return;setSaving(true);try{if(!String(editor.name||'').trim())throw new Error('Informe o nome do plano.');const features={...(editor.features||{})};delete features.ai_posts;delete features.ai_posts_limit;for(const[k]of LIMITS)features[k]=normalize(features[k]);for(const[k]of TOGGLES)features[k]=Boolean(features[k]);const payload={code:editor.code,name:String(editor.name).trim(),description:String(editor.description||'').trim()||null,price_monthly:normalize(editor.price_monthly),price_yearly:normalize(editor.price_yearly),features,active:Boolean(editor.active),sort_order:Number(editor.sort_order)||0,updated_at:new Date().toISOString()};const req=editor.mode==='edit'?supabase.from('plans').update(payload).eq('id',editor.id):supabase.from('plans').insert(payload);const{error}=await req;if(error)throw error;toast(editor.mode==='edit'?'Plano atualizado com sucesso.':'Plano criado com sucesso.');close();await load()}catch(error){toast(error.message||'Não foi possível salvar o plano.',true)}finally{setSaving(false)}}
 const planSummary=useMemo(()=>plans.map(p=>({..p,featureCount:Object.values(p.features||{}).filter(v=>v===true||(typeof v==='number'&&v>0)).length})),[plans])
 if(loading)return <div className="admin-v2-card admin-v2-empty"><strong>Carregando planos…</strong><span>Sincronizando configurações comerciais.</span></div>
 return <div className="admin-plans-page">
  {message.text&&<div className={message.error?'admin-v2-alert':'admin-v2-note'}>{message.text}</div>}
  <section className="admin-v2-card admin-v2-section admin-plans-intro"><div><span className="admin-v2-kicker">MODELO COMERCIAL</span><h2>Planos da plataforma</h2><p>Edite nome, descrição, preços e benefícios diretamente pelo painel. Não é necessário alterar código para ajustar o catálogo comercial.</p></div><button className="admin-v2-btn primary" onClick={openNew}>＋ Novo plano</button></section>
  <section className="admin-plans-grid">{planSummary.map(plan=><article className={`admin-v2-card admin-plan-card ${plan.code==='premium'?'premium':''}`} key={plan.id}><div className="admin-plan-top"><span className="admin-v2-pill blue">{plan.code}</span><span className={`admin-v2-pill ${plan.active?'green':'red'}`}>{plan.active?'Ativo':'Inativo'}</span></div><div className="admin-plan-icon">{plan.code==='premium'?'◆':plan.code==='pro'?'✦':'•'}</div><h3>{plan.name}</h3><p>{plan.description||'Sem descrição.'}</p><strong>{fmt(plan.price_monthly)} <small>/ mês</small></strong><span className="admin-plan-feature-count">{plan.featureCount} benefícios configurados</span><div className="admin-v2-table-actions"><button onClick={()=>openEdit(plan)}>Editar plano</button></div></article>)}</section>
  {editor&&<section className="admin-v2-card admin-v2-form-panel admin-plans-editor"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">{editor.mode==='edit'?'EDIÇÃO':'NOVO PLANO'}</span><h2>{editor.mode==='edit'?`Editar ${editor.name||'plano'}`:'Criar plano'}</h2><p>Configure o comercial sem precisar editar o código do projeto.</p></div><button type="button" className="admin-v2-close-inline" onClick={close}>×</button></div><form onSubmit={save}><div className="admin-v2-form-grid"><label>Código<select value={editor.code} disabled={editor.mode==='edit'} onChange={e=>update('code',e.target.value)}><option value="free">free</option><option value="pro">pro</option><option value="premium">premium</option></select></label><label>Nome<input value={editor.name} onChange={e=>update('name',e.target.value)} required/></label><label className="full">Descrição<textarea rows="3" value={editor.description} onChange={e=>update('description',e.target.value)}/></label><div className="admin-plan-description-help full"><span>Descrição sugerida</span><button type="button" onClick={()=>resetDefaults(editor.code)}>Aplicar texto padrão</button></div><label>Preço mensal<input type="number" min="0" step="0.01" value={editor.price_monthly} onChange={e=>update('price_monthly',e.target.value)}/></label><label>Preço anual<input type="number" min="0" step="0.01" value={editor.price_yearly} onChange={e=>update('price_yearly',e.target.value)}/></label><label>Ordem de exibição<input type="number" value={editor.sort_order} onChange={e=>update('sort_order',e.target.value)}/></label></div>
  <div className="admin-plan-config"><div className="admin-plan-config-head"><div><span className="admin-v2-kicker">LIMITES</span><h3>Uso no ciclo</h3><p>Use 0 para não liberar o recurso.</p></div></div><div className="admin-plan-limit-grid">{LIMITS.map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={editor.features?.[key]??0} onChange={e=>updateFeature(key,normalize(e.target.value))}/></label>)}</div></div>
  <div className="admin-plan-config"><div className="admin-plan-config-head"><div><span className="admin-v2-kicker">RECURSOS</span><h3>Benefícios liberados</h3><p>Ative ou desative cada recurso do plano.</p></div></div><div className="admin-plan-toggle-grid">{TOGGLES.map(([key,label])=><label key={key} className={`admin-plan-toggle ${editor.features?.[key]?'on':''}`}><input type="checkbox" checked={Boolean(editor.features?.[key])} onChange={e=>updateFeature(key,e.target.checked)}/><span><strong>{label}</strong><small>{key==='review_management'?'Inclui reputação no Analytics e resposta às avaliações.':key==='advanced_analytics'?'Visitantes únicos, tendências e canais de contato.':key==='analytics'?'Indicadores comerciais gerais.':'Recurso disponível neste plano.'}</small></span></label>)}</div></div>
  <div className="admin-v2-form-meta"><div className="checks"><label><input type="checkbox" checked={Boolean(editor.active)} onChange={e=>update('active',e.target.checked)}/> Plano ativo</label></div><div className="admin-v2-actions"><button type="button" className="admin-v2-btn" onClick={close}>Cancelar</button><button className="admin-v2-btn primary" disabled={saving}>{saving?'Salvando…':'Salvar plano'}</button></div></div></form></section>}
 </div>
}
