import React,{useEffect,useState} from 'react'
import { db } from './review-service.js'
import Icon from './ui-icons.jsx'
import './admin-ux.css'
const NAV_GROUPS=[
 ['Hoje',[['dashboard','Visão geral','home','/admin'],['notifications','Notificações','bell','/admin/notificacoes']]],
 ['Pessoas',[['businesses','Empresas','store','/admin/empresas'],['users','Usuários','user','/admin/usuarios'],['invitations','Convites','share','/admin/convites']]],
 ['Conteúdo',[['reviews','Avaliações','star','/admin/avaliacoes'],['events','Eventos','calendar','/admin/gestao?tab=events'],['promotions','Promoções','tag','/admin/gestao?tab=promotions'],['banners','Banners','image','/admin/banners']]],
 ['Comercial',[['advertising','Publicidade','ticket','/admin/publicidade'],['plans','Planos','check','/admin/gestao?tab=plans'],['plan_assignments','Planos por empresa','briefcase','/admin/gestao?tab=assignments'],['analytics','Analytics','search','/admin/analytics']]],
 ['Catálogo',[['needs','Necessidades','grid','/admin/gestao?tab=needs'],['categories','Categorias','grid','/admin/gestao?tab=categories'],['cities','Cidades','pin','/admin/gestao?tab=cities']]],
]
export default function AdminShell({active='dashboard',title,description,email,children}){const[mobileOpen,setMobileOpen]=useState(false),[emailState,setEmailState]=useState(email||'');useEffect(()=>{if(email){setEmailState(email);return}db?.auth.getSession().then(({data})=>setEmailState(data?.session?.user?.email||''))},[email]);const logout=async()=>{if(db)await db.auth.signOut();window.location.href='/laguna'};return <div className="admin-v2-shell"><aside className={`admin-v2-sidebar ${mobileOpen?'open':''}`}><div className="admin-v2-brand"><a href="/admin"><span className="admin-v2-brand-mark">V</span><span><strong>Vitrine<span>Local</span></strong><small>Central administrativa</small></span></a></div><nav className="admin-v2-nav" aria-label="Navegação administrativa">{NAV_GROUPS.map(([group,items])=><div className="admin-v2-nav-group" key={group}><small>{group}</small>{items.map(([key,label,icon,href])=><a key={key} href={href} className={active===key?'active':''} aria-current={active===key?'page':undefined}><span className="icon"><Icon name={icon} size={16}/></span><span>{label}</span></a>)}</div>)}</nav><div className="admin-v2-sidebar-bottom"><a href="/admin/novo-parceiro" className="admin-v2-back-site">＋ Novo cadastro</a><a href="/laguna" className="admin-v2-back-site">↗ Ver site público</a><button className="admin-v2-logout" onClick={logout}>Sair da conta</button></div></aside>{mobileOpen&&<button className="admin-v2-overlay" aria-label="Fechar menu" onClick={()=>setMobileOpen(false)}/>}<div className="admin-v2-main"><header className="admin-v2-topbar"><div className="admin-v2-mobile-head"><button className="admin-v2-menu" onClick={()=>setMobileOpen(true)} aria-label="Abrir menu">☰</button><span>VitrineLocal</span></div><div className="admin-v2-user"><span className="admin-v2-avatar">{(emailState||'A').slice(0,1).toUpperCase()}</span><div><strong>{emailState||'Administrador'}</strong><small>Administrador</small></div><span className="admin-v2-dot"/></div></header><main className="admin-v2-content"><div className="admin-v2-heading"><div><span className="admin-v2-kicker">PAINEL ADMINISTRATIVO</span><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="admin-v2-heading-meta"><span>Online</span><small>VitrineLocal</small></div></div>{children}</main></div></div>}
