import React,{useEffect,useMemo,useState} from 'react'
import AdminShell from './AdminShell.jsx'
import './admin-v2.css'

const BUCKET='premium-banners',MAX_BYTES=10*1024*1024,TYPES=new Set(['image/jpeg','image/png','image/webp'])
const empty={business_id:'',city_id:'',title:'',description:'',target_url:'',priority:0,starts_at:'',ends_at:'',active:false,image_url:'',image_path:''}
const dateInput=v=>v?new Date(v).toISOString().slice(0,16):''
export default function AdminPremiumBannerPage({supabase}){
 const [session,setSession]=useState(null),[authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true),[banners,setBanners]=useState([]),[cities,setCities]=useState([]),[businesses,setBusinesses]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[file,setFile]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({text:'',error:false})
 const toast=(text,error=false)=>{setMessage({text,error});window.clearTimeout(window.__vlAdminBannerToast);window.__vlAdminBannerToast=window.setTimeout(()=>setMessage({text:'',error:false}),3300)}
 async function init(){if(!supabase){setChecking(false);setLoading(false);return}const {data:{session:s}}=await supabase.auth.getSession();setSession(s||null);if(!s){setChecking(false);setLoading(false);return}const {data:p}=await supabase.from('profiles').select('role').eq('id',s.user.id).maybeSingle();const ok=p?.role==='admin';setAuthorized(ok);setChecking(false);if(ok)await load()}
 async function load(){setLoading(true);const [b,c,bs]=await Promise.all([supabase.from('advertisements').select('id,business_id,city_id,title,description,image_url,image_path,target_url,active,priority,starts_at,ends_at,created_at,cities(name,state),businesses(name)').eq('placement','home_banner').order('priority',{ascending:false}).order('created_at',{ascending:false}),supabase.from('cities').select('id,name,state,slug,active').order('name'),supabase.from('businesses').select('id,name,city_id,status').order('name')]);if(b.error||c.error||bs.error)toast(b.error?.message||c.error?.message||bs.error?.message||'Erro ao carregar banners.',true);setBanners(b.data||[]);setCities(c.data||[]);setBusinesses(bs.data||[]);setLoading(false);if(selected){const fresh=(b.data||[]).find(x=>x.id===selected.id);if(fresh)beginEdit(fresh);else{setSelected(null);setForm(null)}}}
 useEffect(()=>{init()},[])
 function beginEdit(row){setSelected(row);setFile(null);setForm({business_id:row.business_id||'',city_id:row.city_id||'',title:row.title||'',description:row.description||'',target_url:row.target_url||'',priority:row.priority||0,starts_at:dateInput(row.starts_at),ends_at:dateInput(row.ends_at),active:Boolean(row.active),image_url:row.image_url||'',image_path:row.image_path||''})}
 function newBanner(){setSelected(null);setFile(null);setForm({...empty,city_id:cities.find(x=>x.active)?.id||''})}
 function reset(){setSelected(null);setFile(null);setForm(null)}
 const cityBusinesses=useMemo(()=>businesses.filter(b=>!form?.city_id||b.city_id===form.city_id),[businesses,form?.city_id])
 const preview=file?URL.createObjectURL(file):form?.image_url||''
 const update=(key,value)=>setForm(x=>({...x,[key]:value}))
 async function save(e){e.preventDefault();if(!form)return;if(!form.title.trim())return toast('Informe o título do banner.',true);if(!form.city_id||!form.business_id)return toast('Selecione cidade e empresa.',true);let path='';setSaving(true);try{if(file){if(!TYPES.has(file.type))throw new Error('Use JPG, PNG ou WebP.');if(file.size>MAX_BYTES)throw new Error('A imagem deve ter no máximo 10 MB.');const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';path=`home/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from(BUCKET).upload(path,file,{cacheControl:'31536000',contentType:file.type,upsert:false});if(upload.error)throw upload.error}const image_url=path?supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl:form.image_url||null;const payload={business_id:form.business_id,city_id:form.city_id,title:form.title.trim(),description:form.description.trim()||null,target_url:form.target_url.trim()||null,priority:Number(form.priority)||0,starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null,active:Boolean(form.active),image_url,image_path:path||form.image_path||null,placement:'home_banner'};let r;if(selected)r=await supabase.from('advertisements').update(payload).eq('id',selected.id);else r=await supabase.from('advertisements').insert(payload);if(r.error)throw r.error;if(path&&selected?.image_path)await supabase.storage.from(BUCKET).remove([selected.image_path]).catch(()=>{});toast(selected?'Banner atualizado.':'Banner criado.');await load()}catch(err){if(path)await supabase.storage.from(BUCKET).remove([path]).catch(()=>{});toast(err.message||'Não foi possível salvar o banner.',true)}finally{setSaving(false)}}
 async function toggle(row){const r=await supabase.from('advertisements').update({active:!row.active}).eq('id',row.id);if(r.error)toast(r.error.message,true);else{toast(row.active?'Banner pausado.':'Banner publicado.');await load()}}
 async function remove(row){if(!window.confirm(`Excluir o banner “${row.title}”?`))return;const r=await supabase.from('advertisements').delete().eq('id',row.id);if(r.error)toast(r.error.message,true);else{if(row.image_path)await supabase.storage.from(BUCKET).remove([row.image_path]).catch(()=>{});toast('Banner excluído.');await load();if(selected?.id===row.id)reset()}}
 if(checking)return <div className="admin-v2-shell"><div className="admin-v2-empty">Verificando acesso administrativo…</div></div>
 if(!session||!authorized)return <div className="admin-v2-shell"><main className="admin-v2-content"><div className="admin-v2-card admin-v2-empty"><strong>Acesso restrito</strong><span>Esta área é exclusiva para administradores.</span><a className="admin-v2-btn primary" href="/admin">Voltar ao admin</a></div></main></div>
 return <AdminShell active="banners" title="Banners Premium" description="Controle a mídia patrocinada da Home por cidade, empresa, prioridade e período." email={session.user.email}>
  {message.text&&<div className={message.error?'admin-v2-alert':'admin-v2-note'}>{message.text}</div>}
  <section className="admin-v2-card admin-v2-section"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">PUBLICIDADE</span><h2>{banners.length} banner(s)</h2><p>O primeiro item na prioridade recebe maior destaque no posicionamento configurado.</p></div><button className="admin-v2-btn primary" onClick={newBanner}>＋ Novo banner</button></div>{loading?<div className="admin-v2-empty"><strong>Carregando banners…</strong></div>:<div className="admin-v2-table-wrap"><table className="admin-v2-table"><thead><tr><th>Banner</th><th>Empresa</th><th>Cidade</th><th>Status</th><th>Prioridade</th><th></th></tr></thead><tbody>{banners.map(row=><tr key={row.id}><td><div className="admin-v2-maincell"><span className="admin-v2-thumb">{row.image_url?<img src={row.image_url} alt=""/>:'★'}</span><span><strong>{row.title}</strong><small>{row.description||'Sem descrição'}</small></span></div></td><td>{row.businesses?.name||'—'}</td><td>{row.cities?.name||'—'}{row.cities?.state?` - ${row.cities.state}`:''}</td><td><span className={`admin-v2-pill ${row.active?'green':'red'}`}>{row.active?'Publicado':'Pausado'}</span></td><td>{row.priority||0}</td><td><div className="admin-v2-table-actions"><button className="primary" onClick={()=>beginEdit(row)}>Editar</button><button onClick={()=>toggle(row)}>{row.active?'Pausar':'Publicar'}</button><button className="danger" onClick={()=>remove(row)}>Excluir</button></div></td></tr>)}</tbody></table></div>}</section>
  {form&&<section className="admin-v2-card admin-v2-section" style={{marginTop:14}}><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">{selected?'EDIÇÃO':'NOVO REGISTRO'}</span><h2>{selected?`Editar ${selected.title}`:'Novo banner'}</h2><p>Atualize a arte e os parâmetros de exibição.</p></div><button className="admin-v2-close-inline" onClick={reset} type="button">×</button></div>{preview&&<div className="admin-v2-banner-preview"><img src={preview} alt="Prévia do banner"/></div>}<form className="admin-v2-form-panel" onSubmit={save}><div className="admin-v2-form-grid"><label>Título<input value={form.title} onChange={e=>update('title',e.target.value)} required/></label><label>Cidade<select value={form.city_id} onChange={e=>{const city=e.target.value;const valid=businesses.some(b=>b.id===form.business_id&&b.city_id===city);setForm(x=>({...x,city_id:city,business_id:valid?x.business_id:''}))}} required><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name} - {c.state}{c.active?'':' (inativa)'}</option>)}</select></label><label>Empresa<select value={form.business_id} onChange={e=>update('business_id',e.target.value)} required><option value="">Selecione</option>{cityBusinesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Link de destino<input type="url" value={form.target_url} onChange={e=>update('target_url',e.target.value)} placeholder="https://…"/></label><label>Prioridade<input type="number" min="0" value={form.priority} onChange={e=>update('priority',e.target.value)}/></label><label>Nova imagem<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Início<input type="datetime-local" value={form.starts_at} onChange={e=>update('starts_at',e.target.value)}/></label><label>Fim<input type="datetime-local" value={form.ends_at} onChange={e=>update('ends_at',e.target.value)}/></label><label className="full">Descrição<textarea rows="4" value={form.description} onChange={e=>update('description',e.target.value)}/></label></div><div className="admin-v2-form-meta"><div className="checks"><label><input type="checkbox" checked={form.active} onChange={e=>update('active',e.target.checked)}/> Banner ativo</label></div><div className="admin-v2-actions"><button type="button" className="admin-v2-btn" onClick={reset}>Cancelar</button><button className="admin-v2-btn primary" disabled={saving}>{saving?'Salvando…':'Salvar banner'}</button></div></div></form></section>}
 </AdminShell>
}
