import React,{useEffect,useMemo,useState} from 'react'

const emptyCity={name:'',state:'SC',slug:'',country:'Brasil',active:true}
const emptyCategory={name:'',slug:'',icon:'✦',description:'',sort_order:0,active:true}
const emptyPromotion={business_id:'',title:'',description:'',price:'',original_price:'',starts_at:'',ends_at:'',status:'pending_review'}
const emptyPlan={code:'pro',name:'',description:'',price_monthly:'',price_yearly:'',active:true,sort_order:0,features:'{}'}
const statusLabels={draft:'Rascunho',pending_review:'Em revisão',published:'Publicada',archived:'Arquivada',rejected:'Rejeitada'}
const slugify=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const money=v=>v==null||v===''?'—':`R$ ${Number(v).toFixed(2).replace('.',',')}`
const when=v=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Sem período'
const dateInput=v=>v?new Date(v).toISOString().slice(0,16):''

export default function AdminTools({supabase,defaultTab='promotions'}){
 const [tab,setTab]=useState(defaultTab)
 const [cities,setCities]=useState([]),[categories,setCategories]=useState([]),[businesses,setBusinesses]=useState([]),[promotions,setPromotions]=useState([]),[plans,setPlans]=useState([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState({text:'',error:false})
 const [search,setSearch]=useState(''),[promotionStatus,setPromotionStatus]=useState('all'),[editor,setEditor]=useState(null)
 const [form,setForm]=useState(emptyPromotion)

 useEffect(()=>{setTab(defaultTab)},[defaultTab])
 const toast=(text,error=false)=>{setMessage({text,error});window.clearTimeout(window.__vlAdminToast);window.__vlAdminToast=window.setTimeout(()=>setMessage({text:'',error:false}),3200)}
 async function loadAll(){
  setLoading(true)
  const [c,cat,b,p,pl]=await Promise.all([
   supabase.from('cities').select('id,name,state,slug,country,active,created_at,updated_at').order('name'),
   supabase.from('categories').select('id,name,slug,icon,description,sort_order,active').order('sort_order').order('name'),
   supabase.from('businesses').select('id,name,status,city_id,cities(name,state)').order('name').limit(500),
   supabase.from('promotions').select('id,business_id,title,description,price,original_price,starts_at,ends_at,status,created_at,updated_at,businesses(name,cities(name,state))').order('created_at',{ascending:false}).limit(500),
   supabase.from('plans').select('id,code,name,description,price_monthly,price_yearly,features,active,sort_order,created_at,updated_at').order('sort_order').order('price_monthly')
  ])
  const e=c.error||cat.error||b.error||p.error||pl.error
  if(e)toast(e.message||'Não foi possível carregar a gestão.',true)
  setCities(c.data||[]);setCategories(cat.data||[]);setBusinesses(b.data||[]);setPromotions(p.data||[]);setPlans(pl.data||[]);setLoading(false)
 }
 useEffect(()=>{loadAll()},[])

 const activeBusinesses=useMemo(()=>businesses.filter(x=>x.status==='active'),[businesses])
 const filteredPromotions=useMemo(()=>promotions.filter(p=>{const q=search.trim().toLowerCase();const text=[p.title,p.description,p.businesses?.name,p.businesses?.cities?.name,p.businesses?.cities?.state].filter(Boolean).join(' ').toLowerCase();return (!q||text.includes(q))&&(promotionStatus==='all'||p.status===promotionStatus)}),[promotions,search,promotionStatus])
 const stats=useMemo(()=>({cities:cities.filter(x=>x.active).length,businesses:businesses.filter(x=>x.status==='active').length,published:promotions.filter(x=>x.status==='published').length,pending:promotions.filter(x=>x.status==='pending_review').length}),[cities,businesses,promotions])

 function newCity(){setEditor('city-new');setForm({...emptyCity})}
 function editCity(row){setEditor('city');setForm({name:row.name||'',state:row.state||'SC',slug:row.slug||'',country:row.country||'Brasil',active:Boolean(row.active)})}
 function newCategory(){setEditor('category-new');setForm({...emptyCategory})}
 function editCategory(row){setEditor('category');setForm({name:row.name||'',slug:row.slug||'',icon:row.icon||'✦',description:row.description||'',sort_order:row.sort_order||0,active:Boolean(row.active)})}
 function newPromotion(){setEditor('promotion-new');setForm({...emptyPromotion})}
 function editPromotion(row){setEditor('promotion');setForm({business_id:row.business_id||'',title:row.title||'',description:row.description||'',price:row.price??'',original_price:row.original_price??'',starts_at:dateInput(row.starts_at),ends_at:dateInput(row.ends_at),status:row.status||'pending_review'})}
 function newPlan(){setEditor('plan-new');setForm({...emptyPlan})}
 function editPlan(row){setEditor('plan');setForm({code:row.code||'pro',name:row.name||'',description:row.description||'',price_monthly:row.price_monthly??'',price_yearly:row.price_yearly??'',active:Boolean(row.active),sort_order:row.sort_order||0,features:JSON.stringify(row.features||{},null,2)})}
 function closeEditor(){setEditor(null);setForm(emptyPromotion)}

 async function saveCity(e){e.preventDefault();setBusy('city');try{const payload={name:form.name.trim(),state:form.state.trim().toUpperCase(),slug:slugify(form.slug||form.name),country:form.country.trim()||'Brasil',active:Boolean(form.active),updated_at:new Date().toISOString()};const id=editor==='city'?editor.rowId:null;const r=editor==='city'?await supabase.from('cities').update(payload).eq('id',id):await supabase.from('cities').insert(payload);if(r.error)throw r.error;toast(editor==='city'?'Cidade atualizada.':'Cidade criada.');closeEditor();await loadAll()}catch(e){toast(e.message||'Erro ao salvar cidade.',true)}finally{setBusy('')}}
 async function saveCategory(e){e.preventDefault();setBusy('category');try{const payload={name:form.name.trim(),slug:slugify(form.slug||form.name),icon:form.icon.trim()||'✦',description:form.description.trim()||null,sort_order:Number(form.sort_order)||0,active:Boolean(form.active)};const id=editor==='category'?editor.rowId:null;const r=editor==='category'?await supabase.from('categories').update(payload).eq('id',id):await supabase.from('categories').insert(payload);if(r.error)throw r.error;toast(editor==='category'?'Categoria atualizada.':'Categoria criada.');closeEditor();await loadAll()}catch(e){toast(e.message||'Erro ao salvar categoria.',true)}finally{setBusy('')}}
 async function savePromotion(e){e.preventDefault();setBusy('promotion');try{if(!form.business_id)throw new Error('Selecione a empresa.');if(!form.title.trim())throw new Error('Informe o título da promoção.');if(form.ends_at&&form.starts_at&&new Date(form.ends_at)<new Date(form.starts_at))throw new Error('O fim não pode ser anterior ao início.');const payload={business_id:form.business_id,title:form.title.trim(),description:form.description.trim()||null,price:form.price===''?null:Number(form.price),original_price:form.original_price===''?null:Number(form.original_price),starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null,status:form.status,updated_at:new Date().toISOString()};const id=editor==='promotion'?editor.rowId:null;const r=editor==='promotion'?await supabase.from('promotions').update(payload).eq('id',id):await supabase.from('promotions').insert(payload);if(r.error)throw r.error;toast(editor==='promotion'?'Promoção atualizada.':'Promoção criada.');closeEditor();await loadAll()}catch(e){toast(e.message||'Erro ao salvar promoção.',true)}finally{setBusy('')}}
 async function savePlan(e){e.preventDefault();setBusy('plan');try{if(!form.name.trim())throw new Error('Informe o nome do plano.');let features={};try{features=JSON.parse(form.features||'{}')}catch{throw new Error('Benefícios/limites precisam ser JSON válido.')};const payload={code:form.code,name:form.name.trim(),description:form.description.trim()||null,price_monthly:form.price_monthly===''?0:Number(form.price_monthly),price_yearly:form.price_yearly===''?0:Number(form.price_yearly),features,active:Boolean(form.active),sort_order:Number(form.sort_order)||0,updated_at:new Date().toISOString()};const id=editor==='plan'?editor.rowId:null;const r=editor==='plan'?await supabase.from('plans').update(payload).eq('id',id):await supabase.from('plans').insert(payload);if(r.error)throw r.error;toast(editor==='plan'?'Plano atualizado.':'Plano criado.');closeEditor();await loadAll()}catch(e){toast(e.message||'Erro ao salvar plano.',true)}finally{setBusy('')}}

 async function removePromotion(row){if(!window.confirm(`Excluir a promoção “${row.title}”? Esta ação não pode ser desfeita.`))return;setBusy(row.id);const r=await supabase.from('promotions').delete().eq('id',row.id);if(r.error)toast(r.error.message,true);else{toast('Promoção excluída.');await loadAll()}setBusy('')}
 async function quickPromotion(row,status){setBusy(row.id);const r=await supabase.from('promotions').update({status,updated_at:new Date().toISOString()}).eq('id',row.id);if(r.error)toast(r.error.message,true);else{toast(status==='published'?'Promoção publicada.':status==='archived'?'Promoção arquivada.':'Status atualizado.');await loadAll()}setBusy('')}
 async function toggleRow(table,row){setBusy(row.id);const r=await supabase.from(table).update({active:!row.active,...(table==='cities'||table==='plans'?{updated_at:new Date().toISOString()}: {})}).eq('id',row.id);if(r.error)toast(r.error.message,true);else await loadAll();setBusy('')}
 async function removeSimple(table,row,label){if(!window.confirm(`Excluir ${label} “${row.name}”?`))return;setBusy(row.id);const r=await supabase.from(table).delete().eq('id',row.id);if(r.error)toast(r.error.message,true);else{toast(`${label[0].toUpperCase()+label.slice(1)} excluído.`);await loadAll()}setBusy('')}

 if(loading)return <div className="admin-v2-card admin-v2-empty"><strong>Carregando gestão…</strong><span>Sincronizando dados da plataforma.</span></div>
 return <div className="admin-v2-management">
  {(message.text||message.error)&&<div className={message.error?'admin-v2-alert':'admin-v2-note'}>{message.text}</div>}
  <section className="admin-v2-stats">
   <div className="admin-v2-card admin-v2-stat"><span>Cidades ativas</span><strong>{stats.cities}</strong><small>Disponíveis no catálogo</small></div>
   <div className="admin-v2-card admin-v2-stat green"><span>Empresas ativas</span><strong>{stats.businesses}</strong><small>Perfis publicados</small></div>
   <div className="admin-v2-card admin-v2-stat amber"><span>Promoções publicadas</span><strong>{stats.published}</strong><small>{stats.pending} aguardando revisão</small></div>
   <div className="admin-v2-card admin-v2-stat purple"><span>Cadastros</span><strong>{cities.length+categories.length+plans.length}</strong><small>Estrutura da plataforma</small></div>
  </section>
  <section className="admin-v2-card admin-v2-section admin-v2-management-nav"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">CENTRAL DE GESTÃO</span><h2>Operação da plataforma</h2><p>Conteúdo e configurações organizados por fluxo.</p></div><div className="admin-v2-actions"><a className="admin-v2-btn" href="/admin/banners">Banners Premium →</a><button className="admin-v2-btn" onClick={()=>window.location.href='/admin/gestao?tab=events'}>Eventos →</button></div></div><div className="admin-v2-management-tabs">{[['promotions','Promoções'],['cities','Cidades'],['categories','Categorias'],['plans','Planos']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);closeEditor()}}>{label}{id==='promotions'&&stats.pending>0?<b>{stats.pending}</b>:null}</button>)}</div></section>

  {tab==='promotions'&&<section className="admin-v2-management-layout">
   <div className="admin-v2-card admin-v2-section admin-v2-list-panel"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">CATÁLOGO COMERCIAL</span><h2>Promoções</h2><p>{filteredPromotions.length} registro(s) encontrado(s).</p></div><button className="admin-v2-btn primary" onClick={newPromotion}>＋ Nova promoção</button></div><div className="admin-v2-toolbar"><div className="admin-v2-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por promoção, empresa ou cidade…"/></div><select value={promotionStatus} onChange={e=>setPromotionStatus(e.target.value)}><option value="all">Todos os status</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="admin-v2-promo-list">{!filteredPromotions.length?<div className="admin-v2-empty"><strong>Nenhuma promoção encontrada</strong><span>Crie uma promoção ou ajuste os filtros.</span></div>:filteredPromotions.map(row=><article className="admin-v2-promo-row" key={row.id}><div className="admin-v2-promo-icon">%</div><div className="admin-v2-promo-main"><div className="admin-v2-promo-top"><strong>{row.title}</strong><span className={`admin-v2-pill ${row.status==='published'?'green':row.status==='pending_review'?'amber':row.status==='rejected'?'red':'blue'}`}>{statusLabels[row.status]||row.status}</span></div><p>{row.businesses?.name||'Empresa'} · {row.businesses?.cities?.name||'Cidade'}{row.businesses?.cities?.state?` - ${row.businesses.cities.state}`:''}</p><small>{row.price!=null?money(row.price):'Sem preço'}{row.original_price!=null?` · de ${money(row.original_price)}`:''} · {when(row.starts_at)} → {row.ends_at?when(row.ends_at):'sem fim'}</small></div><div className="admin-v2-table-actions"><button onClick={()=>{setEditor({type:'promotion',rowId:row.id});setForm({business_id:row.business_id||'',title:row.title||'',description:row.description||'',price:row.price??'',original_price:row.original_price??'',starts_at:dateInput(row.starts_at),ends_at:dateInput(row.ends_at),status:row.status||'pending_review'})}}>Editar</button>{row.status!=='published'&&<button className="primary" onClick={()=>quickPromotion(row,'published')} disabled={busy===row.id}>Publicar</button>}{row.status==='published'&&<button onClick={()=>quickPromotion(row,'archived')} disabled={busy===row.id}>Arquivar</button>}<button className="danger" onClick={()=>removePromotion(row)} disabled={busy===row.id}>Excluir</button></div></article>)}</div></div>
   {editor?.type?.startsWith('promotion')&&<EditorCard title={editor.rowId?'Editar promoção':'Nova promoção'} kicker={editor.rowId?'EDIÇÃO':'NOVO REGISTRO'} description="Controle empresa, conteúdo, valores, período e publicação." onClose={closeEditor}><form onSubmit={savePromotion}><div className="admin-v2-form-grid"><label className="full">Empresa<select value={form.business_id} onChange={e=>setForm({...form,business_id:e.target.value})} required><option value="">Selecione uma empresa</option>{activeBusinesses.map(b=><option key={b.id} value={b.id}>{b.name} · {b.cities?.name||'Cidade'}</option>)}</select></label><label className="full">Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label className="full">Descrição<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Preço promocional<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Preço original<input type="number" min="0" step="0.01" value={form.original_price} onChange={e=>setForm({...form,original_price:e.target.value})}/></label><label>Início<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Fim<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label><label className="full">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="admin-v2-form-meta"><span className="admin-v2-pill blue">Salvamento imediato</span><div className="admin-v2-actions"><button type="button" className="admin-v2-btn" onClick={closeEditor}>Cancelar</button><button className="admin-v2-btn primary" disabled={busy==='promotion'}>{busy==='promotion'?'Salvando…':'Salvar promoção'}</button></div></div></form></EditorCard>}
  </section>}

  {tab==='cities'&&<SimpleManager title="Cidades" kicker="ESTRUTURA GEOGRÁFICA" description="Controle as cidades atendidas e sua disponibilidade no catálogo." rows={cities} openNew={newCity} edit={row=>editCity(row)} remove={row=>removeSimple('cities',row,'cidade')} toggle={row=>toggleRow('cities',row)} busy={busy} renderMeta={row=>`${row.state} · ${row.slug}`} editor={editor?.type?.startsWith('city')} editorTitle={editor==='city-new'?'Nova cidade':'Editar cidade'} onClose={closeEditor}><form onSubmit={saveCity}><div className="admin-v2-form-grid"><label>Nome<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>UF<input value={form.state||''} onChange={e=>setForm({...form,state:e.target.value})} maxLength="2" required/></label><label>Slug<input value={form.slug||''} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>País<input value={form.country||''} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><FormActions busy={busy==='city'} close={closeEditor}/></form></SimpleManager>}
  {tab==='categories'&&<SimpleManager title="Categorias" kicker="ORGANIZAÇÃO DO CATÁLOGO" description="Mantenha a descoberta de empresas simples e consistente." rows={categories} openNew={newCategory} edit={editCategory} remove={row=>removeSimple('categories',row,'categoria')} toggle={row=>toggleRow('categories',row)} busy={busy} renderMeta={row=>`${row.icon||'✦'} · posição ${row.sort_order}`} editor={editor?.type?.startsWith('category')} editorTitle={editor==='category-new'?'Nova categoria':'Editar categoria'} onClose={closeEditor}><form onSubmit={saveCategory}><div className="admin-v2-form-grid"><label>Nome<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Slug<input value={form.slug||''} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Ícone<input value={form.icon||''} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label>Ordem<input type="number" value={form.sort_order??0} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="full">Descrição<textarea rows="4" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><FormActions busy={busy==='category'} close={closeEditor}/></form></SimpleManager>}
  {tab==='plans'&&<section className="admin-v2-management-layout"><div className="admin-v2-card admin-v2-section admin-v2-list-panel"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">MODELO COMERCIAL</span><h2>Planos</h2><p>{plans.length} plano(s) configurado(s).</p></div><button className="admin-v2-btn primary" onClick={newPlan}>＋ Novo plano</button></div><div className="admin-v2-plan-grid">{plans.map(row=><article className="admin-v2-plan-card" key={row.id}><div className="admin-v2-plan-top"><span className="admin-v2-pill blue">{row.code}</span><span className={`admin-v2-pill ${row.active?'green':'red'}`}>{row.active?'Ativo':'Inativo'}</span></div><h3>{row.name}</h3><p>{row.description||'Sem descrição.'}</p><strong>{money(row.price_monthly)} <small>/ mês</small></strong><div className="admin-v2-table-actions"><button onClick={()=>editPlan(row)}>Editar</button><button onClick={()=>toggleRow('plans',row)}>{row.active?'Desativar':'Ativar'}</button></div></article>)}</div></div>{editor?.type?.startsWith('plan')&&<EditorCard title={editor.rowId?'Editar plano':'Novo plano'} kicker="CONFIGURAÇÃO" description="Defina preço, descrição, benefícios e status." onClose={closeEditor}><form onSubmit={savePlan}><div className="admin-v2-form-grid"><label>Código<select value={form.code} onChange={e=>setForm({...form,code:e.target.value})}><option value="free">free</option><option value="pro">pro</option><option value="premium">premium</option></select></label><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="full">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Mensal<input type="number" min="0" step="0.01" value={form.price_monthly} onChange={e=>setForm({...form,price_monthly:e.target.value})}/></label><label>Anual<input type="number" min="0" step="0.01" value={form.price_yearly} onChange={e=>setForm({...form,price_yearly:e.target.value})}/></label><label>Ordem<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="full">Benefícios / limites (JSON)<textarea rows="8" value={form.features} onChange={e=>setForm({...form,features:e.target.value})}/></label></div><div className="admin-v2-form-meta"><div className="checks"><label><input type="checkbox" checked={Boolean(form.active)} onChange={e=>setForm({...form,active:e.target.checked})}/> Plano ativo</label></div><div className="admin-v2-actions"><button type="button" className="admin-v2-btn" onClick={closeEditor}>Cancelar</button><button className="admin-v2-btn primary" disabled={busy==='plan'}>{busy==='plan'?'Salvando…':'Salvar plano'}</button></div></div></form></EditorCard>}</section>}
 </div>
}

function FormActions({busy,close}){return <div className="admin-v2-form-meta"><div className="checks"><label><input type="checkbox" defaultChecked readOnly/> Ativo por padrão</label></div><div className="admin-v2-actions"><button type="button" className="admin-v2-btn" onClick={close}>Cancelar</button><button className="admin-v2-btn primary" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></div>}
function EditorCard({title,kicker,description,onClose,children}){return <div className="admin-v2-card admin-v2-form-panel admin-v2-side-editor"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">{kicker}</span><h2>{title}</h2><p>{description}</p></div><button type="button" className="admin-v2-close-inline" onClick={onClose}>×</button></div>{children}</div>}
function SimpleManager({title,kicker,description,rows,openNew,edit,remove,toggle,busy,renderMeta,editor,editorTitle,onClose,children}){return <section className="admin-v2-management-layout"><div className="admin-v2-card admin-v2-section admin-v2-list-panel"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">{kicker}</span><h2>{title}</h2><p>{description}</p></div><button className="admin-v2-btn primary" onClick={openNew}>＋ Novo</button></div><div className="admin-v2-simple-list">{!rows.length?<div className="admin-v2-empty"><strong>Nenhum registro</strong><span>Cadastre o primeiro item usando o botão acima.</span></div>:rows.map(row=><article className="admin-v2-list-row" key={row.id}><div><strong>{row.name}</strong><small>{renderMeta(row)}</small></div><div className="admin-v2-table-actions"><button onClick={()=>edit(row)}>Editar</button><button onClick={()=>toggle(row)}>{row.active?'Desativar':'Ativar'}</button><button className="danger" onClick={()=>remove(row)} disabled={busy===row.id}>Excluir</button></div></article>)}</div></div>{editor&&<EditorCard title={editorTitle} kicker="EDIÇÃO" description={`Atualize os dados de ${title.toLowerCase()} sem sair do painel.`} onClose={onClose}>{children}</EditorCard>}</section>}
