import React,{useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import './core.css'
const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
export default function AdminHomePage(){
 const [checking,setChecking]=useState(true),[allowed,setAllowed]=useState(false),[email,setEmail]=useState('')
 useEffect(()=>{let live=true;(async()=>{if(!db){setChecking(false);return}const {data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setChecking(false);return}setEmail(session.user.email||'');const {data}=await db.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(live){setAllowed(data?.role==='admin');setChecking(false)}})();return()=>{live=false}},[])
 if(checking)return <div className="app"><main className="page section"><div className="empty"><h3>Verificando acesso administrativo…</h3></div></main></div>
 if(!allowed)return <div className="app"><main className="page section"><div className="empty"><h1>Acesso restrito</h1><p>Esta área é exclusiva para administradores.</p><a className="btn primary" href="/laguna">Voltar ao site</a></div></main></div>
 return <div className="app"><header className="topbar"><div className="nav"><a className="brand" href="/laguna"><span className="brand-mark">V</span><span>Vitrine<span className="brand-accent">Local</span></span></a><div className="nav-spacer"/><span className="muted">{email}</span><a className="btn" href="/laguna">Voltar</a></div></header><main className="page section"><span className="section-kicker">ADMINISTRAÇÃO</span><h1>Painel administrativo</h1><p className="muted">Gerencie a plataforma pelo catálogo, publicidade, agenda e configurações comerciais.</p><div className="business-grid" style={{marginTop:24}}><a className="profile-card" style={{padding:24,textDecoration:'none'}} href="/admin/gestao"><span className="section-kicker">PLATAFORMA</span><h2>Gestão da plataforma</h2><p>Cidades, categorias, promoções, banners e planos.</p><span className="link">Abrir gestão →</span></a><a className="profile-card" style={{padding:24,textDecoration:'none'}} href="/admin/empresas"><span className="section-kicker">CATÁLOGO</span><h2>Empresas</h2><p>Liste todas as empresas cadastradas e edite os dados comerciais.</p><span className="link">Gerenciar empresas →</span></a><a className="profile-card" style={{padding:24,textDecoration:'none'}} href="/admin/gestao"><span className="section-kicker">AGENDA</span><h2>Eventos</h2><p>Cadastre, edite, publique e destaque os eventos da cidade.</p><span className="link">Gerenciar eventos →</span></a><a className="profile-card" style={{padding:24,textDecoration:'none'}} href="/admin/banners"><span className="section-kicker">PUBLICIDADE</span><h2>Banners Premium</h2><p>Edite os espaços patrocinados da Home.</p><span className="link">Gerenciar banners →</span></a><a className="profile-card" style={{padding:24,textDecoration:'none'}} href="/planos"><span className="section-kicker">COMERCIAL</span><h2>Planos</h2><p>Veja a experiência pública dos planos comerciais.</p><span className="link">Ver planos →</span></a></div></main></div>
}
