import React,{useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import AdminShell from './AdminShell.jsx'
import './admin-analytics.css'
const U=import.meta.env.VITE_SUPABASE_URL,KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&KEY?createClient(U,KEY):null
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function AdminAnalyticsPage(){
 const [s,setS]=useState({checking:true,allowed:false,session:null,events:[],businesses:[],plans:[],subs:[]})
 useEffect(()=>{let live=true;(async()=>{if(!db){setS(x=>({...x,checking:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setS(x=>({...x,checking:false}));return}const{data:p,error:pe}=await db.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(!live)return;if(pe||p?.role!=='admin'){setS(x=>({...x,checking:false,session}));return}const d=new Date();d.setDate(d.getDate()-29);const[e,b,pl,sub]=await Promise.all([db.from('analytics_events').select('event_type,business_id,created_at').gte('created_at',d.toISOString()),db.from('businesses').select('id,name,status'),db.from('plans').select('id,code,name,price_monthly,price_yearly').eq('active',true),db.from('subscriptions').select('id,business_id,plan_id,status,billing_interval').in('status',['active','trialing'])]);if(live)setS({checking:false,allowed:true,session,events:e.data||[],businesses:b.data||[],plans:pl.data||[],subs:sub.data||[]})})();return()=>{live=false}},[])
 const m=useMemo(()=>{const n=t=>s.events.filter(e=>e.event_type===t).length;const pm=new Map(s.plans.map(p=>[p.id,p]));const mrr=s.subs.reduce((v,x)=>{const p=pm.get(x.plan_id);return v+(x.billing_interval==='yearly'?Number(p?.price_yearly||0)/12:Number(p?.price_monthly||0))},0);return{views:n('profile_view'),wa:n('whatsapp_click'),ig:n('instagram_click'),web:n('website_click'),active:s.businesses.filter(b=>b.status==='active').length,mrr}},[s])
 const top=useMemo(()=>{const names=new Map(s.businesses.map(b=>[b.id,b.name]));const c={};s.events.forEach(e=>{if(e.business_id)c[e.business_id]=(c[e.business_id]||0)+1});return Object.entries(c).map(([id,count])=>({id,name:names.get(id)||'Empresa',count})).sort((a,b)=>b.count-a.count).slice(0,6)},[s])
 const days=useMemo(()=>{const a=[];for(let i=29;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);a.push({k,label:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),v:s.events.filter(e=>e.created_at?.slice(0,10)===k).length})}const max=Math.max(1,...a.map(x=>x.v));return{a,max}},[s.events])
 if(s.checking)return <div className="admin-v2-shell"><div className="admin-v2-empty">Verificando acesso administrativo…</div></div>
 if(!s.allowed)return <div className="admin-v2-shell"><main className="admin-v2-content"><div className="admin-v2-card admin-v2-empty"><strong>Acesso restrito</strong><span>Esta área é exclusiva para administradores.</span><a className="admin-v2-btn primary" href="/admin">Voltar ao admin</a></div></main></div>
 return <AdminShell active="analytics" title="Analytics" description="Descoberta, contatos, desempenho comercial e receita estimada." email={s.session?.user?.email}><section className="aa-kpis"><K label="Visualizações" v={m.views} n="perfil · 30 dias"/><K label="WhatsApp" v={m.wa} n="cliques · 30 dias" c="green"/><K label="Site" v={m.web} n="cliques · 30 dias" c="purple"/><K label="MRR estimado" v={money(m.mrr)} n={`${s.subs.length} assinatura(s)`} c="amber"/></section><section className="aa-grid"><div className="admin-v2-card aa-card"><div className="aa-head"><div><span className="admin-v2-kicker">ENGAJAMENTO</span><h2>Atividade diária</h2><p>Eventos capturados nos últimos 30 dias.</p></div><strong>{s.events.length}</strong></div><div className="aa-chart">{days.a.map(x=><div className="aa-bar-wrap" key={x.k} title={`${x.label}: ${x.v}`}><span className="aa-bar" style={{height:`${Math.max(4,x.v/days.max*100)}%`}}/><small>{x.label}</small></div>)}</div></div><div className="admin-v2-card aa-card"><div className="aa-head"><div><span className="admin-v2-kicker">TOP NEGÓCIOS</span><h2>Mais engajadas</h2><p>Por volume de eventos.</p></div></div><div className="aa-ranking">{top.length?top.map((x,i)=><div className="aa-rank" key={x.id}><b>{i+1}</b><div><strong>{x.name}</strong><small>{x.count} eventos</small></div></div>):<div className="admin-v2-empty">Ainda não há eventos por empresa.</div>}</div></div></section><section className="admin-v2-card aa-card"><div className="aa-operational"><div><span>Empresas ativas</span><strong>{m.active}</strong></div><div><span>Assinaturas ativas</span><strong>{s.subs.length}</strong></div><div><span>MRR estimado</span><strong>{money(m.mrr)}</strong></div><div><span>Instagram</span><strong>{m.ig}</strong></div></div></section></AdminShell>
}
function K({label,v,n,c=''}){return <div className={`admin-v2-card aa-kpi ${c}`}><span>{label}</span><strong>{v}</strong><small>{n}</small></div>}
