import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import AdminShell from './AdminShell.jsx'
import'./admin-advertising-sales.css'

const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(v)):'—'
const creativeLabel=r=>r.creative_mode==='design'?'VitrineLocal cria a arte':'Empresa enviou a arte'
const paymentLabel=r=>r.payment_status==='paid'?'Pago':r.payment_status==='awaiting_payment'?'Aguardando pagamento':r.payment_status==='failed'?'Falha no pagamento':r.payment_status==='canceled'?'Cancelado':'Ainda não liberado'
export default function AdminAdvertisingSalesPage(){
 const[s,setS]=useState({checking:true,allowed:false,session:null,requests:[],ads:[],error:''}),[busy,setBusy]=useState(''),[note,setNote]=useState('')
 async function load(){if(!db)return;const{data:{session}}=await db.auth.getSession();if(!session){setS(x=>({...x,checking:false}));return}const{data:profile,error:pe}=await db.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(pe||profile?.role!=='admin'){setS({checking:false,allowed:false,session,error:'Acesso restrito.'});return}const[r,a]=await Promise.all([db.from('advertising_requests').select('id,business_id,title,description,target_url,desired_start_at,desired_end_at,monthly_budget,final_price,status,admin_note,created_at,updated_at,creative_mode,artwork_url,artwork_path,payment_status,paid_at,approved_at,stripe_subscription_id,businesses(id,name,city_id,cities(name,state))').order('created_at',{ascending:false}),db.from('advertisements').select('id,advertising_request_id,business_id,title,active,starts_at,ends_at,monthly_price,billing_status,image_url,businesses(name),cities(name,state)').eq('placement','home_banner').order('created_at',{ascending:false})]);if(r.error||a.error){setS(x=>({...x,checking:false,allowed:true,session,error:(r.error||a.error)?.message||'Falha ao carregar publicidade.'}));return}setS({checking:false,allowed:true,session,requests:r.data||[],ads:a.data||[],error:''})}
 useEffect(()=>{load()},[])
 const metrics=useMemo(()=>({pending:s.requests.filter(r=>r.status==='pending').length,awaiting:s.requests.filter(r=>r.payment_status==='awaiting_payment').length,paid:s.requests.filter(r=>r.payment_status==='paid').length,active:s.ads.filter(a=>a.active&&(!a.ends_at||new Date(a.ends_at)>new Date())).length}),[s.requests,s.ads])
 async function review(request,status){const id=request.id;setBusy(id);setNote('');if(status==='approved'){const price=Number(document.getElementById(`final-price-${id}`)?.value||0);if(!Number.isFinite(price)||price<=0){setNote('Defina um valor final maior que zero antes de aprovar.');setBusy('');return}const payload={status:'approved',final_price:price,admin_note:`Campanha aprovada. ${request.creative_mode==='design'?'A equipe deve preparar a arte antes da ativação.':'A arte enviada será usada após a confirmação do pagamento.'}`};const{error}=await db.from('advertising_requests').update(payload).eq('id',id);if(error)setNote(error.message);else setNote('Solicitação aprovada e pagamento liberado.');await load()}else{const{error}=await db.from('advertising_requests').update({status:'rejected',admin_note:'Solicitação rejeitada pelo administrador.'}).eq('id',id);if(error)setNote(error.message);else setNote('Solicitação rejeitada.');await load()}setBusy('')}
 if(s.checking)return <div className="admin-v2-shell"><div className="admin-v2-empty">Verificando acesso administrativo…</div></div>
 if(!s.allowed)return <div className="admin-v2-shell"><main className="admin-v2-content"><div className="admin-v2-card admin-v2-empty"><strong>Acesso restrito</strong><span>{s.error||'Esta área é exclusiva para administradores.'}</span><a className="admin-v2-btn primary" href="/admin">Voltar</a></div></main></div>
 return <AdminShell active="advertising" title="Publicidade Premium" description="Venda, aprovação, cobrança e ativação das campanhas Premium." email={s.session?.user?.email}>
  {note&&<div className="asa-note">{note}</div>}
  <section className="admin-v2-stats asa-stats"><Stat label="Em análise" value={metrics.pending}/><Stat label="Aguardando pagamento" value={metrics.awaiting}/><Stat label="Pagas" value={metrics.paid}/><Stat label="Campanhas ativas" value={metrics.active}/></section>
  <section className="admin-v2-card admin-v2-section"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">PIPELINE COMERCIAL</span><h2>Solicitações de Banner Premium</h2><p>Revise material, defina o valor final e libere o pagamento.</p></div><a className="admin-v2-btn" href="/admin/banners">Editor de banners →</a></div>{s.requests.length?<div className="asa-list">{s.requests.map(r=><article className="asa-row" key={r.id}><div className="asa-art">{r.artwork_url?<img src={r.artwork_url} alt="Arte enviada"/>:'★'}</div><div className="asa-main"><strong>{r.title}</strong><small>{r.businesses?.name||'Empresa'} · {r.businesses?.cities?.name||'Cidade'}{r.businesses?.cities?.state?` - ${r.businesses.cities.state}`:''}</small><span>{creativeLabel(r)} · enviado {dateTime(r.created_at)}</span><span>Status: {r.status} · {paymentLabel(r)}</span>{r.admin_note&&<em>{r.admin_note}</em>}</div><div className="asa-controls">{r.status==='pending'&&<><label>Valor final mensal<input id={`final-price-${r.id}`} type="number" min="0" step="0.01" placeholder={r.monthly_budget?String(r.monthly_budget):'Ex.: 299.90'} defaultValue={r.final_price||r.monthly_budget||''}/></label><div className="asa-buttons"><button className="admin-v2-btn primary" disabled={busy===r.id} onClick={()=>review(r,'approved')}>Aprovar e liberar pagamento</button><button className="admin-v2-btn danger" disabled={busy===r.id} onClick={()=>review(r,'rejected')}>Rejeitar</button></div></>}{r.status==='approved'&&<div className="asa-offer"><strong>{r.final_price>0?money(r.final_price):'Valor não definido'}/mês</strong><span>{paymentLabel(r)}</span><small>O cancelamento de cobranças ocorre pelo Stripe/portal de assinatura.</small></div>}</div></article>)}</div>:<div className="admin-v2-empty">Nenhuma solicitação recebida.</div>}</section>
  <section className="admin-v2-card admin-v2-section"><div className="admin-v2-section-head"><div><span className="admin-v2-kicker">CAMPANHAS</span><h2>Campanhas sincronizadas com cobrança</h2><p>O webhook Stripe cria/atualiza o banner após confirmação do pagamento. A manutenção agendada controla o início e fim.</p></div></div>{s.ads.length?<div className="asa-campaigns">{s.ads.map(a=><div className="asa-campaign" key={a.id}><div><strong>{a.title}</strong><span>{a.businesses?.name||'Empresa'} · {a.cities?.name||'Cidade'}{a.cities?.state?` - ${a.cities.state}`:''}</span><small>{money(a.monthly_price)}/mês · {a.billing_status} · {a.active?'Ativo':'Aguardando início/arte'}</small></div><a className="admin-v2-btn" href="/admin/banners">Gerenciar</a></div>)}</div>:<div className="admin-v2-empty">Nenhuma campanha paga ainda.</div>}</section>
 </AdminShell>
}
function Stat({label,value}){return <div className="admin-v2-card admin-v2-stat"><span>{label}</span><strong>{value}</strong></div>}
