import React from 'react'
import { createRoot } from 'react-dom/client'
import { supabase } from './supabase-client.js'
import SiteHeader from './SiteHeader.jsx'
import AnalyticsTracker from './analytics-tracker.jsx'
import AppErrorBoundary from './AppErrorBoundary.jsx'
import PrelaunchGate from './PrelaunchGate.jsx'
import PrelaunchPlansPage from './PrelaunchPlansPage.jsx'
import EventsPage from './EventsPage.jsx'
import AdminPremiumBannerPage from './AdminPremiumBannerPage.jsx'
import AdminAdvertisingPage from './AdminAdvertisingPage.jsx'
import AdminAdvertisingSalesPage from './AdminAdvertisingSalesPage.jsx'
import AdminPlatformPage from './AdminPlatformPage.jsx'
import AdminHomePage from './AdminHomePage.jsx'
import AdminAnalyticsPage from './AdminAnalyticsPage.jsx'
import AdminBusinessesPage from './AdminBusinessesPage.jsx'
import AdminReviewsPage from './AdminReviewsPage.jsx'
import AdminUsersPage from './AdminUsersPage.jsx'
import AdminOnboardingPage from './AdminOnboardingPage.jsx'
import BusinessRegistrationPage from './BusinessRegistrationPage.jsx'
import CityHomePage from './CityHomePage.jsx'
import AccountPage from './AccountWorkspacePage.jsx'
import AccountOnboardingPage,{AccountOnboardingGate} from './AccountOnboardingPage.jsx'
import CommercialAnalyticsPage from './CommercialAnalyticsPage.jsx'
import MerchantAdvertisingPage from './MerchantAdvertisingPage.jsx'
import MerchantAdvertisingSalesPage from './MerchantAdvertisingSalesPage.jsx'
import AuthPage from './AuthPage.jsx'
import UserAuthPage from './UserAuthPage.jsx'
import UserProfilePage from './UserProfilePage.jsx'
import PasswordUpdatePage from './PasswordUpdatePage.jsx'
import BillingPlansPage from './BillingPlansPage.jsx'
import ModernBusinessProfilePage from './ModernBusinessProfilePage.jsx'
import ModernBusinessesPage from './ModernBusinessesPage.jsx'
import { PromotionsPage,NotFoundPage } from './PublicCatalogPages.jsx'
import { PrivacyPage,TermsPage } from './LegalPages.jsx'
import './core.css'
import './events.css'
import './city-home.css'
import './commercial-home.css'
import './home-v3.css'
import './auth-page.css'
import './billing-plans.css'
import './billing-funnel.css'
import './public-polish.css'
import './vitrine-ux-adjustments.css'
import './modern-business-profile.css'
import './modern-business-profile-v2.css'
import './modern-business-list.css'
import './modern-gallery-lightbox.css'
import './review-card-rating.css'
import './modern-gallery-lightbox.js'
import './admin-city-actions.js'
import './business-registration.css'
import './banner-timezone-fix.js'
import './account-premium-nav.js'
import './account-modern.css'
import './site-header.css'
import './site-header-v2.css'
import './site-header-v3.css'
import './site-header-dedup.css'
import './admin-v2.css'
import './admin-management.css'
import './admin-analytics.css'
import './admin-users.css'
import './admin-onboarding.css'
import './analytics.css'
import './commercial-analytics.css'
import './merchant-advertising.css'
import './merchant-advertising-sales.css'
import './admin-advertising.css'
import './admin-advertising-sales.css'
import './modern-business-profile-v4.css'
import './phase2-product.css'
import './phase2-enhancements.js'
import './account-premium-ad-shortcut.css'
import './mobile-responsive-fixes.css'
import './review-ui-mount.js'
import './review-card-rating.js'
import './user-profile.css'
import './ux-refinement.css'
import './mobile-launch-fixes.css'
import './media-adapter.js'
import './categories-ordering.js'
import './categories-home-ux.js'
import './prelaunch.css'
import './prelaunch-plans.css'

const normalizePath=p=>p.replace(/\/+$/,'')||'/'
const partsOf=p=>p.split('/').filter(Boolean).map(decodeURIComponent)
function getCityRoute(path){
 const p=partsOf(path)
 if(p.length===0)return {kind:'home',citySlug:'laguna'}
 if(p.length===1&&!['login','planos','conta','admin','privacidade','termos','atualizar-senha','usuario'].includes(p[0].toLowerCase()))return {kind:'home',citySlug:p[0].toLowerCase()}
 if(p.length===2&&!['admin','usuario'].includes(p[0].toLowerCase())){const citySlug=p[0].toLowerCase(),child=p[1].toLowerCase();if(child==='eventos')return {kind:'events',citySlug};if(child==='empresas')return {kind:'businesses',citySlug};if(child==='promocoes')return {kind:'promotions',citySlug}}
 if(p.length===3&&p[1].toLowerCase()==='empresa')return {kind:'business',citySlug:p[0].toLowerCase(),businessSlug:p[2]}
 return null
}
function EventRoute({citySlug}){const[city,setCity]=React.useState(supabase?null:{id:'fallback',name:'Laguna',state:'SC',slug:citySlug,active:true}),[loading,setLoading]=React.useState(Boolean(supabase));React.useEffect(()=>{let live=true;(async()=>{if(!supabase){setLoading(false);return}const{data}=await supabase.from('cities').select('id,name,state,slug,country,active').eq('slug',citySlug).eq('active',true).maybeSingle();if(live){setCity(data||null);setLoading(false)}})();return()=>{live=false}},[citySlug]);if(loading)return <div className="app"><div className="loader"/></div>;if(!city)return <div className="app"><main className="page section"><a className="back-link" href="/laguna">← Voltar</a><div className="empty"><h3>Cidade não encontrada.</h3></div></main></div>;return <div className="app"><EventsPage supabase={supabase} city={city} onBack={()=>location.href=`/${city.slug}`}/></div>}
function AccountRoute(){const params=new URLSearchParams(location.search),isNewBusiness=params.get('new')==='business';if(isNewBusiness)return <BusinessRegistrationPage/>;return <div className="account-route-shell"><AccountOnboardingGate><AccountPage/></AccountOnboardingGate></div>}
function UserProfileRoute(){const[checking,setChecking]=React.useState(true);React.useEffect(()=>{let live=true;(async()=>{if(!supabase){if(live)setChecking(false);return}const{data:{session}}=await supabase.auth.getSession();if(!session){if(live)setChecking(false);return}const[{data:profile},{count:businessCount,error:businessError}]=await Promise.all([supabase.from('profiles').select('role').eq('id',session.user.id).maybeSingle(),supabase.from('businesses').select('id',{count:'exact',head:true}).eq('owner_id',session.user.id)]);if(!live)return;if(profile?.role==='admin'||profile?.role==='business_owner'||(!businessError&&(businessCount||0)>0)){window.location.replace('/conta');return}setChecking(false)})();return()=>{live=false}},[]);if(checking)return <main className="user-profile-page"><div className="user-profile-loading">Carregando perfil…</div></main>;return <UserProfilePage/>}
function AccountModerationGuard({children}){React.useEffect(()=>{if(!supabase)return;let live=true;const check=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session||!live)return;const{data:profile}=await supabase.from('profiles').select('role,account_status').eq('id',session.user.id).maybeSingle();if(!live)return;if((profile?.role==='user'||profile?.role==='business_owner')&&profile.account_status&&profile.account_status!=='active'){await supabase.auth.signOut();window.location.href=`/usuario/login?blocked=${encodeURIComponent(profile.account_status)}`}};check();const sub=supabase.auth.onAuthStateChange(()=>setTimeout(check,0));return()=>{live=false;sub?.data?.subscription?.unsubscribe?.()}},[]);return children}
function RootRoute(){const path=normalizePath(location.pathname);if(path==='/em-breve/planos')return <PrelaunchPlansPage/>;if(path==='/login')return <AuthPage/>;if(path==='/usuario/login'||path==='/usuario/cadastro')return <UserAuthPage/>;if(path==='/usuario/perfil')return <UserProfileRoute/>;if(path==='/planos')return <BillingPlansPage/>;if(path==='/conta/onboarding')return <AccountOnboardingPage/>;if(path==='/conta')return <AccountRoute/>;if(path==='/conta/analytics')return <CommercialAnalyticsPage/>;if(path==='/conta/analytics-comercial')return <CommercialAnalyticsPage/>;if(path==='/conta/publicidade')return <MerchantAdvertisingSalesPage/>;if(path==='/conta/publicidade-legado')return <MerchantAdvertisingPage/>;if(path==='/conta/nova')return <BusinessRegistrationPage/>;if(path==='/atualizar-senha')return <PasswordUpdatePage/>;if(path==='/privacidade')return <PrivacyPage/>;if(path==='/termos')return <TermsPage/>;if(path==='/admin')return <AdminHomePage/>;if(path==='/admin/analytics')return <AdminAnalyticsPage/>;if(path==='/admin/empresas')return <AdminBusinessesPage/>;if(path==='/admin/usuarios')return <AdminUsersPage/>;if(path==='/admin/novo-parceiro')return <AdminOnboardingPage mode="partner"/>;if(path==='/admin/novo-usuario')return <AdminOnboardingPage mode="user"/>;if(path==='/admin/nova-empresa')return <AdminOnboardingPage mode="business"/>;if(path==='/admin/avaliacoes')return <AdminReviewsPage/>;if(path==='/admin/banners')return <AdminPremiumBannerPage supabase={supabase}/>;if(path==='/admin/publicidade')return <AdminAdvertisingSalesPage/>;if(path==='/admin/publicidade-legado')return <AdminAdvertisingPage/>;if(path==='/admin/gestao')return <AdminPlatformPage supabase={supabase}/>;const route=getCityRoute(path);if(!route)return <NotFoundPage/>;if(route.kind==='home')return <CityHomePage citySlug={route.citySlug}/>;if(route.kind==='events')return <EventRoute citySlug={route.citySlug}/>;if(route.kind==='businesses')return <ModernBusinessesPage citySlug={route.citySlug}/>;if(route.kind==='promotions')return <PromotionsPage citySlug={route.citySlug}/>;if(route.kind==='business')return <ModernBusinessProfilePage citySlug={route.citySlug} businessSlug={route.businessSlug}/>;return <NotFoundPage/>}
function App(){const path=normalizePath(location.pathname),isAdmin=path.startsWith('/admin'),isStandalone=path==='/conta/onboarding',isPrelaunchPlans=path==='/em-breve/planos';return <AppErrorBoundary><AccountModerationGuard><><PrelaunchGate path={path}>{!isAdmin&&!isStandalone&&!isPrelaunchPlans&&<SiteHeader/>}{!isAdmin&&!isStandalone&&!isPrelaunchPlans&&<AnalyticsTracker/>}<RootRoute/></PrelaunchGate></></AccountModerationGuard></AppErrorBoundary>}
createRoot(document.getElementById('root')).render(<App/>)
