import React,{useEffect,useMemo,useState}from'react'
import {createClient}from'@supabase/supabase-js'
import './billing-plans.css'

const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const FALLBACK=[
 {id:'free',code:'free',name:'Grátis',price_monthly:0,price_yearly:0,description:'Presença básica e recursos essenciais.',features:{photos:5,items:10,promotions:1,ai_posts:3,analytics:false,featured:false,verified:false,city_instagram:false,advanced_analytics:false}},
 {id:'pro',code:'pro',name:'Pro',price_monthly:29.9,price_yearly:299,description:'Mais destaque e recursos para crescer.',features:{photos:30,items:50,promotions:5,ai_posts:30,analytics:true,featured:true,verified:true,city_instagram:false,advanced_analytics:false}},
 {id:'premium',code:'premium',name:'Premium',price_monthly:59.9,price_yearly:599,description:'Máxima presença e recursos avançados.',features:{photos:100,items:200,promotions:20,ai_posts:100,analytics:true,featured:true,verified:true,city_instagram:true,advanced_analytics:true}}
]
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(v)):'—'
const rank={free:0,pro:1,premium:2}
const statusCopy={active:'Assinatura ativa',trialing:'Período de teste',pending:'Aguardando pagamento',past_due:'Pagamento pendente',unpaid:'Pagamento em atraso',paused:'Assinatura pausada',incomplete:'Pagamento ainda não concluído'}
const labelForFeature=(key,limit)=>({photos:`Até ${limit} fotos/mídias`,items:`Até ${limit} produtos/serviços`,promotions:`Até ${limit} promoções`,ai_posts:`${limit} usos de IA por mês`,analytics:'Analytics completo',featured:'Destaque nas buscas',verified:'Selo de verificação',city_instagram:'Presença no Instagram da cidade',advanced_analytics:'Estatísticas avançadas'})[key]||key
function featureList(features={}){const order=['photos','items','promotions','ai_posts','analytics','featured','verified','advanced_analytics','city_instagram'];return order.map(key=>{const raw=features[key],limit=Number(features[`${key}_limit`]??raw);if(['photos','items','promotions','ai_posts'].includes(key))return Number.isFinite(limit)&&limit>0?labelForFeature(key,limit):null;return raw===true?labelForFeature(key):null}).filter(Boolean).slice(0,9)}

export default function BillingPlansPage(){
 const[plans,setPlans]=useState(FALLBACK),[session,setSession]=useState(null),[businesses,setBusinesses]=useState([]),[businessId,setBusinessId]=useState(''),[interval,setIntervalValue]=useState('monthly'),[current,setCurrent]=useState(null),[msg,setMsg]=useState(''),[msgTone,setMsgTone]=useState('info'),[busy,setBusy]=useState(false),[onboarding,setOnboarding]=useState(false),[loading,setLoading]=useState(true)
 const params=useMemo(()=>new URLSearchParams(location.search),[])
 async function loadCurrent(uid,bid){if(!db||!uid||!bid){setCurrent(null);return}const{data,error}=await db.from('subscriptions').select('id,business_id,status,provider,provider_subscription_id,current_period_start,current_period_end,ends_at,cancel_at_period_end,billing_interval,provider_price_id,plan_id,scheduled_plan_id,scheduled_billing_interval,scheduled_change_at').eq('user_id',uid).eq('business_id',bid).in('provider',['mercadopago','stripe','manual']).in('status',['active','trialing','pending','past_due','unpaid','paused','incomplete']).order('created_at',{ascending:false});if(error){setMsg(error.message||'Não foi possível verificar a assinatura.');setMsgTone('error');return}setCurrent((data||[]).find(x=>x.provider==='mercadopago')||(data||[]).find(x=>x.provider==='stripe')||(data||[])[0]||null)}
 useEffect(()=>{let live=true;(async()=>{const requested=params.get('business_id')||'';setOnboarding(params.get('onboarding')==='1');const checkout=params.get('checkout');if(checkout==='success'){setMsg('Pagamento enviado. Estamos confirmando sua assinatura; isso pode levar alguns segundos.');setMsgTone('success')}else if(checkout==='cancelled'){setMsg('Checkout cancelado. Nenhuma cobrança foi concluída nesta sessão.');setMsgTone('info')}if(!db){setLoading(false);return}const[{data:{session:s}},{data:p,error:pe}]=await Promise.all([db.auth.getSession(),db.from('plans').select('id,code,name,price_monthly,price_yearly,description,features').eq('active',true).order('sort_order')]);if(!live)return;setSession(s||null);if(!pe&&p?.length)setPlans(p);if(!s){setLoading(false);return}const{data:b,error:be}=await db.from('businesses').select('id,name,status').eq('owner_id',s.user.id).order('created_at',{ascending:false});if(!live)return;if(be){setMsg(be.message||'Não foi possível carregar suas empresas.');setMsgTone('error')}setBusinesses(b||[]);const chosen=(b||[]).find(x=>x.id===requested)||(b||[])[0];setBusinessId(chosen?.id||'');if(chosen?.id)await loadCurrent(s.user.id,chosen.id);setLoading(false)})();return()=>{live=false}},[])
 useEffect(()=>{if(session?.user?.id&&businessId){loadCurrent(session.user.id,businessId);if(params.get('checkout')==='success'){let attempts=0;const timer=window.setInterval(async()=>{attempts+=1;await loadCurrent(session.user.id,businessId);if(attempts>=6)window.clearInterval(timer)},2000);return()=>window.clearInterval(timer)}}},[session?.user?.id,businessId])
 const annualSaving=useMemo(()=>plans.reduce((acc,p)=>{const full=Number(p.price_monthly||0)*12,yearly=Number(p.price_yearly||0);acc[p.code]=full>0&&yearly>0?Math.max(0,Math.round((1-yearly/full)*100)):0;return acc},{}),[plans])
 const currentCode=current?.plan_id?(plans.find(p=>p.id===current.plan_id)?.code||'free'):'free',currentPlan=plans.find(p=>p.code===currentCode)||plans[0],scheduledPlan=current?.scheduled_plan_id?plans.find(p=>p.id===current.scheduled_plan_id):null,effectiveInterval=current?.billing_interval||'monthly',changingAllowed=Boolean(['mercadopago','stripe'].includes(current?.provider)&&current?.provider_subscription_id&&!['past_due','unpaid','incomplete','pending'].includes(current.status))
 async function checkout(plan){if(plan.code==='free'){setMsg(current?'Use “Gerenciar assinatura” ou cancele sua assinatura para ir ao Grátis.':'O plano Grátis não exige pagamento.');setMsgTone('info');if(!current)window.setTimeout(()=>location.href=businessId?`/conta?business_id=${encodeURIComponent(businessId)}`:'/conta',500);return}if(!session)return location.href=`/login?next=${encodeURIComponent(location.pathname+location.search)}`;if(!businessId){setMsg('Cadastre ou selecione uma empresa antes de contratar um plano pago.');setMsgTone('error');return}
 setBusy(true);setMsg('Preparando checkout seguro…');setMsgTone('info')
 const{data:{session:freshSession},error:sessionError}=await db.auth.getSession()
 if(sessionError||!freshSession?.access_token){setMsg('Sua sessão expirou. Faça login novamente para continuar.');setMsgTone('error');setBusy(false);return}
 let data,error
 try{({data,error}=await db.functions.invoke('create-checkout-session',{body:{business_id:businessId,plan_code:plan.code,interval},headers:{Authorization:`Bearer ${freshSession.access_token}`}}))}catch(err){error=err}
 if(error){let detail=error?.message||'Falha ao iniciar o pagamento.';try{if(error?.context instanceof Response){const payload=await error.context.json().catch(()=>null);if(payload?.error)detail=payload.error}}catch{}setMsg(detail);setMsgTone('error');setBusy(false);return}
 if(data?.url){location.href=data.url;return}setMsg('Não foi possível obter o endereço do checkout.');setMsgTone('error');setBusy(false)}
 async function changePlan(plan){if(!['mercadopago','stripe'].includes(current?.provider)){setMsg('Este plano foi concedido manualmente e não possui cobrança recorrente automática para alteração.');setMsgTone('info');return}if(!current?.provider_subscription_id){return checkout(plan)}if(!changingAllowed){setMsg('Regularize a assinatura antes de trocar o plano. Use “Gerenciar assinatura”.');setMsgTone('error');return}if(plan.code===currentCode&&interval===effectiveInterval&&!current.cancel_at_period_end){setMsg('Sua assinatura já está neste plano e ciclo de cobrança.');setMsgTone('info');return}
 if(interval!==effectiveInterval){setMsg(`A troca entre cobrança ${effectiveInterval==='yearly'?'anual':'mensal'} e ${interval==='yearly'?'anual':'mensal'} exige uma nova autorização no Mercado Pago. O VitrineLocal não altera o ciclo de uma assinatura existente automaticamente.`);setMsgTone('info');return}
 setBusy(true);setMsg('Atualizando sua assinatura no Mercado Pago…');setMsgTone('info');const{data,error}=await db.functions.invoke('change-subscription-plan',{body:{business_id:businessId,plan_code:plan.code,interval}});if(error){let detail=error.message||'Não foi possível alterar o plano.';try{if(error.context instanceof Response){const payload=await error.context.json().catch(()=>null);if(payload?.error)detail=payload.error}}catch{}setMsg(detail);setMsgTone('error');setBusy(false);return}if(data?.mode==='immediate'){setMsg(`Plano alterado para ${plan.name}. Os novos limites já estão disponíveis.`);setMsgTone('success')}else if(data?.mode==='scheduled'){setMsg(`Troca para ${plan.name} agendada para ${dateTime(data.effective_at)}.`);setMsgTone('success')}else if(data?.mode==='canceled'){setMsg(`Sua assinatura foi encerrada. Você pode contratar novamente um plano pelo Mercado Pago.`);setMsgTone('success')}else if(data?.mode==='resumed'){setMsg(`Cancelamento revertido. Sua assinatura ${plan.name} continua ativa.`);setMsgTone('success')}else{setMsg('Assinatura atualizada.');setMsgTone('success')}await loadCurrent(session.user.id,businessId);setBusy(false)}
 async function portal(){if(!current?.provider_subscription_id){setMsg('Nenhuma assinatura encontrada para esta empresa.');setMsgTone('error');return}setBusy(true);const{data,error}=await db.functions.invoke('billing-portal',{body:{business_id:businessId,return_to:'plans'}});if(error){setMsg(error.message||'Falha ao abrir a gestão da assinatura.');setMsgTone('error');setBusy(false);return}if(data?.url){location.href=data.url;return}setMsg('A gestão da assinatura não retornou um endereço válido.');setMsgTone('error');setBusy(false)}
 if(loading)return <div className="vl-plans-app"><main className="page section"><div className="plan-message">Carregando planos e assinatura…</div></main></div>
 return <div className="vl-plans-app"><main className="page section">
  <div className="plans-heading"><div className="plans-back"><a className="back-link" href={businessId?`/conta?business_id=${encodeURIComponent(businessId)}`:'/laguna'}>← {businessId?'Voltar para minha conta':'Voltar para Laguna'}</a></div><span className="section-kicker">{onboarding?'CONFIGURAÇÃO COMERCIAL':'PLANOS'}</span><h1>Escolha o plano ideal para o seu negócio</h1><p>{onboarding?'Sua empresa foi cadastrada. Agora escolha como deseja começar.':'Mais recursos, mais destaque e mais espaço para sua empresa crescer.'}</p></div>
  {onboarding&&<div className="billing-onboarding"><div className="done"><b>1</b><span>Empresa cadastrada</span></div><i/><div className="active"><b>2</b><span>Escolha seu plano</span></div><i/><div><b>3</b><span>Ative e acompanhe</span></div></div>}
  {businesses.length>0&&<div className="billing-bar"><label>Empresa<select value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}{b.status==='pending'?' · em análise':''}</option>)}</select></label><div className="billing-toggle"><button type="button" className={interval==='monthly'?'active':''} onClick={()=>setIntervalValue('monthly')}>Mensal</button><button type="button" className={interval==='yearly'?'active':''} onClick={()=>setIntervalValue('yearly')}>Anual</button></div>{current?.provider_subscription_id&&<button type="button" className="outline billing-manage" onClick={portal} disabled={busy}>Gerenciar assinatura</button>}</div>}
  {current&&<div className={`billing-current ${current.cancel_at_period_end?'warning':''}`}><div><span>ASSINATURA ATUAL</span><strong>{currentPlan?.name||'Plano ativo'}</strong><small>{current.provider==='manual'?'Concedida pelo administrador':statusCopy[current.status]||current.status}{current.cancel_at_period_end?' · cancelamento agendado':''}</small></div><div><b>{current.provider==='manual'?'Plano manual':effectiveInterval==='yearly'?'Cobrança anual':'Cobrança mensal'}</b><span>{current.current_period_end?'Próximo ciclo: '+dateTime(current.current_period_end):'Sem cobrança recorrente'}</span></div></div>}
  {scheduledPlan&&<div className="billing-scheduled">Troca programada: <strong>{scheduledPlan.name}</strong> · aplicação em <strong>{dateTime(current.scheduled_change_at)}</strong>. O plano atual permanece válido até essa data.</div>}
  {current&&['past_due','unpaid','incomplete','pending'].includes(current.status)&&<div className="billing-alert error">Sua assinatura precisa de atenção. Use <strong>Gerenciar assinatura</strong> para concluir ou regularizar o pagamento antes de trocar de plano.</div>}
  {msg&&<div className={`plan-message ${msgTone}`}>{msg}</div>}
  <div className="plans-grid">{plans.map(p=>{const price=interval==='yearly'?p.price_yearly:p.price_monthly,isCurrent=currentCode===p.code,features=featureList(p.features);let button='Assinar '+p.name;if(!current&&p.code==='free')button='Começar grátis';else if(isCurrent){if(current?.cancel_at_period_end&&p.code===currentCode)button='Reativar plano';else button='Plano atual'}else if(current){button=rank[p.code]>rank[currentCode]?'Fazer upgrade':'Mudar para '+p.name}return <article className={`plan-card ${p.code==='premium'?'featured':''} ${isCurrent?'current':''}`} key={p.id}><span className="section-kicker">{p.code==='premium'?'MAIS COMPLETO':p.code==='pro'?'RECOMENDADO':'COMECE AQUI'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="plan-price">{money(price)}<small>/{interval==='yearly'?'ano':'mês'}</small></div>{interval==='yearly'&&annualSaving[p.code]>0&&<span className="billing-saving">Economize {annualSaving[p.code]}%</span>}<ul>{features.map(item=><li key={item}>{item}</li>)}</ul><button type="button" className={isCurrent?'outline':'primary'} disabled={busy||(isCurrent&&!current?.cancel_at_period_end)||(Boolean(current&&!changingAllowed&&!isCurrent))} onClick={()=>current?changePlan(p):checkout(p)}>{button}</button></article>})}</div>
  {session&&businessId&&<div className="billing-after-grid"><div><strong>Controle da sua assinatura</strong><span>Alterações de plano e ciclo são sincronizadas com o provedor de pagamento.</span></div><a href={`/conta?business_id=${encodeURIComponent(businessId)}`}>Abrir minha conta →</a><a href={`/conta/analytics?business_id=${encodeURIComponent(businessId)}`}>Ver desempenho →</a></div>}
 </main></div>
}
