import React,{useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import './billing-plans.css'
const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const FALLBACK=[{id:'free',code:'free',name:'Grátis',price_monthly:0,price_yearly:0,description:'Presença básica no catálogo',features:{photos_limit:5,items_limit:10,promotions_limit:1}},{id:'pro',code:'pro',name:'Pro',price_monthly:29.9,price_yearly:299,description:'Mais recursos para crescer',features:{photos_limit:30,items_limit:50,promotions_limit:5}},{id:'premium',code:'premium',name:'Premium',price_monthly:59.9,price_yearly:599,description:'Máxima visibilidade e recursos',features:{photos_limit:100,items_limit:200,promotions_limit:20}}]
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function BillingPlansPage(){const [plans,setPlans]=useState(FALLBACK),[session,setSession]=useState(null),[businesses,setBusinesses]=useState([]),[businessId,setBusinessId]=useState(''),[interval,setIntervalValue]=useState('monthly'),[current,setCurrent]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{let live=true;(async()=>{if(!db)return;const [{data:{session:s}},{data:p}]=await Promise.all([db.auth.getSession(),db.from('plans').select('id,code,name,price_monthly,price_yearly,description,features').eq('active',true).order('sort_order')]);if(!live)return;setSession(s);if(p?.length)setPlans(p);if(s){const [{data:b},{data:subs}]=await Promise.all([db.from('businesses').select('id,name,status').eq('owner_id',s.user.id).order('created_at',{ascending:false}),db.from('subscriptions').select('id,business_id,status,provider,provider_subscription_id,current_period_end,ends_at,cancel_at_period_end,plans(code,name)').eq('user_id',s.user.id).eq('status','active').order('created_at',{ascending:false})]);if(b?.length){setBusinesses(b);setBusinessId(b[0].id)}setCurrent(subs?.[0]||null)}})();return()=>{live=false}},[])
 async function checkout(p){if(p.code==='free')return setMsg('O plano Grátis já está disponível sem pagamento.');if(!session)return location.href=`/login?next=${encodeURIComponent('/planos')}`;if(!businessId)return setMsg('Cadastre uma empresa antes de contratar um plano pago.');setBusy(true);setMsg('');const {data,error}=await db.functions.invoke('create-checkout-session',{body:{business_id:businessId,plan_code:p.code,interval}});if(error){setMsg(error.message||'Falha ao iniciar o pagamento.');setBusy(false);return}if(data?.url){location.href=data.url;return}setMsg('Checkout não retornou uma URL.');setBusy(false)}
 async function portal(){if(!current?.provider_subscription_id)return setMsg('Nenhuma assinatura Stripe ativa encontrada.');setBusy(true);const {data,error}=await db.functions.invoke('billing-portal',{body:{business_id:current.business_id}});if(error)setMsg(error.message||'Falha ao abrir o portal.');else if(data?.url)location.href=data.url;else setMsg('Portal não retornou uma URL.');setBusy(false)}
 return <div className="vl-plans-app"><header className="topbar"><div className="nav"><a className="brand" href="/laguna"><span className="brand-mark">V</span><span>Vitrine<span className="brand-accent">Local</span></span></a><div className="nav-spacer"/><nav className="nav-actions">{session?<a href="/conta">Minha conta</a>:<a className="primary" href="/login?next=%2Fplanos">Entrar</a>}</nav></div></header><main className="page section"><div className="plans-heading"><span className="section-kicker">PLANOS</span><h1>Escolha o plano ideal para o seu negócio</h1><p>Comece gratuitamente e evolua conforme sua empresa cresce.</p></div>{businesses.length>0&&<div className="billing-bar"><label>Empresa<select value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="billing-toggle"><button className={interval==='monthly'?'active':''} onClick={()=>setIntervalValue('monthly')}>Mensal</button><button className={interval==='yearly'?'active':''} onClick={()=>setIntervalValue('yearly')}>Anual</button></div>{current&&<button className="outline" onClick={portal} disabled={busy}>Gerenciar assinatura</button>}</div>}{msg&&<div className="plan-message">{msg}</div>}<div className="plans-grid">{plans.map(p=>{const price=interval==='yearly'?p.price_yearly:p.price_monthly;const isCurrent=current?.plans?.code===p.code;return <article className={`plan-card ${p.code==='premium'?'featured':''}`} key={p.id}><span className="section-kicker">{p.code==='premium'?'MAIS COMPLETO':p.code==='pro'?'RECOMENDADO':'COMECE AQUI'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="plan-price">{money(price)}<small>/{interval==='yearly'?'ano':'mês'}</small></div><ul><li>{p.features?.photos_limit??0} fotos/mídias</li><li>{p.features?.items_limit??0} produtos/serviços</li><li>{p.features?.promotions_limit??0} promoções</li></ul><button className={isCurrent?'outline':'primary'} disabled={busy||isCurrent} onClick={()=>checkout(p)}>{isCurrent?'Plano atual':p.code==='free'?'Grátis':`Assinar ${p.name}`}</button></article>})}</div></main></div>}
