import React,{useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import {DEFAULT_PROMOTION_IMAGE,getActiveCityPromotions,projectTodayISO} from './promotion-service.js'
import './city-home.css'
import './premium-banner-carousel.css'
import './home-v2.css'
import './home-v2-fixes.css'
import './home-content-layout.css'

const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const FALLBACK={id:'fallback',name:'Laguna',state:'SC',slug:'laguna',active:true}
const FALLBACK_CATS=[['Restaurantes','🍽️'],['Lojas','🛍️'],['Serviços','🧰'],['Saúde','❤️'],['Beleza','✨'],['Turismo','📍'],['Automóveis','🚗'],['Imóveis','🏠'],['Pets','🐾'],['Outros','✦']]
const fallbackCategories=()=>FALLBACK_CATS.map(([name,icon],i)=>({id:`fallback-${i}`,name,icon,slug:name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}))
const money=v=>v==null||v===''?'':`R$ ${Number(v).toFixed(2).replace('.',',')}`
const timeout=(promise,ms=7000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Tempo limite de carregamento excedido.')),ms))])

export default function CityHomePageResilient2({citySlug='laguna'}){
 const [city,setCity]=useState(citySlug==='laguna'?FALLBACK:{...FALLBACK,slug:citySlug,name:citySlug})
 const [categories,setCategories]=useState(fallbackCategories)
 const [businesses,setBusinesses]=useState([]),[promotions,setPromotions]=useState([]),[events,setEvents]=useState([]),[banners,setBanners]=useState([])
 const [bannerIndex,setBannerIndex]=useState(0),[q,setQ]=useState('')
 const [eventsLoading,setEventsLoading]=useState(true),[eventsError,setEventsError]=useState(''),[promoError,setPromoError]=useState('')
 const base=`/${city?.slug||citySlug}`

 useEffect(()=>{if(!db){setEventsLoading(false);setEventsError('Não foi possível carregar os eventos.');return}let alive=true;(async()=>{try{const r=await timeout(db.from('cities').select('id,name,state,country,slug,active').eq('active',true).eq('slug',citySlug).maybeSingle());if(!alive)return;if(r.data)setCity(r.data);else{setEventsLoading(false);setEventsError('Não foi possível localizar a cidade para carregar os eventos.')}}catch(error){if(alive){setEventsLoading(false);setEventsError(error?.message||'Não foi possível carregar os eventos.')}}})();return()=>{alive=false}},[citySlug])

 useEffect(()=>{if(!db||!city?.id||city.id==='fallback')return;let alive=true
  const categoriesLoad=async()=>{try{const r=await timeout(db.from('categories').select('id,name,slug,icon').eq('active',true).order('sort_order').order('name'));if(alive&&r.data?.length)setCategories(r.data)}catch(_){}}
  const businessesLoad=async()=>{try{const r=await timeout(db.from('public_business_directory').select('id,name,slug,short_description,cover_url,address,featured,verified,category_name,created_at').eq('city_id',city.id).order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(8));if(alive)setBusinesses((r.data||[]).map(x=>({...x,categories:x.category_name?{name:x.category_name}:null})))}catch(_){}}
  const promotionsLoad=async()=>{try{const r=await timeout(getActiveCityPromotions(db,city.id,{limit:100}));if(!alive)return;if(r.error){setPromotions([]);setPromoError(r.error.message||'Não foi possível carregar as promoções.')}else setPromotions(r.data||[])}catch(error){if(alive){setPromotions([]);setPromoError(error?.message||'Não foi possível carregar as promoções.')}}}
  const eventsLoad=async()=>{setEventsLoading(true);setEventsError('');try{const r=await timeout(db.from('events').select('id,title,description,image_url,event_date,start_time,location,featured').eq('city_id',city.id).eq('active',true).gte('event_date',projectTodayISO()).order('featured',{ascending:false}).order('event_date').order('start_time').limit(4));if(!alive)return;if(r.error){setEvents([]);setEventsError(r.error.message||'Não foi possível carregar os eventos.')}else setEvents(r.data||[])}catch(error){if(alive){setEvents([]);setEventsError(error?.message||'Não foi possível carregar os eventos.')}}finally{if(alive)setEventsLoading(false)}}
  const bannersLoad=async()=>{try{const r=await timeout(db.from('advertisements').select('id,title,description,image_url,target_url,priority,starts_at,ends_at').eq('city_id',city.id).eq('placement','home_banner').eq('active',true).order('priority',{ascending:false}).order('created_at',{ascending:false}).limit(20));if(!alive)return;const now=Date.now();setBanners((r.data||[]).filter(x=>(!x.starts_at||new Date(x.starts_at).getTime()<=now)&&(!x.ends_at||new Date(x.ends_at).getTime()>=now)));setBannerIndex(0)}catch(_){if(alive)setBanners([])}}
  categoriesLoad();businessesLoad();promotionsLoad();eventsLoad();bannersLoad();return()=>{alive=false}},[city?.id])

 useEffect(()=>{if(banners.length<2)return;const t=setInterval(()=>setBannerIndex(i=>(i+1)%banners.length),6000);return()=>clearInterval(t)},[banners.length])
 useEffect(()=>{if(bannerIndex>=banners.length&&banners.length)setBannerIndex(0)},[bannerIndex,banners.length])

 const filtered=businesses.filter(b=>{const s=q.trim().toLowerCase();return !s||[b.name,b.short_description,b.address,b.categories?.name].filter(Boolean).join(' ').toLowerCase().includes(s)})
 const featured=filtered.filter(b=>b.featured===true).slice(0,4)
 const banner=banners[bannerIndex]||null
 const categoryHref=c=>`${base}/empresas?categoria=${encodeURIComponent(c.slug)}`

 return <div className="home-v2 vl-public-app">
  <section className="home-hero hero"><div className="home-hero-inner"><div className="hero-copy"><span className="hero-kicker">✦ A cidade na palma da mão</span><h1>Descubra o que <span>{city?.name||'sua cidade'}</span> tem de melhor.</h1><p>Encontre empresas, serviços, promoções e eventos perto de você — tudo em um só lugar.</p><div className="hero-search searchbox"><span className="hero-search-icon">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="O que você procura hoje?" aria-label="O que você procura hoje"/><button onClick={()=>location.href=`${base}/empresas${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`}>Buscar</button></div><div className="hero-buttons"><a href={`${base}/empresas`}>Explorar empresas →</a><a href="/conta?new=business">Cadastre sua empresa <span>→</span></a></div><div className="hero-note">● Catálogo local de {city?.name||'sua cidade'} · atualizado por negócios locais.</div></div><aside className="hero-panel"><div className="hero-panel-top"><span>• O QUE ESTÁ ROLANDO</span><span>{city?.name||'—'}</span></div><div className="hero-stat"><div className="hero-stat-icon">📣</div><div><strong>{promotions.length} promoções</strong><small>Ofertas publicadas por empresas locais</small></div></div><div className="hero-stat"><div className="hero-stat-icon">📅</div><div><strong>{events.length} eventos próximos</strong><small>Veja o que acontece na cidade</small></div></div><a className="hero-panel-action" href={`${base}/eventos`}>Ver agenda →</a></aside></div></section>
  <div className="home-wrap">
   <nav className="category-dock vl-category-slot" aria-label="Categorias"><div className="category-grid">{categories.map(c=><a className="category-card" key={c.id} href={categoryHref(c)}><span className="category-icon">{c.icon||'✦'}</span><strong>{c.name}</strong></a>)}</div></nav>
   <section className="home-section">{banner?<div className="ad-card"><a className="ad-media" href={banner.target_url||'#'} target={banner.target_url?'_blank':undefined} rel="noreferrer"><img src={banner.image_url||'/laguna-hero.svg'} alt={banner.title||'Banner patrocinado'}/></a><div className="ad-content"><span className="eyebrow">ESPAÇO PUBLICITÁRIO · PREMIUM</span><h2>{banner.title}</h2><p>{banner.description||'Sua marca em destaque na VitrineLocal.'}</p><a href={banner.target_url||'#'} target={banner.target_url?'_blank':undefined} rel="noreferrer">Conhecer anúncio →</a></div></div>:<div className="empty-v2"><h3>Espaço publicitário premium</h3><p>Este espaço é reservado para empresas que desejam colocar sua marca em destaque na página inicial.</p></div>}</section>
   {featured.length>0&&<section className="home-section"><div className="section-heading"><div><span className="eyebrow">NEGÓCIOS LOCAIS</span><h2>Empresas em destaque</h2><p>Conheça negócios selecionados que fazem parte da VitrineLocal.</p></div><a href={`${base}/empresas`}>Ver todas →</a></div><div className={`business-grid business-grid-${featured.length}`}>{featured.map(b=><a className="business-card-v2" key={b.id} href={`${base}/empresa/${encodeURIComponent(b.slug)}`}><div className="business-image">{b.cover_url?<img src={b.cover_url} alt="" loading="lazy"/>:<div className="cover-placeholder">V</div>}</div><div className="business-info"><div className="business-meta">{b.verified&&<span className="verified">✓ Verificada</span>}<span className="category">{b.categories?.name||'Empresa local'}</span></div><h3>{b.name}</h3><p>{b.short_description||'Conheça este negócio local.'}</p>{b.address&&<small>📍 {b.address}</small>}</div></a>)}</div></section>}
  </div>
  {promotions.length>0&&<section className="soft-section promo-section"><div className="home-wrap"><div className="section-heading"><div><span className="eyebrow">OFERTAS</span><h2>Promoções em {city?.name||'sua cidade'}</h2><p>Descubra oportunidades e ofertas de empresas locais.</p></div><a href={`${base}/promocoes`}>Ver todas →</a></div>{promoError&&<div className="empty-v2"><h3>Não foi possível carregar todas as promoções.</h3><p>{promoError}</p></div>}<div className="promotion-grid promotion-grid-3">{promotions.slice(0,3).map(p=><a className="content-card-v2" key={p.id} href={`${base}/empresa/${encodeURIComponent(p.businesses?.slug||'')}`}><div className="content-card-media"><img src={p.image_url||DEFAULT_PROMOTION_IMAGE} alt={p.title} loading="lazy"/></div><div className="content-card-body"><span className="tag">PROMOÇÃO</span><h3>{p.title}</h3><p>{p.description||'Confira esta oferta.'}</p><p><strong>{p.businesses?.name}</strong></p><div className="price-row">{p.original_price!=null&&<del>{money(p.original_price)}</del>}{p.price!=null&&<strong>{money(p.price)}</strong>}</div></div></a>)}</div></div></section>}
  {promotions.length===0&&promoError&&<section className="soft-section promo-section"><div className="home-wrap"><div className="empty-v2"><h3>Não foi possível carregar as promoções.</h3><p>{promoError}</p></div></div></section>}
  <div className="home-wrap"><section className="home-section"><div className="section-heading"><div><span className="eyebrow">AGENDA</span><h2>Próximos eventos</h2><p>O que está acontecendo e o que vem por aí na cidade.</p></div><a href={`${base}/eventos`}>Ver agenda →</a></div>{eventsLoading?<div className="empty-v2"><h3>Carregando eventos…</h3></div>:eventsError?<div className="empty-v2"><h3>Não foi possível carregar os eventos.</h3><p>{eventsError}</p><a href={`${base}/eventos`}>Abrir agenda →</a></div>:events.length?<div className={`event-grid event-grid-${Math.min(events.length,3)}`}>{events.slice(0,3).map(e=><a className="content-card-v2" key={e.id} href={`${base}/eventos`}>{e.image_url&&<img src={e.image_url} alt="" loading="lazy"/>}<div className="content-card-body"><span className="tag">{new Date(`${e.event_date}T00:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span><h3>{e.title}</h3><p>{e.location||'Local a confirmar'}{e.start_time?` · ${String(e.start_time).slice(0,5)}`:''}</p></div></a>)}</div>:<div className="empty-v2"><h3>Nenhum evento próximo.</h3><p>Quando novos eventos forem cadastrados, eles aparecerão aqui.</p></div>}</section><section className="home-section"><div className="commercial"><div className="commercial-copy"><span className="eyebrow">PARA EMPRESAS</span><h2>Coloque sua empresa na vitrine da cidade.</h2><p>Crie seu perfil, publique promoções, acompanhe o desempenho e apareça para quem está procurando negócios locais.</p></div><div className="commercial-actions"><a href="/conta?new=business">Cadastrar empresa</a><a href="/planos">Conhecer planos</a></div></div></section></div>
 </div>
