import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import{hasPlanFeature}from'./phase2-rules.js'
import'./commercial-analytics.css'

const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const fmt=v=>Number(v||0).toLocaleString('pt-BR')
const pct=(v,d)=>d?((v/d)*100).toFixed(1):'0.0'
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeZone:'America/Sao_Paulo'}).format(new Date(v)):'—'

export default function CommercialAnalyticsPage(){
 const[s,setS]=useState({loading:true,session:null,businesses:[],businessId:'',plan:null,summary:null,error:''}),[range,setRange]=useState(30)
 useEffect(()=>{let live=true;(async()=>{if(!db){setS(x=>({...x,loading:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setS(x=>({...x,loading:false}));return}const{data:businesses,error}=await db.from('businesses').select('id,name,status').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(!live)return;if(error){setS({loading:false,session,businesses:[],businessId:'',plan:null,summary:null,error:error.message});return}setS(x=>({...x,loading:false,session,businesses:businesses||[],businessId:businesses?.[0]?.id||'',error:''}))})();return()=>{live=false}},[])
 useEffect(()=>{let live=true;(async()=>{if(!db||!s.session||!s.businessId)return;setS(x=>({...x,plan:null,summary:null,error:''}));const[{data:planId,error:pe},{data:biz,error:be}]=await Promise.all([db.rpc('get_effective_plan_id',{p_business_id:s.businessId}),db.from('businesses').select('id,name,status').eq('id',s.businessId).eq('owner_id',s.session.user.id).maybeSingle()]);if(!live)return;if(pe||be||!biz){setS(x=>({...x,error:(pe||be)?.message||'Não foi possível validar a empresa.'}));return}const{data:plan,error:ple}=await db.from('plans').select('id,code,name,features').eq('id',planId).maybeSingle();if(!live)return;if(ple||!plan){setS(x=>({...x,error:ple?.message||'Plano não encontrado.'}));return}if(!hasPlanFeature(plan.features,'analytics',false)){setS(x=>({...x,plan,biz,error:''}));return}const{data:summary,error:se}=await db.rpc('get_business_analytics_summary',{p_business_id:s.businessId,p_days:range});if(!live)return;if(se){setS(x=>({...x,plan,biz,error:se.message||'Não foi possível carregar as métricas.'}));return}setS(x=>({...x,plan,biz,summary:summary?.[0]||null,error:''}))})();return()=>{live=false}},[s.session?.user?.id,s.businessId,range])
 const m=s.summary||{};const leadCount=(m.whatsapp_clicks||0)+(m.instagram_clicks||0)+(m.website_clicks||0);const conversion=m.profile_views?((leadCount/m.profile_views)*100).toFixed(1):'0.0';const previous=m.previous_profile_views||0;const delta=previous?(((m.profile_views||0-previous)/previous)*100).toFixed(1):null
 if(s.loading)return <div className="commercial-analytics-page"><div className="ca-empty">Carregando desempenho comercial…</div></div>
 if(!s.session)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Acompanhe o desempenho da sua empresa</h1><a href="/login?next=%2Fconta%2Fanalytics">Entrar</a></div></div>
 if(!s.businesses.length)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Nenhuma empresa cadastrada</h1><a href="/conta?new=business">Cadastrar empresa</a></div></div>
 if(s.error)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Não foi possível carregar o desempenho</h1><p>{s.error}</p><a href="/conta">Voltar para minha conta</a></div></div>
 if(s.plan&&!hasPlanFeature(s.plan.features,'analytics',false))return <main className="commercial-analytics-page"><div className="ca-shell"><div className="ca-locked"><span>PLANO {s.plan.name?.toUpperCase()||'GRÁTIS'}</span><h1>Transforme visitas em oportunidades</h1><p>Veja quem encontrou sua empresa, quais canais geram contatos e como suas ações estão performando.</p><a href={`/planos?business_id=${encodeURIComponent(s.businessId)}`}>Fazer upgrade para Pro →</a></div></div></main>
 const business=s.businesses.find(x=>x.id===s.businessId)||s.businesses[0]
 const funnel=[['Visualizações',m.profile_views||0],['WhatsApp',m.whatsapp_clicks||0],['Instagram',m.instagram_clicks||0],['Site',m.website_clicks||0]]
 return <main className="commercial-analytics-page"><div className="ca-shell">
  <header className="ca-head"><div><span>DESEMPENHO COMERCIAL</span><h1>Analytics da empresa</h1><p>{business?.name||'Empresa'} · decisões baseadas em comportamento real.</p></div><div className="ca-actions"><a href="/conta">← Minha conta</a><select value={s.businessId} onChange={e=>setS(x=>({...x,businessId:e.target.value}))}>{s.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={range} onChange={e=>setRange(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></div></header>
  <section className="ca-kpis"><K title="Visualizações" value={fmt(m.profile_views)} note={`${range} dias${delta?` · ${delta}% vs. período anterior`:''}`} /><K title="Contatos" value={fmt(leadCount)} note="WhatsApp + Instagram + site" tone="green"/><K title="Conversão" value={`${conversion}%`} note="visita → contato" tone="purple"/><K title="Interações" value={fmt(m.total_interactions)} note="ações registradas" tone="amber"/></section>
  <section className="ca-grid"><article className="ca-card"><div className="ca-card-head"><div><span>FUNIL</span><h2>De visita a contato</h2><p>Onde o interesse acontece no seu perfil.</p></div></div><div className="ca-funnel">{funnel.map(([label,value],i)=>{const max=Math.max(1,m.profile_views||1);return <div className="ca-funnel-row" key={label}><div><strong>{label}</strong><small>{fmt(value)}</small></div><div className="ca-track"><i style={{width:`${Math.max(3,value/max*100)}%`}}/></div><b>{pct(value,m.profile_views||0)}%</b></div>})}</div></article><article className="ca-card"><div className="ca-card-head"><div><span>PUBLICIDADE</span><h2>Banners Premium</h2><p>Resultado de exposição patrocinada.</p></div></div><div className="ca-ad-metrics"><Metric label="Impressões" value={fmt(m.banner_impressions)}/><Metric label="Cliques" value={fmt(m.banner_clicks)}/><Metric label="CTR" value={`${pct(m.banner_clicks,m.banner_impressions)}%`}/></div><a className="ca-ad-link" href="/conta/publicidade">Gerenciar publicidade →</a></article></section>
  <section className="ca-card"><div className="ca-card-head"><div><span>OPORTUNIDADES</span><h2>Como transformar tráfego em vendas</h2><p>Use os sinais do seu perfil para priorizar as próximas ações.</p></div></div><div className="ca-opportunities"><div><b>WhatsApp</b><strong>{fmt(m.whatsapp_clicks)}</strong><small>{m.whatsapp_clicks?'Seu principal canal de contato já está gerando interesse.':'Facilite o contato adicionando ou destacando um número de WhatsApp.'}</small></div><div><b>Promoções</b><strong>{fmt(m.promotion_clicks)}</strong><small>{m.promotion_clicks?'Suas ofertas já estão sendo acionadas.':'Publique ofertas relevantes para criar um próximo passo claro.'}</small></div><div><b>Eventos</b><strong>{fmt(m.event_clicks)}</strong><small>{m.event_clicks?'Seu público está interagindo com a agenda.':'Use eventos para criar recorrência e trazer pessoas de volta.'}</small></div></div></section>
 </div></main>
}
function K({title,value,note,tone=''}){return <div className={`ca-kpi ${tone}`}><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
function Metric({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
