import React,{useEffect,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import{hasPlanFeature}from'./phase2-rules.js'
import{chooseBusiness,getRequestedBusinessId,persistBusinessId}from'./business-selection.js'
import'./commercial-analytics.css'

const U=import.meta.env.VITE_SUPABASE_URL,SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&SUPABASE_KEY?createClient(U,SUPABASE_KEY):null
const fmt=v=>Number(v||0).toLocaleString('pt-BR')
const pct=(v,d)=>d?((v/d)*100).toFixed(1):'0.0'

export default function CommercialAnalyticsPage(){
 const[s,setS]=useState({loading:true,session:null,businesses:[],businessId:'',plan:null,summary:null,advanced:null,advancedError:'',error:''}),[range,setRange]=useState(30)
 useEffect(()=>{let live=true;(async()=>{if(!db){setS(x=>({...x,loading:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setS(x=>({...x,loading:false}));return}const{data:businesses,error}=await db.from('businesses').select('id,name,status').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(!live)return;if(error){setS(x=>({...x,loading:false,session,businesses:[],businessId:'',plan:null,summary:null,advanced:null,error:error.message}));return}const selected=chooseBusiness(businesses,getRequestedBusinessId());persistBusinessId(selected?.id);setS(x=>({...x,loading:false,session,businesses:businesses||[],businessId:selected?.id||'',error:'',advanced:null,advancedError:''}))})();return()=>{live=false}},[])
 useEffect(()=>{let live=true;(async()=>{if(!db||!s.session||!s.businessId)return;setS(x=>({...x,plan:null,summary:null,advanced:null,advancedError:'',error:''}));const[{data:planId,error:pe},{data:biz,error:be}]=await Promise.all([db.rpc('get_effective_plan_id',{p_business_id:s.businessId}),db.from('businesses').select('id,name,status').eq('id',s.businessId).eq('owner_id',s.session.user.id).maybeSingle()]);if(!live)return;if(pe||be||!biz){setS(x=>({...x,error:(pe||be)?.message||'Não foi possível validar a empresa.'}));return}const{data:plan,error:ple}=await db.from('plans').select('id,code,name,features').eq('id',planId).maybeSingle();if(!live)return;if(ple||!plan){setS(x=>({...x,error:ple?.message||'Plano não encontrado.'}));return}if(!hasPlanFeature(plan.features,'analytics',false)){setS(x=>({...x,plan,biz,error:''}));return}const advancedEnabled=hasPlanFeature(plan.features,'advanced_analytics',false);const[{data:summary,error:se},{data:advanced,error:ae}]=await Promise.all([db.rpc('get_business_analytics_summary',{p_business_id:s.businessId,p_days:range}),advancedEnabled?db.rpc('get_business_advanced_analytics',{p_business_id:s.businessId,p_days:range}):Promise.resolve({data:null,error:null})]);if(!live)return;if(se){setS(x=>({...x,plan,biz,error:se.message||'Não foi possível carregar as métricas.'}));return}setS(x=>({...x,plan,biz,summary:summary?.[0]||null,advanced:advanced?.[0]||null,advancedError:advancedEnabled?(ae?.message||''):'',error:''}))})();return()=>{live=false}},[s.session?.user?.id,s.businessId,range])
 const m=s.summary||{},a=s.advanced||{};const leadCount=(m.whatsapp_clicks||0)+(m.instagram_clicks||0)+(m.website_clicks||0);const conversion=m.profile_views?((leadCount/m.profile_views)*100).toFixed(1):'0.0';const previous=Number(m.previous_profile_views||0);const currentViews=Number(m.profile_views||0);const delta=previous?(((currentViews-previous)/previous)*100).toFixed(1):null;const previousAdvanced=Number(a.previous_profile_views||0);const advancedDelta=previousAdvanced?(((Number(a.profile_views||0)-previousAdvanced)/previousAdvanced)*100).toFixed(1):null;const daily=Array.isArray(a.daily)?a.daily:[];const maxDaily=Math.max(1,...daily.map(x=>Number(x?.profile_views||0)));const channelEntries=[['WhatsApp',a.channels?.whatsapp||0],['Instagram',a.channels?.instagram||0],['Site',a.channels?.website||0]]
 if(s.loading)return <div className="commercial-analytics-page"><div className="ca-empty">Carregando desempenho comercial…</div></div>
 if(!s.session)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Acompanhe o desempenho da sua empresa</h1><a href="/login?next=%2Fconta%2Fanalytics">Entrar</a></div></div>
 if(!s.businesses.length)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Nenhuma empresa cadastrada</h1><a href="/conta?new=business">Cadastrar empresa</a></div></div>
 if(s.error)return <div className="commercial-analytics-page"><div className="ca-empty"><h1>Não foi possível carregar o desempenho</h1><p>{s.error}</p><a href="/conta">Voltar para minha conta</a></div></div>
 if(s.plan&&!hasPlanFeature(s.plan.features,'analytics',false))return <main className="commercial-analytics-page"><div className="ca-shell"><div className="ca-locked"><span>PLANO {s.plan.name?.toUpperCase()||'GRÁTIS'}</span><h1>Transforme visitas em oportunidades</h1><p>Veja quem encontrou sua empresa, quais canais geram contatos e como suas ações estão performando.</p><a href={`/planos?business_id=${encodeURIComponent(s.businessId)}`}>Fazer upgrade para Pro →</a></div></div></main>
 const business=s.businesses.find(x=>x.id===s.businessId)||s.businesses[0],funnel=[['Visualizações',m.profile_views||0],['WhatsApp',m.whatsapp_clicks||0],['Instagram',m.instagram_clicks||0],['Site',m.website_clicks||0]]
 return <main className="commercial-analytics-page"><div className="ca-shell">
  <header className="ca-head"><div><span>DESEMPENHO COMERCIAL</span><h1>Analytics da empresa</h1><p>{business?.name||'Empresa'} · decisões baseadas em comportamento real.</p></div><div className="ca-actions"><a href="/conta">← Minha conta</a><select value={s.businessId} onChange={e=>{persistBusinessId(e.target.value);setS(x=>({...x,businessId:e.target.value}))}} aria-label="Empresa analisada">{s.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={range} onChange={e=>setRange(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></div></header>
  <section className="ca-kpis"><Kpi title="Visualizações" value={fmt(m.profile_views)} note={`${range} dias${delta?` · ${delta}% vs. período anterior`:''}`} /><Kpi title="Contatos" value={fmt(leadCount)} note="WhatsApp + Instagram + site" tone="green"/><Kpi title="Conversão" value={`${conversion}%`} note="visita → contato" tone="purple"/><Kpi title="Interações" value={fmt(m.total_interactions)} note="ações registradas" tone="amber"/></section>
  <section className="ca-grid"><article className="ca-card"><div className="ca-card-head"><div><span>FUNIL</span><h2>De visita a contato</h2><p>Onde o interesse acontece no seu perfil.</p></div></div><div className="ca-funnel">{funnel.map(([label,value])=>{const max=Math.max(1,m.profile_views||1);return <div className="ca-funnel-row" key={label}><div><strong>{label}</strong><small>{fmt(value)}</small></div><div className="ca-track"><i style={{width:`${Math.max(3,value/max*100)}%`}}/></div><b>{pct(value,m.profile_views||0)}%</b></div>})}</div></article><article className="ca-card"><div className="ca-card-head"><div><span>PUBLICIDADE</span><h2>Banners Premium</h2><p>Resultado de exposição patrocinada.</p></div></div><div className="ca-ad-metrics"><Metric label="Impressões" value={fmt(m.banner_impressions)}/><Metric label="Cliques" value={fmt(m.banner_clicks)}/><Metric label="CTR" value={`${pct(m.banner_clicks,m.banner_impressions)}%`}/></div><a className="ca-ad-link" href={`/conta/publicidade?business_id=${encodeURIComponent(s.businessId)}`}>Gerenciar publicidade →</a></article></section>
  <section className="ca-card ca-advanced-card"><div className="ca-card-head"><div><span>ESTATÍSTICAS AVANÇADAS</span><h2>Leitura avançada do desempenho</h2><p>Aprofunde os dados com visitantes únicos, tendências diárias, canais de contato e comparação de períodos.</p></div><strong className="ca-premium-badge">PREMIUM</strong></div>{hasPlanFeature(s.plan?.features,'advanced_analytics',false)?s.advanced?<><div className="ca-advanced-kpis"><Kpi title="Visitantes únicos" value={fmt(a.unique_visitors)} note={`${pct(a.unique_visitors,a.profile_views||0)}% das visualizações`} /><Kpi title="Engajamentos" value={fmt(a.engaged_interactions)} note="interações qualificadas" tone="green"/><Kpi title="Taxa de engajamento" value={`${Number(a.engagement_rate||0).toFixed(1)}%`} note="contato / visualização" tone="purple"/><Kpi title="Variação" value={advancedDelta?`${advancedDelta}%`:'—'} note="vs. período anterior" tone="amber"/></div><div className="ca-advanced-grid"><article className="ca-advanced-panel"><div className="ca-subhead"><h3>Tendência diária</h3><span>{range} dias</span></div><div className="ca-daily-chart" aria-label="Visualizações por dia">{daily.map(row=><div className="ca-day-bar" key={row.day} title={`${row.day}: ${fmt(row.profile_views)} visualizações`}><i style={{height:`${Math.max(6,(Number(row.profile_views||0)/maxDaily)*100)}%`}}/><small>{String(row.day||'').slice(8,10)}</small></div>)}</div><p className="ca-caption">Visualizações diárias do período atual. {advancedDelta?`No período anterior foram ${fmt(previousAdvanced)} visualizações.`:'Ainda não há período anterior suficiente para comparação.'}</p></article><article className="ca-advanced-panel"><div className="ca-subhead"><h3>Canais de contato</h3><span>{fmt(a.total_contacts)} contatos</span></div><div className="ca-channel-list">{channelEntries.map(([label,value])=><div key={label}><div><strong>{label}</strong><span>{fmt(value)}</span></div><div className="ca-channel-track"><i style={{width:`${Math.max(4,pct(Number(value),Number(a.total_contacts||0)))}%`}}/></div></div>)}</div></article></div></>:<div className="ca-advanced-loading">Carregando estatísticas avançadas…</div>:<div className="ca-advanced-locked"><span>EXCLUSIVO DO PREMIUM</span><h3>Estatísticas avançadas</h3><p>O Premium libera visitantes únicos, tendências diárias, canais de contato, engajamento e comparação com o período anterior.</p><a href={`/planos?business_id=${encodeURIComponent(s.businessId)}`}>Conhecer o Premium →</a></div>}{s.advancedError&&<p className="ca-advanced-error">{s.advancedError}</p>}</section>
  <section className="ca-card"><div className="ca-card-head"><div><span>OPORTUNIDADES</span><h2>Como transformar tráfego em vendas</h2><p>Use os sinais do seu perfil para priorizar as próximas ações.</p></div></div><div className="ca-opportunities"><div><b>WhatsApp</b><strong>{fmt(m.whatsapp_clicks)}</strong><small>{m.whatsapp_clicks?'Seu principal canal de contato já está gerando interesse.':'Facilite o contato adicionando ou destacando um número de WhatsApp.'}</small></div><div><b>Promoções</b><strong>{fmt(m.promotion_clicks)}</strong><small>{m.promotion_clicks?'Suas ofertas já estão sendo acionadas.':'Publique ofertas relevantes para criar um próximo passo claro.'}</small></div><div><b>Eventos</b><strong>{fmt(m.event_clicks)}</strong><small>{m.event_clicks?'Seu público está interagindo com a agenda.':'Use eventos para criar recorrência e trazer pessoas de volta.'}</small></div></div></section>
 </div></main>
}
function Kpi({title,value,note,tone=''}){return <div className={`ca-kpi ${tone}`}><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
function Metric({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
