import React,{useEffect,useMemo,useState}from'react'
import './cover-position-editor.css'
const DEFAULT={x:0,y:0,zoom:1,scaleX:1,scaleY:1}
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v))
export default function CoverPositionEditor({coverUrl,businessName='Empresa',desktopPosition,mobilePosition,onSave,onClose,saveLabel='Salvar enquadramento'}){
 const[mode,setMode]=useState('desktop'),[desktop,setDesktop]=useState({...DEFAULT,...(desktopPosition||{})}),[mobile,setMobile]=useState({...DEFAULT,...(mobilePosition||{})}),[drag,setDrag]=useState(null),[saving,setSaving]=useState(false),current=mode==='desktop'?desktop:mobile
 const setCurrent=p=>{const n={...current,...p};mode==='desktop'?setDesktop(n):setMobile(n)}
 useEffect(()=>{const k=e=>{if(e.key==='Escape'&&!saving)onClose?.()};document.addEventListener('keydown',k);return()=>document.removeEventListener('keydown',k)},[onClose,saving])
 const down=e=>{if(!coverUrl)return;e.currentTarget.setPointerCapture?.(e.pointerId);setDrag({x:e.clientX,y:e.clientY,startX:current.x,startY:current.y})}
 const move=e=>{if(!drag)return;setCurrent({x:clamp(drag.startX+e.clientX-drag.x,-400,400),y:clamp(drag.startY+e.clientY-drag.y,-260,260)})}
 const up=()=>setDrag(null),reset=()=>setCurrent(DEFAULT)
 const save=async()=>{if(!coverUrl||!onSave)return;setSaving(true);try{await onSave({desktop,mobile})}finally{setSaving(false)}}
 const transform=useMemo(()=> 'translate(calc(-50% + '+current.x+'px), calc(-50% + '+current.y+'px)) scale('+current.zoom+') scaleX('+current.scaleX+') scaleY('+current.scaleY+')',[current])
 return <div className="cover-editor-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose?.()}}><section className="cover-editor-modal" role="dialog" aria-modal="true" aria-label={'Ajustar capa de '+businessName}>
  <header className="cover-editor-header"><div><span className="cover-editor-kicker">AJUSTAR CAPA</span><h2>{businessName}</h2><p>Arraste, aumente ou estique a imagem até posicionar o conteúdo importante exatamente dentro da área visível.</p></div><button type="button" className="cover-editor-close" onClick={onClose} disabled={saving} aria-label="Fechar editor">×</button></header>
  <div className="cover-editor-tabs"><button type="button" className={mode==='desktop'?'active':''} onClick={()=>setMode('desktop')}>Desktop</button><button type="button" className={mode==='mobile'?'active':''} onClick={()=>setMode('mobile')}>Mobile</button></div>
  <div className={'cover-editor-workspace '+mode}><div className="cover-editor-stage-wrap"><div className="cover-editor-stage" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{coverUrl?<img src={coverUrl} alt="" draggable="false" style={{transform}}/>:<div className="cover-editor-empty">Nenhuma capa carregada.</div>}<div className="cover-editor-safe"><span>Área segura</span></div></div><small>Arraste a imagem. O posicionamento de desktop e mobile é independente.</small></div>
  <aside className="cover-editor-controls"><section><h3>Posição</h3><label>Horizontal <strong>{Math.round(current.x)} px</strong></label><input aria-label="Posição horizontal" type="range" min="-400" max="400" value={current.x} onChange={e=>setCurrent({x:Number(e.target.value)})}/><label>Vertical <strong>{Math.round(current.y)} px</strong></label><input aria-label="Posição vertical" type="range" min="-260" max="260" value={current.y} onChange={e=>setCurrent({y:Number(e.target.value)})}/></section>
  <section><h3>Zoom <strong>{current.zoom.toFixed(2)}×</strong></h3><input aria-label="Zoom da capa" type="range" min="0.6" max="1.8" step="0.01" value={current.zoom} onChange={e=>setCurrent({zoom:Number(e.target.value)})}/><div className="cover-editor-zoom-buttons"><button type="button" onClick={()=>setCurrent({zoom:clamp(current.zoom-.05,.6,1.8)})}>−</button><button type="button" onClick={()=>setCurrent({zoom:clamp(current.zoom+.05,.6,1.8)})}>+</button></div></section><section><h3>Alongar imagem <strong>{Math.round(current.scaleX*100)}% × {Math.round(current.scaleY*100)}%</strong></h3><label>Largura <strong>{Math.round(current.scaleX*100)}%</strong></label><input aria-label="Largura da capa" type="range" min="0.6" max="1.8" step="0.01" value={current.scaleX} onChange={e=>setCurrent({scaleX:Number(e.target.value)})}/><label>Altura <strong>{Math.round(current.scaleY*100)}%</strong></label><input aria-label="Altura da capa" type="range" min="0.6" max="1.8" step="0.01" value={current.scaleY} onChange={e=>setCurrent({scaleY:Number(e.target.value)})}/><button type="button" className="cover-editor-secondary" onClick={()=>setCurrent({scaleX:1,scaleY:1})}>↺ Voltar à proporção original</button></section><button type="button" className="cover-editor-reset" onClick={reset}>↺ Restaurar posição</button></aside></div>
  <footer className="cover-editor-footer"><button type="button" className="cover-editor-cancel" onClick={onClose} disabled={saving}>Cancelar</button><button type="button" className="cover-editor-save" onClick={save} disabled={saving||!coverUrl}>{saving?'Salvando…':saveLabel}</button></footer>
 </section></div>
}