import React,{useEffect,useMemo,useState}from'react'
import './cover-position-editor.css'
import{normalizeCoverPosition,DEFAULT_COVER_POSITION,COVER_FRAMES,COVER_MIN_WIDTHS,coverFitOf}from'./cover-position-utils.js'
const DEFAULT=DEFAULT_COVER_POSITION
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v))
export default function CoverPositionEditor({coverUrl,businessName='Empresa',desktopPosition,mobilePosition,onSave,onClose,saveLabel='Salvar enquadramento',frames=COVER_FRAMES.profile,minWidths=COVER_MIN_WIDTHS.profile,kind='cover'}){
 const[mode,setMode]=useState('desktop'),[desktop,setDesktop]=useState(()=>normalizeCoverPosition(desktopPosition,'desktop')),[mobile,setMobile]=useState(()=>normalizeCoverPosition(mobilePosition,'mobile')),[drag,setDrag]=useState(null),[saving,setSaving]=useState(false),[naturalWidth,setNaturalWidth]=useState(0),current=mode==='desktop'?desktop:mobile
 const setCurrent=p=>{const n=normalizeCoverPosition({...current,...p,unit:'percent'},mode);mode==='desktop'?setDesktop(n):setMobile(n)}
 const fit=coverFitOf(desktop)
 const movableX=fit==='contain'||current.zoom*current.scaleX>1
 const movableY=fit==='contain'||current.zoom*current.scaleY>1
 const setFit=v=>{setDesktop(d=>({...d,fit:v}));setMobile(m=>({...m,fit:v}))}
 const frame=frames[mode]||frames.desktop
 const minWidth=(minWidths||{})[mode]||0
 useEffect(()=>{if(!coverUrl)return;const probe=new Image();probe.onload=()=>setNaturalWidth(probe.naturalWidth);probe.src=coverUrl},[coverUrl])
 useEffect(()=>{const k=e=>{if(e.key==='Escape'&&!saving)onClose?.()};document.addEventListener('keydown',k);return()=>document.removeEventListener('keydown',k)},[onClose,saving])
 const down=e=>{if(!coverUrl)return;e.currentTarget.setPointerCapture?.(e.pointerId);const rect=e.currentTarget.getBoundingClientRect();setDrag({x:e.clientX,y:e.clientY,startX:current.xPct,startY:current.yPct,width:rect.width,height:rect.height})}
 const move=e=>{if(!drag)return;setCurrent({xPct:clamp(drag.startX+((e.clientX-drag.x)/drag.width)*100,-50,50),yPct:clamp(drag.startY+((e.clientY-drag.y)/drag.height)*100,-50,50)})}
 const up=()=>setDrag(null),reset=()=>setCurrent(DEFAULT)
 const save=async()=>{if(!coverUrl||!onSave)return;setSaving(true);try{await onSave({desktop,mobile})}finally{setSaving(false)}}
 const transform=useMemo(()=> 'translate('+current.xPct+'%,'+current.yPct+'%) scale('+current.zoom+') scaleX('+current.scaleX+') scaleY('+current.scaleY+')',[current])
 return <div className="cover-editor-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose?.()}}><section className="cover-editor-modal" role="dialog" aria-modal="true" aria-label={(kind==='logo'?'Ajustar logo de ':'Ajustar capa de ')+businessName}>
  <header className="cover-editor-header"><div><span className="cover-editor-kicker">{kind==="logo"?"AJUSTAR LOGO":"AJUSTAR CAPA"}</span><h2>{businessName}</h2><p>Arraste, aumente ou estique a imagem até posicionar o conteúdo importante exatamente dentro da área visível.</p></div><button type="button" className="cover-editor-close" onClick={onClose} disabled={saving} aria-label="Fechar editor">×</button></header>
  {kind!=='logo'&&<div className="cover-editor-tabs"><button type="button" className={mode==='desktop'?'active':''} onClick={()=>setMode('desktop')}>Desktop</button><button type="button" className={mode==='mobile'?'active':''} onClick={()=>setMode('mobile')}>Mobile</button></div>}
  <div className={'cover-editor-workspace '+mode}><div className="cover-editor-stage-wrap"><div className="cover-editor-stage" style={{aspectRatio:frame.width+' / '+frame.height}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{coverUrl?<div className="cover-editor-image" role="img" aria-label="Pré-visualização da imagem" style={{backgroundImage:'url("'+coverUrl+'")',backgroundSize:fit,transform,transformOrigin:'center center'}}/>:<div className="cover-editor-empty">Nenhuma capa carregada.</div>}<div className="cover-editor-safe"><span>Área segura</span></div></div><small>Arraste a imagem. O posicionamento de desktop e mobile é independente.</small>{naturalWidth>0&&minWidth>0&&naturalWidth<minWidth&&<p className="cover-editor-warning" role="status">Imagem pequena para esta área: {naturalWidth} px de largura. Recomendamos pelo menos {minWidth} px para ficar nítida.</p>}</div>
  <aside className="cover-editor-controls">{fit==='cover'&&<p className="cover-editor-explain" role="note"><strong>Por que o zoom começa em 100%?</strong> A foto precisa cobrir toda a área do site, senão aparecem faixas vazias. Por isso o zoom e o alongamento não diminuem abaixo de 100%. Para mover a foto, aumente o zoom. Para ver a imagem inteira (ex.: logos), marque "Mostrar a imagem inteira".</p>}<section><h3>Posição</h3>{fit==='cover'&&!movableX&&!movableY&&<p className="cover-editor-hint">Aumente o zoom para mover a foto.</p>}<label>Horizontal <strong>{current.xPct.toFixed(1)}%</strong></label><input aria-label="Posição horizontal" disabled={!movableX} type="range" min="-50" max="50" step="0.1" value={current.xPct} onChange={e=>setCurrent({xPct:Number(e.target.value)})}/><label>Vertical <strong>{current.yPct.toFixed(1)}%</strong></label><input aria-label="Posição vertical" disabled={!movableY} type="range" min="-50" max="50" step="0.1" value={current.yPct} onChange={e=>setCurrent({yPct:Number(e.target.value)})}/></section>
  <section><h3>Enquadramento</h3><label className="cover-editor-check"><input type="checkbox" checked={fit==='contain'} onChange={e=>setFit(e.target.checked?'contain':'cover')}/> Mostrar a imagem inteira (use para logos)</label></section><section><h3>Zoom <strong>{current.zoom.toFixed(2)}×</strong></h3><input aria-label="Zoom da capa" type="range" min={fit==='cover'?1:0.6} max="1.8" step="0.01" value={current.zoom} onChange={e=>setCurrent({zoom:Number(e.target.value)})}/><div className="cover-editor-zoom-buttons"><button type="button" onClick={()=>setCurrent({zoom:clamp(current.zoom-.05,.6,1.8)})}>−</button><button type="button" onClick={()=>setCurrent({zoom:clamp(current.zoom+.05,.6,1.8)})}>+</button></div></section><section><h3>Alongar imagem <strong>{Math.round(current.scaleX*100)}% × {Math.round(current.scaleY*100)}%</strong></h3><label>Largura <strong>{Math.round(current.scaleX*100)}%</strong></label><input aria-label="Largura da capa" type="range" min={fit==='cover'?1:0.6} max="1.8" step="0.01" value={current.scaleX} onChange={e=>setCurrent({scaleX:Number(e.target.value)})}/><label>Altura <strong>{Math.round(current.scaleY*100)}%</strong></label><input aria-label="Altura da capa" type="range" min={fit==='cover'?1:0.6} max="1.8" step="0.01" value={current.scaleY} onChange={e=>setCurrent({scaleY:Number(e.target.value)})}/><button type="button" className="cover-editor-secondary" onClick={()=>setCurrent({scaleX:1,scaleY:1})}>↺ Voltar à proporção original</button></section><button type="button" className="cover-editor-reset" onClick={reset}>↺ Restaurar posição</button></aside></div>
  <footer className="cover-editor-footer"><button type="button" className="cover-editor-cancel" onClick={onClose} disabled={saving}>Cancelar</button><button type="button" className="cover-editor-save" onClick={save} disabled={saving||!coverUrl}>{saving?'Salvando…':saveLabel}</button></footer>
 </section></div>
}