import React,{useEffect,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import'./account-workspace.css'
import'./demo-account.css'
import DemoAnalyticsSection from './DemoAnalyticsSection.jsx'

const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const DEMO_BUSINESS_ID='b4a06684-34bc-4e44-8de1-0868c88c7095'
const FALLBACK={id:DEMO_BUSINESS_ID,name:'Bistrô Laguna - Teste',status:'active',short_description:'Uma empresa de demonstração do VitrineLocal para apresentar como funciona a presença de um negócio na plataforma.',description:'Perfil demonstrativo do VitrineLocal.',cities:{name:'Laguna',state:'SC',slug:'laguna'},categories:{name:'Restaurantes'},logo_url:null,cover_url:null}

export default function DemoAccountPage(){
 const[business,setBusiness]=useState(FALLBACK),[promotions,setPromotions]=useState([]),[items,setItems]=useState([]),[photos,setPhotos]=useState([]),[section,setSection]=useState('overview'),[mobileMenu,setMobileMenu]=useState(false),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;(async()=>{if(!db){setLoading(false);return}const[b,p,i,ph]=await Promise.all([db.from('businesses').select('*,categories(id,name,slug,icon),cities(id,name,state,slug)').eq('id',DEMO_BUSINESS_ID).maybeSingle(),db.from('promotions').select('id,title,status,price,original_price,starts_at,ends_at').eq('business_id',DEMO_BUSINESS_ID).order('created_at',{ascending:false}),db.from('business_items').select('id,name,description,price,active,image_url').eq('business_id',DEMO_BUSINESS_ID).order('sort_order'),db.from('business_photos').select('id,url,media_type,alt_text').eq('business_id',DEMO_BUSINESS_ID).order('sort_order')]);if(!live)return;if(b.data)setBusiness(b.data);setPromotions(p.data||[]);setItems(i.data||[]);setPhotos(ph.data||[]);setLoading(false)})();return()=>{live=false}},[])
 const cityLabel=business.cities?`${business.cities.name} - ${business.cities.state||'SC'}`:'Laguna - SC'
 const statusLabel={active:'Ativa',pending:'Em análise',suspended:'Suspensa',rejected:'Rejeitada'}[business.status]||'Ativa'
 const go=key=>{setSection(key);setMobileMenu(false)}
 return <div className="app account-workspace-app demo-account-app"><header className="account-topbar"><div className="account-topbar-inner"><a className="account-brand" href="/laguna"><span>V</span><strong>Vitrine<span>Local</span></strong></a><div className="account-top-actions"><span className="account-city-pill">📍 {cityLabel}</span><span className="demo-account-badge">DEMO</span><a href="/laguna">Ver site</a><button className="account-mobile-toggle" onClick={()=>setMobileMenu(v=>!v)} aria-label="Abrir menu">☰</button></div></div></header><main className="account-workspace"><aside className={`account-sidebar ${mobileMenu?'open':''}`}><div className="account-sidebar-head"><div><span className="account-eyebrow">CONTA DEMONSTRATIVA</span><h2>Minha conta</h2></div><button onClick={()=>setMobileMenu(false)} aria-label="Fechar menu">×</button></div><div className="account-business-switcher"><span className="account-nav-label">EMPRESA ATIVA</span><div className="demo-business-select">{business.name}</div></div><nav className="account-sidebar-nav"><DemoNav active={section==='overview'} icon="⌂" label="Visão geral" onClick={()=>go('overview')}/><DemoNav active={section==='company'} icon="◈" label="Minha empresa" onClick={()=>go('company')}/><DemoNav active={section==='media'} icon="▣" label="Mídias" count={photos.length} onClick={()=>go('media')}/><DemoNav active={section==='items'} icon="◇" label="Produtos e serviços" count={items.length} onClick={()=>go('items')}/><DemoNav active={section==='promotions'} icon="✦" label="Promoções" count={promotions.length} onClick={()=>go('promotions')}/><DemoNav active={section==='analytics'} icon="◉" label="Desempenho" onClick={()=>go('analytics')}/><DemoNav active={section==='plan'} icon="◉" label="Meu plano" onClick={()=>go('plan')}/></nav><div className="account-sidebar-footer"><div className="account-user-chip"><div className="account-avatar">V</div><div><strong>Conta demonstração</strong><small>Somente visualização</small></div></div><a href="/laguna">← Voltar ao site</a></div></aside><section className="account-content"><div className="demo-account-notice"><strong>Modo demonstração</strong><span>Esta é uma conta de exemplo. Você pode navegar pelo painel sem cadastro ou login.</span></div>{loading?<div className="empty"><h3>Carregando dados da empresa…</h3></div>:section==='overview'?<Overview business={business} cityLabel={cityLabel} statusLabel={statusLabel} promotions={promotions} items={items} photos={photos} onSection={go}/>:section==='company'?<Company business={business} cityLabel={cityLabel}/>:section==='media'?<Media photos={photos}/>:section==='items'?<Items items={items}/>:section==='promotions'?<Promotions promotions={promotions}/>:section==='analytics'?<DemoAnalyticsSection/>:<Plan/>}</section></main></div>
}
function DemoNav({active,icon,label,count,onClick}){return <button type="button" className={`account-nav-item ${active?'active':''}`} onClick={onClick}><span className="nav-icon">{icon}</span><span>{label}</span>{count>0&&<b>{count}</b>}</button>}
function Overview({business,cityLabel,statusLabel,promotions,items,photos,onSection}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">VISÃO GERAL • DEMO</span><h1>Olá, {business.name}.</h1><p>Explore como uma empresa acompanha sua presença no VitrineLocal.</p></div><div className="account-status-badge"><i className="dot"/>{statusLabel}</div></div><div className="account-overview-card"><div className="account-overview-cover">{business.cover_url?<img src={business.cover_url} alt=""/>:<div className="account-cover-fallback">VitrineLocal</div>}<div className="account-overview-brand">{business.logo_url?<img src={business.logo_url} alt=""/>:<span>V</span>}</div></div><div className="account-overview-info"><div><span className="account-chip">{business.categories?.name||'Restaurantes'}</span><h2>{business.name}</h2><p>{business.short_description}</p><span className="account-muted">📍 {cityLabel}</span></div><div className="account-overview-actions"><button onClick={()=>onSection('company')}>Ver empresa</button><a href={`/${business.cities?.slug||'laguna'}/empresa/${encodeURIComponent(business.slug||'bistro-laguna-teste')}`}>Perfil público ↗</a></div></div></div><div className="account-stats-grid"><Stat label="Visualizações" value="128" sub="Visitas ao perfil"/><Stat label="WhatsApp" value="24" sub="Cliques de contato"/><Stat label="Instagram" value="17" sub="Acessos ao Instagram"/><Stat label="Site" value="9" sub="Cliques ao site"/></div><div className="account-quick-grid"><button onClick={()=>onSection('company')}><span>◈</span><div><strong>Minha empresa</strong><small>Dados, contatos e horários</small></div><b>→</b></button><button onClick={()=>onSection('items')}><span>◇</span><div><strong>Produtos e serviços</strong><small>{items.length} itens cadastrados na demonstração</small></div><b>→</b></button><button onClick={()=>onSection('promotions')}><span>✦</span><div><strong>Promoções</strong><small>{promotions.length} oferta(s) na demonstração</small></div><b>→</b></button></div><div className="demo-account-summary"><span>{photos.length} mídias</span><span>{items.length} produtos/serviços</span><span>{promotions.length} promoções</span><span>Plano demonstrativo</span></div></div>}
function Stat({label,value,sub}){return <div className="account-stat-card"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Company({business,cityLabel}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MINHA EMPRESA</span><h1>{business.name}</h1><p>Dados que aparecem no perfil público da empresa.</p></div><span className="account-status-badge"><i className="dot"/>Demonstração</span></div><div className="demo-detail-grid"><Detail label="Categoria" value={business.categories?.name||'Restaurantes'}/><Detail label="Cidade" value={cityLabel}/><Detail label="Descrição" value={business.short_description||'Perfil demonstrativo'}/><Detail label="Status" value={business.status==='active'?'Ativa':'Demonstração'}/></div><div className="demo-readonly-card"><strong>Conta em modo somente visualização</strong><p>Na versão comercial do VitrineLocal, o responsável pela empresa poderá editar estas informações, horários, contatos, mídias, produtos e promoções diretamente neste painel.</p></div></div>}
function Detail({label,value}){return <div className="demo-detail-card"><span>{label}</span><strong>{value}</strong></div>}
function Media({photos}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MÍDIAS</span><h1>Galeria da empresa</h1><p>Veja como as mídias ficam organizadas no painel.</p></div></div>{photos.length?<div className="demo-media-grid">{photos.map(p=><div className="demo-media-card" key={p.id}><img src={p.url} alt={p.alt_text||businessAlt}/></div>)}</div>:<div className="empty"><h3>Nenhuma mídia cadastrada na demonstração.</h3></div>}</div>}
const businessAlt='Imagem da empresa'
function Items({items}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">PRODUTOS E SERVIÇOS</span><h1>Catálogo</h1><p>Uma visão de exemplo do catálogo gerenciado pela empresa.</p></div></div><div className="demo-item-grid">{items.length?items.map(i=><article className="demo-item-card" key={i.id}>{i.image_url&&<img src={i.image_url} alt=""/>}<div><strong>{i.name}</strong><p>{i.description||'Produto ou serviço demonstrativo.'}</p>{i.price!=null&&<b>R$ {Number(i.price).toFixed(2).replace('.',',')}</b>}</div></article>):<div className="empty"><h3>Nenhum produto ou serviço cadastrado.</h3></div>}</div></div>}
function Promotions({promotions}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">PROMOÇÕES</span><h1>Ofertas da empresa</h1><p>Veja as promoções publicadas na conta demonstrativa.</p></div></div><div className="demo-promotion-grid">{promotions.length?promotions.map(p=><article className="demo-promotion-card" key={p.id}><span className="account-chip">{p.status==='published'?'PUBLICADA':p.status}</span><h3>{p.title}</h3><p>Oferta ativa no perfil público da empresa.</p>{p.original_price&&<del>R$ {Number(p.original_price).toFixed(2).replace('.',',')}</del>}{p.price!=null&&<strong>R$ {Number(p.price).toFixed(2).replace('.',',')}</strong>}</article>):<div className="empty"><h3>Nenhuma promoção cadastrada.</h3></div>}</div></div>}
function Plan(){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MEU PLANO</span><h1>Plano demonstrativo</h1><p>Uma prévia de como os recursos do plano aparecem para o empreendedor.</p></div></div><div className="demo-plan-card"><span>DEMONSTRAÇÃO</span><h2>VitrineLocal Pro</h2><p>Perfil completo, produtos e serviços, promoções, mídias e indicadores de presença.</p><div><b>✓ Perfil da empresa</b><b>✓ Produtos e serviços</b><b>✓ Promoções</b><b>✓ Analytics</b></div></div></div>}
