import React,{useEffect,useState}from'react'
import{getReviewSummary,getBusinessReviews}from'./review-service.js'
import'./review-performance.css'

const DEMO_BUSINESS_ID='b4a06684-34bc-4e44-8de1-0868c88c7095'
const fmtDate=v=>v?new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'}):''
const initials=n=>String(n||'U').trim().slice(0,1).toUpperCase()
export default function DemoReviewsPerformanceCard(){
 const[d,setD]=useState({avg:0,count:0,rows:[],distribution:{1:0,2:0,3:0,4:0,5:0},loading:true})
 useEffect(()=>{let live=true;(async()=>{try{const[{data:s},{data:r}]=await Promise.all([getReviewSummary(DEMO_BUSINESS_ID),getBusinessReviews(DEMO_BUSINESS_ID,20)]);if(!live)return;const x=s?.[0]||{},rows=r||[];setD({avg:Number(x.avg_rating||0),count:Number(x.review_count||rows.length),rows,distribution:{1:Number(x.one_star||0),2:Number(x.two_stars||0),3:Number(x.three_stars||0),4:Number(x.four_stars||0),5:Number(x.five_stars||0)},loading:false})}catch{if(live)setD(x=>({...x,loading:false}))}})();return()=>{live=false}},[])
 const bars=[5,4,3,2,1].map(n=>({n,count:d.distribution[n]||0,pct:d.count?Math.round((d.distribution[n]||0)/d.count*100):0}))
 const responded=d.rows.filter(r=>Boolean(r.owner_response)).length,waiting=Math.max(0,d.count-responded),responseRate=d.count?Math.round(responded/d.count*100):0
 return <section className="vp-card demo-review-performance" aria-label="Desempenho das avaliações"><header className="vp-head"><div><span className="vp-eyebrow">REPUTAÇÃO • DEMO</span><h2>Desempenho das avaliações</h2><p>Veja como a reputação da empresa aparece no painel do empreendedor.</p></div><div className="vp-score-box"><strong>{d.avg.toFixed(1)}</strong><span>★★★★★</span><small>{d.count} {d.count===1?'avaliação':'avaliações'}</small></div></header>{d.loading?<div className="vp-loading"><i/>Carregando avaliações…</div>:<><div className="vp-overview"><div className="vp-breakdown"><div className="vp-section-title"><strong>Distribuição das notas</strong><span>dados da demonstração</span></div>{bars.map(x=><div className="vp-bar" key={x.n}><span>{x.n} <b>★</b></span><div><i style={{width:`${x.pct}%`}}/></div><em>{x.count}</em></div>)}</div><div className="vp-health"><div className="vp-health-top"><span>ATENDIMENTO</span><b>{responseRate}% respondidas</b></div><div className="vp-health-grid"><div><strong>{d.count}</strong><small>Total</small></div><div><strong>{responded}</strong><small>Respondidas</small></div><div className={waiting?'attention':''}><strong>{waiting}</strong><small>Aguardando</small></div></div><div className="vp-progress"><i style={{width:`${responseRate}%`}}/></div><small className="vp-health-caption">Na conta real, o empreendedor poderá responder cada avaliação diretamente pelo painel.</small></div></div><div className="vp-list">{d.rows.length?d.rows.map(r=><article className="vp-review" key={r.id}><div className="vp-review-head"><div className="vp-avatar"><span>{initials(r.reviewer_name)}</span></div><div className="vp-reviewer"><strong>{r.reviewer_name||'Cliente'}</strong><time>{fmtDate(r.created_at)}</time></div><div className="vp-rating"><span>{'★'.repeat(Number(r.rating)||0)}</span><b>{Number(r.rating)||0}/5</b></div></div><p className="vp-comment">{r.comment||'O cliente não deixou um comentário por escrito.'}</p><div className="demo-review-readonly"><span>AVALIAÇÃO PUBLICADA</span><small>Modo demonstração · somente visualização</small></div></article>):<div className="vp-empty"><div>☆</div><strong>Nenhuma avaliação cadastrada</strong><span>As avaliações aparecerão aqui.</span></div>}</div></>}</section>
}
