import React,{useEffect,useMemo,useState} from "react"
import {supabase} from "./supabase-client.js"
import Icon from "./ui-icons.jsx"
import ModernBusinessesPage from "./ModernBusinessesPage.jsx"
import ModernBusinessProfilePage from "./ModernBusinessProfilePage.jsx"
import "./account-modern.css"
import "./account-workspace.css"
import "./demo.css"

const TABS=[["catalog","Catálogo público"],["profile","Perfil empresarial"],["account","Minha conta"]]
const NAV=[["overview","grid","Visão geral"],["company","briefcase","Minha empresa"],["media","image","Mídias"],["items","grid","Produtos e serviços"],["promotions","tag","Promoções"],["analytics","chart","Desempenho"],["plan","tag","Meu plano"]]
const LIMITS={photos:100,items:200,promotions:20}

export default function DemoPage(){
 const [tab,setTab]=useState("catalog"),[businesses,setBusinesses]=useState([]),[selectedId,setSelectedId]=useState(""),[promotions,setPromotions]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;(async()=>{
  if(!supabase){setLoading(false);return}
  const [b,p]=await Promise.all([
   supabase.from("public_business_directory").select("id,name,slug,short_description,description,logo_url,cover_url,address,neighborhood,phone,whatsapp,instagram_url,website_url,verified,featured,search_featured,city_name,city_state,category_name,category_slug,opening_hours,has_delivery,has_pickup,has_dine_in").eq("city_name","Laguna").order("featured",{ascending:false}).order("created_at",{ascending:false}).limit(100),
   supabase.from("promotions").select("id,title,description,price,original_price,image_url,status,business_id").eq("status","published").order("created_at",{ascending:false}).limit(20)
  ])
  if(!live)return
  const rows=b.data||[];setBusinesses(rows);setSelectedId(rows.find(x=>x.slug==="teste")?.id||rows[0]?.id||"");setPromotions(p.data||[]);setLoading(false)
 })();return()=>{live=false}},[])
 const selected=useMemo(()=>businesses.find(x=>x.id===selectedId)||businesses[0]||null,[businesses,selectedId])
 const selectedPromotions=useMemo(()=>promotions.filter(x=>x.business_id===selected?.id),[promotions,selected?.id])
 if(loading)return <div className="demo-loading"><span className="demo-kicker">MODO DEMONSTRAÇÃO</span><h1>Preparando o VitrineLocal…</h1><p>Carregando os dados públicos atuais em modo somente leitura.</p></div>
 return <main className="demo-shell">
  <section className="demo-banner"><div><span className="demo-kicker">VITRINELOCAL · DEMO</span><strong>Demonstração interativa</strong><p>Os dados desta página são somente leitura. Nenhuma ação modifica o projeto ou o banco.</p></div><span className="demo-premium"><Icon name="star" size={13}/> Experiência Premium</span></section>
  <nav className="demo-nav">{TABS.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}<span className="demo-nav-spacer"/><span className="demo-readonly"><Icon name="lock" size={12}/> Somente visualização</span></nav>
  {tab==="catalog"&&<div className="demo-surface"><ModernBusinessesPage citySlug="laguna"/></div>}
  {tab==="profile"&&selected&&<div className="demo-surface"><ModernBusinessProfilePage citySlug="laguna" businessSlug={selected.slug}/></div>}
  {tab==="account"&&selected&&<DemoAccount businesses={businesses} selected={selected} onSelect={setSelectedId} promotions={selectedPromotions}/>}
 </main>
}

function DemoAccount({businesses,selected,onSelect,promotions}){
 const [section,setSection]=useState("overview")
 return <div className="app account-workspace-app demo-account-app"><main className="account-workspace demo-account-workspace">
  <aside className="account-sidebar"><div className="account-sidebar-head"><div><span className="account-eyebrow">ESPAÇO DO EMPREENDEDOR</span><h2>Minha conta</h2></div><span className="demo-account-lock"><Icon name="lock" size={12}/></span></div>
   <div className="account-business-switcher"><span className="account-business-switcher-label">EMPRESA DE DEMONSTRAÇÃO</span><div className="account-business-switcher-row"><div className="account-business-switcher-avatar"><Icon name="store" size={15}/></div><select value={selected.id} onChange={e=>onSelect(e.target.value)}>{businesses.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><span className="account-business-switcher-status">Premium</span></div></div>
   <nav className="account-sidebar-nav">{NAV.map(([key,icon,label])=><button key={key} type="button" className={"account-nav-item "+(section===key?"active":"")} onClick={()=>setSection(key)}><span className="nav-icon"><Icon name={icon} size={17}/></span><span>{label}</span>{key==="media"&&<b>100</b>}{key==="promotions"&&<b>{promotions.length||1}</b>}</button>)}</nav>
   <div className="account-sidebar-footer"><div className="account-user-chip"><div className="account-avatar">D</div><div><strong>demo@vitrinelocal.net</strong><small>Modo demonstração</small></div></div><span className="demo-sidebar-premium">Plano Premium · completo</span></div>
  </aside>
  <section className="account-content"><div className="demo-account-strip"><Icon name="lock" size={12}/> Ambiente somente leitura: editar, excluir, publicar, fazer upload e contratar estão desativados.</div>
   {section==="overview"&&<DemoOverview selected={selected} onSection={setSection}/>} {section==="company"&&<DemoCompany selected={selected}/>} {section==="media"&&<DemoMedia selected={selected}/>} {section==="items"&&<DemoItems selected={selected}/>} {section==="promotions"&&<DemoPromotions selected={selected} promotions={promotions}/>} {section==="analytics"&&<DemoAnalytics/>} {section==="plan"&&<DemoPlan/>}
  </section>
 </main></div>
}

function DemoOverview({selected,onSection}){
 const stats=[["Visualizações","4.280"],["WhatsApp","312"],["Instagram","184"],["Site","96"]]
 return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">VISÃO GERAL · DEMO</span><h1>Olá, {selected.name}.</h1><p>Visualização do painel empresarial com todos os recursos Premium liberados.</p></div><div className="account-status-badge"><i className="dot"/>Ativa · Premium</div></div>
  <section className="account-completion-card"><div className="account-completion-top"><div><h2>Seu perfil está 100% completo</h2><p>Na demonstração, todas as etapas aparecem concluídas.</p></div><strong className="account-completion-score">100%</strong></div><div className="account-completion-progress"><i style={{width:"100%"}}/></div><div className="account-task-list"><span className="account-task done"><Icon name="check" size={11}/>Concluído · Perfil público</span><span className="account-task done"><Icon name="check" size={11}/>Concluído · Mídias</span><span className="account-task done"><Icon name="check" size={11}/>Concluído · Produtos e serviços</span><span className="account-task done"><Icon name="check" size={11}/>Concluído · Promoções</span></div></section>
  <div className="account-overview-card"><div className="account-overview-cover">{selected.cover_url?<img src={selected.cover_url} alt=""/>:<div className="account-cover-fallback">VitrineLocal</div>}<div className="account-overview-brand">{selected.logo_url?<img src={selected.logo_url} alt=""/>:<span>V</span>}</div></div><div className="account-overview-info"><div><span className="account-chip">{selected.category_name||"Empresa local"}</span><h2>{selected.name}</h2><p>{selected.short_description||"Presença empresarial no catálogo local."}</p><span className="account-muted"><Icon name="pin" size={11}/> {selected.city_name||"Laguna"} - {selected.city_state||"SC"}</span></div><div className="account-overview-actions"><button disabled>Editar empresa</button><button disabled>Ver perfil ↗</button></div></div></div>
  <div className="account-stats-grid">{stats.map(([label,value])=><div className="account-stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>Métrica simulada</small><em className="account-stat-period">Premium · demo</em></div>)}</div>
  <div className="account-quick-grid"><button onClick={()=>onSection("company")}><span><Icon name="briefcase" size={15}/></span><div><strong>Ver dados da empresa</strong><small>Cadastro atual em modo somente leitura</small></div><b>→</b></button><button onClick={()=>onSection("media")}><span><Icon name="image" size={15}/></span><div><strong>Explorar mídias</strong><small>Galeria e limites Premium</small></div><b>→</b></button><button onClick={()=>onSection("plan")}><span><Icon name="tag" size={15}/></span><div><strong>Ver recursos Premium</strong><small>Todos os módulos desbloqueados</small></div><b>→</b></button></div>
 </div>
}

function DemoCompany({selected}){
 const fields=[["Nome",selected.name],["Categoria",selected.category_name||"—"],["Cidade",(selected.city_name||"Laguna")+" - "+(selected.city_state||"SC")],["Endereço",selected.address||"—"],["Bairro",selected.neighborhood||"—"],["Telefone",selected.phone||"—"],["WhatsApp",selected.whatsapp||"—"],["Instagram",selected.instagram_url||"—"],["Site",selected.website_url||"—"]]
 return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MINHA EMPRESA · DEMO</span><h1>Dados da empresa</h1><p>Informações atuais, sem possibilidade de edição.</p></div><button className="account-primary-btn" disabled>Somente leitura</button></div><div className="account-card"><div className="account-card-title"><div><h2>Informações principais</h2><p>Todos os campos estão bloqueados.</p></div></div><div className="account-form-grid">{fields.map(([label,value])=><label className="field" key={label}><span>{label}</span><input value={String(value||"")} readOnly disabled/></label>)}</div></div></div>
}

function DemoMedia({selected}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MÍDIAS · DEMO</span><h1>Identidade e galeria</h1><p>Experiência Premium de mídias, somente para visualização.</p></div><button className="account-primary-btn" disabled>Adicionar mídia</button></div><div className="demo-media-grid"><div className="demo-media-card"><span>Capa</span>{selected.cover_url?<img src={selected.cover_url} alt="Capa"/>:<div className="demo-media-empty">Sem capa</div>}</div><div className="demo-media-card demo-logo-card"><span>Logo</span>{selected.logo_url?<img src={selected.logo_url} alt="Logo"/>:<div className="demo-media-empty">Sem logo</div>}</div></div><div className="account-card"><div className="account-card-title"><div><h2>Capacidade Premium</h2><p>{LIMITS.photos} mídias armazenadas permitidas no plano Premium.</p></div><span className="account-chip">Liberado</span></div><div className="demo-usage-bar"><i style={{width:"72%"}}/></div><small className="demo-muted">Uso ilustrativo da demonstração.</small></div></div>}

function DemoItems({selected}){const items=[["Menu executivo","Item demonstrativo"],["Prato da casa","Item demonstrativo"],["Serviço personalizado","Item demonstrativo"]];return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">PRODUTOS E SERVIÇOS · DEMO</span><h1>Catálogo da empresa</h1><p>Módulo Premium totalmente liberado para visualização.</p></div><button className="account-primary-btn" disabled>Adicionar item</button></div><div className="demo-usage-card"><span>Capacidade Premium</span><strong>32 / {LIMITS.items} itens</strong><div className="demo-usage-bar"><i style={{width:"16%"}}/></div></div><div className="demo-item-grid">{items.map(([title,desc],i)=><article className="demo-item-card" key={title}><div className="demo-item-icon"><Icon name={i===0?"utensils":i===1?"tag":"briefcase"} size={21}/></div><span>{selected.category_name||"Empresa"}</span><h3>{title}</h3><p>{desc}</p><button disabled>Editar</button></article>)}</div></div>}

function DemoPromotions({selected,promotions}){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">PROMOÇÕES · DEMO</span><h1>Ofertas da empresa</h1><p>Quota Premium liberada no modo de demonstração.</p></div><button className="account-primary-btn" disabled>Nova promoção</button></div><div className="demo-usage-card"><span>Quota mensal</span><strong>{promotions.length} / {LIMITS.promotions} promoções</strong><div className="demo-usage-bar"><i style={{width:Math.max(8,Math.min(promotions.length/LIMITS.promotions*100,100))+"%"}}/></div></div>{promotions.length?<div className="demo-promo-list">{promotions.map(p=><article className="demo-promo-row" key={p.id}><div className="demo-promo-thumb">{p.image_url?<img src={p.image_url} alt=""/>:<Icon name="tag" size={21}/>}</div><div><span>{selected.name}</span><h3>{p.title}</h3><p>{p.description||"Promoção publicada no catálogo."}</p></div><b>{p.price!=null?"R$ "+Number(p.price).toFixed(2).replace(".",","):"Confira"}</b></article>)}</div>:<div className="account-card demo-empty-state"><h2>Nenhuma promoção atual</h2><p>O módulo continua liberado no ambiente Premium.</p></div>}</div>}

function DemoAnalytics(){return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">DESEMPENHO · DEMO</span><h1>Analytics comercial</h1><p>Indicadores simulados para mostrar o módulo Premium.</p></div><span className="account-chip">Premium</span></div><div className="account-stats-grid">{[["Visualizações de perfil","4.280"],["Cliques em WhatsApp","312"],["Acessos ao Instagram","184"],["Cliques no site","96"]].map(([label,value])=><div className="account-stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>Dados simulados</small><em className="account-stat-period">Somente leitura</em></div>)}</div></div>}

function DemoPlan(){const features=["Perfil empresarial completo","Busca em destaque","Empresa verificada","Analytics avançado","Produtos e serviços","Até 100 mídias","Até 20 promoções por ciclo","Publicidade Premium","Gestão de avaliações","Instagram da cidade"];return <div className="account-section"><div className="account-section-header"><div><span className="account-eyebrow">MEU PLANO · DEMO</span><h1>Plano Premium</h1><p>Todos os recursos permanecem desbloqueados para visualização.</p></div><span className="demo-premium-large"><Icon name="star" size={15}/> PREMIUM</span></div><div className="demo-plan-hero"><div><span>PLANO ATIVO NA DEMONSTRAÇÃO</span><strong>Premium</strong><p>Experiência completa do painel empresarial, sem autenticação e sem gravação.</p></div><b>R$ 59,90<small>/mês · demonstração</small></b></div><div className="account-card"><div className="account-card-title"><div><h2>Recursos incluídos</h2><p>Todos desbloqueados no ambiente demo.</p></div></div><div className="demo-feature-grid">{features.map(x=><div key={x}><Icon name="check" size={13}/><span>{x}</span></div>)}</div></div></div>}
