/* VitrineLocal — safe media adaptation for business uploads. */
const TARGETS={logo:{width:1000,height:1000,label:'Logo · recomendado 1000 × 1000 px'},cover:{width:1600,height:600,label:'Capa · recomendado 1600 × 600 px'},promotion:{width:1200,height:628,label:'Promoção · recomendado 1200 × 628 px'},square:{width:1200,height:1200,label:'Imagem · recomendado 1200 × 1200 px'}}
function kindFor(input){if(input.closest('.owner-promo-file'))return'promotion';const media=input.closest('.account-upload-previews');if(media){const text=(media.textContent||'').toLowerCase();if(text.includes('logo'))return'logo';if(text.includes('capa'))return'cover'}return'square'}
function findGuidanceHost(input){return input.closest('.owner-promo-file')?.parentElement||input.closest('.file-button')?.parentElement||input.closest('.account-upload-previews')||input.closest('.vl-item-image-copy')||input.parentElement}
function addGuidance(input){const host=findGuidanceHost(input);if(!host||host.querySelector(':scope > .vl-media-guidance'))return;const kind=kindFor(input);const el=document.createElement('small');el.className='vl-media-guidance';el.textContent=TARGETS[kind].label+' · o VitrineLocal adapta automaticamente sem cortar o conteúdo.';host.appendChild(el)}
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível ler a imagem.'))};img.src=url})}
function drawSafe(canvas,img,target,transparent=false){const ctx=canvas.getContext('2d',{alpha:true});if(!transparent){ctx.save();ctx.filter='blur(28px) saturate(.9)';const scale=Math.max(target.width/img.width,target.height/img.height),bw=img.width*scale*1.12,bh=img.height*scale*1.12;ctx.drawImage(img,(target.width-bw)/2,(target.height-bh)/2,bw,bh);ctx.restore();ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(0,0,target.width,target.height)}const scale=Math.min(target.width/img.width,target.height/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(target.width-w)/2,(target.height-h)/2,w,h)}
async function adapt(file,kind){if(!file||!file.type.startsWith('image/')||file.type==='image/gif')return file;const target=TARGETS[kind]||TARGETS.square,img=await loadImage(file),canvas=document.createElement('canvas');canvas.width=target.width;canvas.height=target.height;drawSafe(canvas,img,target,kind==='logo');const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.92));if(!blob)return file;const base=(file.name||'imagem').replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-')||'imagem';return new File([blob],`${base}-vitrinelocal.jpg`,{type:'image/jpeg',lastModified:Date.now()})}
export async function adaptImageFile(file,kind='square'){return adapt(file,kind)}
async function handleChange(event){if(event.__vlAdaptedEvent==='1')return;const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=='file')return;if(input.closest('.vl-item-file'))return;addGuidance(input);const file=input.files?.[0];if(!file||!file.type.startsWith('image/')||file.type==='image/gif')return;event.stopImmediatePropagation();try{const adapted=await adapt(file,kindFor(input)),dt=new DataTransfer();dt.items.add(adapted);input.files=dt.files;const next=new Event('change',{bubbles:true});Object.defineProperty(next,'__vlAdaptedEvent',{value:'1'});input.dispatchEvent(next)}catch{const next=new Event('change',{bubbles:true});Object.defineProperty(next,'__vlAdaptedEvent',{value:'1'});input.dispatchEvent(next)}}
document.addEventListener('change',handleChange,true)
const observer=new MutationObserver(()=>document.querySelectorAll('input[type="file"]').forEach(addGuidance));observer.observe(document.documentElement,{subtree:true,childList:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('input[type="file"]').forEach(addGuidance),{once:true});else document.querySelectorAll('input[type="file"]').forEach(addGuidance)
