import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import{hasPlanFeature}from'./phase2-rules.js'
import'./merchant-advertising.css'

const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const TZ='America/Sao_Paulo'
const empty={title:'',description:'',target_url:'',desired_start_at:'',desired_end_at:'',monthly_budget:''}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:TZ}).format(new Date(v)):'—'
const eventMatchesAd=(event,ad)=>event.metadata?.advertisement_id===ad.id||(event.metadata?.title===ad.title&&event.metadata?.href===ad.target_url)
function localIso(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
export default function MerchantAdvertisingPage(){
 const[s,setS]=useState({loading:true,session:null,businesses:[],businessId:'',plan:null,ads:[],requests:[],events:[],error:''}),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[range,setRange]=useState(30),[message,setMessage]=useState({text:'',error:false})
 const notify=(text,error=false)=>setMessage({text,error})
 async function load(){if(!db||!s.businessId)return;const[{data:planId,error:pe},{data:ads,error:ae},{data:reqs,error:re},{data:events,error:ee}]=await Promise.all([db.rpc('get_effective_plan_id',{p_business_id:s.businessId}),db.from('advertisements').select('id,title,description,target_url,active,priority,starts_at,ends_at,monthly_price,billing_status,billing_started_at,billing_ends_at,image_url').eq('business_id',s.businessId).eq('placement','home_banner').order('created_at',{ascending:false}),db.from('advertising_requests').select('*').eq('business_id',s.businessId).order('created_at',{ascending:false}),db.from('analytics_events').select('event_type,created_at,metadata').eq('business_id',s.businessId).gte('created_at',new Date(Date.now()-range*86400000).toISOString())]);if(pe||ae||re||ee){notify((pe||ae||re||ee)?.message||'Não foi possível carregar a publicidade.',true);return}const{data:plan,error:pl}=await db.from('plans').select('id,code,name,features').eq('id',planId).maybeSingle();if(pl){notify(pl.message,true);return}setS(x=>({...x,plan,ads:ads||[],requests:reqs||[],events:events||[],error:''}))}
 useEffect(()=>{let live=true;(async()=>{if(!db){setS(x=>({...x,loading:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setS(x=>({...x,loading:false}));return}const{data:businesses,error}=await db.from('businesses').select('id,name,status').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(!live)return;if(error){setS({loading:false,session,businesses:[],businessId:'',plan:null,ads:[],requests:[],events:[],error:error.message});return}const businessId=businesses?.[0]?.id||'';setS(x=>({...x,loading:false,session,businesses:businesses||[],businessId}))})();return()=>{live=false}},[])
 useEffect(()=>{load()},[s.businessId,range])
 const premium=hasPlanFeature(s.plan?.features,'premium_ads',false)
 const adMetrics=useMemo(()=>{const rows=s.events.filter(e=>['banner_impression','banner_click'].includes(e.event_type)&&s.ads.some(a=>eventMatchesAd(e,a)));const impressions=rows.filter(e=>e.event_type==='banner_impression').length,clicks=rows.filter(e=>e.event_type==='banner_click').length;return{impressions,clicks,ctr:impressions?((clicks/impressions)*100).toFixed(1):'0.0'}},[s.events,s.ads])
 const activeAds=s.ads.filter(a=>a.active&&(!a.ends_at||new Date(a.ends_at)>new Date()))
 async function submit(e){e.preventDefault();if(saving)return;setMessage({text:'',error:false});if(!premium){notify('Publicidade Premium está disponível no plano Premium.',true);return}if(!form.title.trim())return notify('Informe o nome da campanha.',true);const budget=form.monthly_budget===''?0:Number(form.monthly_budget);if(!Number.isFinite(budget)||budget<0)return notify('Informe um orçamento mensal válido.',true);const start=localIso(form.desired_start_at),end=localIso(form.desired_end_at);if(form.desired_start_at&&!start)return notify('Data inicial inválida.',true);if(form.desired_end_at&&!end)return notify('Data final inválida.',true);if(start&&end&&new Date(end)<=new Date(start))return notify('A data final precisa ser posterior à inicial.',true);setSaving(true);const{error}=await db.from('advertising_requests').insert({business_id:s.businessId,requested_placement:'home_banner',title:form.title.trim(),description:form.description.trim()||null,target_url:form.target_url.trim()||null,desired_start_at:start,desired_end_at:end,monthly_budget:budget,status:'pending'});if(error)notify(error.message,true);else{notify('Solicitação enviada. Nossa equipe vai avaliar o espaço e o período.');setForm(empty);setOpen(false);await load()}setSaving(false)}
 if(s.loading)return <div className="merchant-ad-page"><div className="ma-empty">Carregando publicidade…</div></div>
 if(!s.session)return <div className="merchant-ad-page"><div className="ma-empty"><h1>Acesse sua conta para anunciar</h1><a href="/login?next=%2Fconta%2Fpublicidade">Entrar</a></div></div>
 if(!s.businesses.length)return <div className="merchant-ad-page"><div className="ma-empty"><h1>Cadastre sua empresa primeiro</h1><a href="/conta?new=business">Cadastrar empresa</a></div></div>
 if(s.error)return <div className="merchant-ad-page"><div className="ma-empty"><h1>Não foi possível carregar a publicidade</h1><p>{s.error}</p></div></div>
 if(!premium)return <main className="merchant-ad-page"><div className="ma-shell"><section className="ma-locked"><span>RECURSO PREMIUM</span><h1>Coloque sua empresa em destaque na Home</h1><p>Reserve espaço publicitário por cidade e aumente sua exposição com banners Premium medidos por impressões, cliques e CTR.</p><a href={`/planos?business_id=${encodeURIComponent(s.businessId)}`}>Conhecer Premium →</a></section></div></main>
 return <main className="merchant-ad-page"><div className="ma-shell">
  {message.text&&<div className={`ma-alert ${message.error?'error':'success'}`}>{message.text}</div>}
  <header className="ma-head"><div><span>PUBLICIDADE PREMIUM</span><h1>Anuncie sua empresa</h1><p>Gerencie solicitações e acompanhe o desempenho dos seus banners na VitrineLocal.</p></div><div className="ma-actions"><a href="/conta">← Minha conta</a><select value={range} onChange={e=>setRange(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select><button onClick={()=>setOpen(v=>!v)} className="ma-primary">＋ Nova solicitação</button></div></header>
  <section className="ma-kpis"><K label="Campanhas ativas" value={activeAds.length}/><K label="Impressões" value={adMetrics.impressions} note={`${range} dias`}/><K label="Cliques" value={adMetrics.clicks} tone="green" note={`${range} dias`}/><K label="CTR" value={`${adMetrics.ctr}%`} tone="amber" note="cliques ÷ impressões"/></section>
  {open&&<section className="ma-card ma-form"><div className="ma-card-head"><div><span>NOVA SOLICITAÇÃO</span><h2>Quero anunciar na Home</h2><p>Preencha a proposta. A equipe administrativa define disponibilidade, preço final e publicação.</p></div><button className="ma-close" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><div className="ma-form-grid"><label>Nome da campanha<input required maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Semana do Cliente"/></label><label>Link de destino<input type="url" value={form.target_url} onChange={e=>setForm({...form,target_url:e.target.value})} placeholder="https://..."/></label><label>Início desejado<input type="datetime-local" value={form.desired_start_at} onChange={e=>setForm({...form,desired_start_at:e.target.value})}/></label><label>Fim desejado<input type="datetime-local" value={form.desired_end_at} onChange={e=>setForm({...form,desired_end_at:e.target.value})}/></label><label>Orçamento mensal<input type="number" min="0" step="0.01" value={form.monthly_budget} onChange={e=>setForm({...form,monthly_budget:e.target.value})} placeholder="Ex.: 299,90"/></label><label className="full">Descrição<textarea rows="4" maxLength="500" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Objetivo, público, oferta e observações da campanha…"/></label></div><div className="ma-form-foot"><small>Fuso horário: {TZ}. O envio não publica automaticamente o banner.</small><div><button type="button" className="ma-secondary" onClick={()=>setOpen(false)} disabled={saving}>Cancelar</button><button className="ma-primary" disabled={saving}>{saving?'Enviando…':'Enviar solicitação'}</button></div></div></form></section>}
  <section className="ma-grid"><div className="ma-card"><div className="ma-card-head"><div><span>SUAS CAMPANHAS</span><h2>Banners Premium</h2><p>Valores e desempenho dos banners vinculados à empresa.</p></div></div>{s.ads.length?<div className="ma-list">{s.ads.map(a=>{const impressions=s.events.filter(e=>e.event_type==='banner_impression'&&eventMatchesAd(e,a)).length,clicks=s.events.filter(e=>e.event_type==='banner_click'&&eventMatchesAd(e,a)).length;return <div className="ma-list-row" key={a.id}><div className="ma-thumb">{a.image_url?<img src={a.image_url} alt=""/>:'★'}</div><div className="ma-main"><strong>{a.title}</strong><small>{a.active?'Ativo':'Pausado'} · {a.billing_status==='paid'?'Pago':a.billing_status==='pending'?'Pendente':a.billing_status==='overdue'?'Em atraso':'Sem cobrança'}</small><span>{a.monthly_price?`${money(a.monthly_price)}/mês`:'Preço a definir'} · {a.ends_at?`até ${dateTime(a.ends_at)}`:'sem fim definido'}</span></div><div className="ma-mini-metrics"><b>{impressions}</b><small>impressões</small><b>{clicks}</b><small>cliques</small></div></div>})}</div>:<div className="ma-empty-inline">Nenhum banner vinculado à sua empresa ainda.</div>}</div><div className="ma-card"><div className="ma-card-head"><div><span>SOLICITAÇÕES</span><h2>Histórico</h2><p>Acompanhe o andamento dos seus pedidos de publicidade.</p></div></div>{s.requests.length?<div className="ma-request-list">{s.requests.map(r=><div className="ma-request" key={r.id}><div><strong>{r.title}</strong><small>{r.desired_start_at?dateTime(r.desired_start_at):'Data a definir'} · orçamento {money(r.monthly_budget)}</small></div><span className={`ma-status ${r.status}`}>{r.status==='pending'?'Em análise':r.status==='approved'?'Aprovada':r.status==='rejected'?'Rejeitada':'Cancelada'}</span></div>)}</div>:<div className="ma-empty-inline">Nenhuma solicitação enviada.</div>}</div></section>
 </div></main>
}
function K({label,value,note='',tone=''}){return <div className={`ma-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
