import React,{useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import './analytics.css'
const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const EMPTY={profile_view:0,whatsapp_click:0,instagram_click:0,website_click:0,business_click:0,promotion_click:0}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function MerchantAnalyticsPage(){
 const [state,setState]=useState({checking:true,session:null,businesses:[],businessId:'',events:[]})
 useEffect(()=>{let live=true;(async()=>{if(!db){setState(x=>({...x,checking:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setState(x=>({...x,checking:false}));return}const{data:b}=await db.from('businesses').select('id,name,status,city_id').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(!live)return;const id=b?.[0]?.id||'';let events=[];if(id){const d=new Date();d.setDate(d.getDate()-29);const{data:e}=await db.from('analytics_events').select('event_type,created_at,metadata').eq('business_id',id).gte('created_at',d.toISOString());events=e||[]}if(live)setState({checking:false,session,businesses:b||[],businessId:id,events})})();return()=>{live=false}},[])
 const changeBusiness=async id=>{setState(x=>({...x,businessId:id,events:[]}));if(!db||!id)return;const d=new Date();d.setDate(d.getDate()-29);const{data}=await db.from('analytics_events').select('event_type,created_at,metadata').eq('business_id',id).gte('created_at',d.toISOString());setState(x=>({...x,businessId:id,events:data||[]}))}
 const counts=useMemo(()=>{const x={...EMPTY};state.events.forEach(e=>{if(Object.prototype.hasOwnProperty.call(x,e.event_type))x[e.event_type]+=1});return x},[state.events])
 const conversion=counts.profile_view?((counts.whatsapp_click/counts.profile_view)*100).toFixed(1):'0.0'
 const daily=useMemo(()=>{const out=[];for(let i=29;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);out.push({k,label:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),v:state.events.filter(e=>e.created_at?.slice(0,10)===k).length})}const max=Math.max(1,...out.map(x=>x.v));return{out,max}},[state.events])
 if(state.checking)return <div className="analytics-page"><div className="analytics-empty">Verificando sua conta…</div></div>
 if(!state.session)return <div className="analytics-page"><div className="analytics-empty"><strong>Entre para acompanhar seu desempenho.</strong><a href="/login?next=%2Fconta%2Fanalytics">Entrar</a></div></div>
 if(!state.businesses.length)return <div className="analytics-page"><div className="analytics-empty"><strong>Você ainda não possui uma empresa cadastrada.</strong><a href="/conta?new=business">Cadastrar empresa</a></div></div>
 return <main className="analytics-page"><div className="analytics-shell"><div className="analytics-head"><div><span>DESEMPENHO DA EMPRESA</span><h1>Analytics</h1><p>Veja como as pessoas encontram e entram em contato com seu negócio.</p></div><div className="analytics-head-actions"><a href="/conta">← Minha conta</a><select value={state.businessId} onChange={e=>changeBusiness(e.target.value)}>{state.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div></div><section className="analytics-kpis"><K title="Visualizações" value={counts.profile_view} note="perfil · 30 dias"/><K title="WhatsApp" value={counts.whatsapp_click} note="contatos iniciados" c="green"/><K title="Instagram" value={counts.instagram_click} note="visitas geradas" c="purple"/><K title="Conversão" value={`${conversion}%`} note="visitas → WhatsApp" c="amber"/></section><section className="analytics-grid"><div className="analytics-card"><div className="analytics-card-head"><div><span>TRÁFEGO</span><h2>Atividade diária</h2><p>Todos os eventos registrados para esta empresa.</p></div><strong>{state.events.length}</strong></div><div className="analytics-chart">{daily.out.map(x=><div className="analytics-bar-wrap" key={x.k} title={`${x.label}: ${x.v}`}><i style={{height:`${Math.max(4,x.v/daily.max*100)}%`}}/><small>{x.label}</small></div>)}</div></div><div className="analytics-card"><div className="analytics-card-head"><div><span>AÇÕES</span><h2>Onde o cliente clicou</h2><p>Intenções registradas no perfil.</p></div></div><div className="analytics-action-list"><Row label="WhatsApp" value={counts.whatsapp_click}/><Row label="Instagram" value={counts.instagram_click}/><Row label="Site" value={counts.website_click}/><Row label="Promoções" value={counts.promotion_click}/></div></div></section><section className="analytics-card"><div className="analytics-card-head"><div><span>INTERPRETAÇÃO</span><h2>Como melhorar</h2><p>Use estes sinais para manter o perfil comercial mais competitivo.</p></div></div><div className="analytics-tips"><div><strong>Fotos e capa</strong><small>Perfis visuais tendem a comunicar melhor o negócio. Mantenha logo e capa atualizadas.</small></div><div><strong>WhatsApp em destaque</strong><small>{counts.whatsapp_click?`Você recebeu ${counts.whatsapp_click} cliques no período.`:'Ainda não houve cliques registrados no WhatsApp neste período.'}</small></div><div><strong>Descrição</strong><small>Use uma descrição curta e objetiva para explicar o principal diferencial da empresa.</small></div></div></section></div></main>
}
function K({title,value,note,c=''}){return <div className={`analytics-kpi ${c}`}><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
function Row({label,value}){return <div className="analytics-row"><span>{label}</span><strong>{value}</strong></div>}
