import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import{hasPlanFeature}from'./phase2-rules.js'
import{chooseBusiness,getRequestedBusinessId,persistBusinessId}from'./business-selection.js'
import'./merchant-advertising-sales.css'

const U=import.meta.env.VITE_SUPABASE_URL,K=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,db=U&&K?createClient(U,K):null
const BUCKET='advertising-request-art',MAX_BYTES=10*1024*1024,TYPES=new Set(['image/jpeg','image/png','image/webp']),TZ='America/Sao_Paulo'
const empty={title:'',description:'',target_url:'',desired_start_at:'',desired_end_at:'',monthly_budget:'',creative_mode:'self'}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateTime=v=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:TZ}).format(new Date(v)):'—'
const localIso=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
const statusLabel=(r)=>r.payment_status==='paid'?'Pagamento confirmado':r.status==='approved'&&r.payment_status==='awaiting_payment'?'Aguardando pagamento':r.status==='rejected'?'Rejeitada':r.status==='approved'?'Aprovada':'Em análise'

export default function MerchantAdvertisingSalesPage(){
 const[s,setS]=useState({loading:true,session:null,businesses:[],businessId:'',plan:null,requests:[],ads:[],error:''}),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[file,setFile]=useState(null),[saving,setSaving]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState({text:'',error:false}),[paymentMessage,setPaymentMessage]=useState('')
 const notify=(text,error=false)=>setMessage({text,error})
 async function load(){
  if(!db||!s.businessId)return
  const[{data:planId,error:pe},{data:requests,error:re},{data:ads,error:ae}]=await Promise.all([
   db.rpc('get_effective_plan_id',{p_business_id:s.businessId}),
   db.from('advertising_requests').select('id,business_id,requested_placement,title,description,target_url,desired_start_at,desired_end_at,monthly_budget,final_price,status,admin_note,created_at,updated_at,creative_mode,artwork_path,artwork_url,payment_status,paid_at,approved_at,stripe_subscription_id').eq('business_id',s.businessId).order('created_at',{ascending:false}),
   db.from('advertisements').select('id,title,active,starts_at,ends_at,monthly_price,billing_status,image_url').eq('business_id',s.businessId).eq('placement','home_banner').order('created_at',{ascending:false})
  ])
  if(pe||re||ae){notify((pe||re||ae)?.message||'Não foi possível carregar a publicidade.',true);return}
  const{data:plan,error:pl}=await db.from('plans').select('id,code,name,features').eq('id',planId).maybeSingle()
  if(pl){notify(pl.message,true);return}
  setS(x=>({...x,plan,requests:requests||[],ads:ads||[],error:''}))
 }
 useEffect(()=>{let live=true;(async()=>{if(!db){setS(x=>({...x,loading:false}));return}const{data:{session}}=await db.auth.getSession();if(!live)return;if(!session){setS(x=>({...x,loading:false}));return}const{data:businesses,error}=await db.from('businesses').select('id,name,status').eq('owner_id',session.user.id).order('created_at',{ascending:false});if(!live)return;if(error){setS({loading:false,session,businesses:[],businessId:'',plan:null,requests:[],ads:[],error:error.message});return}const selected=chooseBusiness(businesses,getRequestedBusinessId());persistBusinessId(selected?.id);setS(x=>({...x,loading:false,session,businesses:businesses||[],businessId:selected?.id||''}))})();return()=>{live=false}},[])
 useEffect(()=>{load()},[s.businessId])
 useEffect(()=>{const p=new URLSearchParams(location.search);const result=p.get('payment');if(result==='success')setPaymentMessage('Pagamento recebido. O Stripe está confirmando a assinatura e a campanha será sincronizada automaticamente.');else if(result==='cancelled')setPaymentMessage('Checkout cancelado. Nenhuma campanha foi ativada por esta sessão.')},[])
 const premium=hasPlanFeature(s.plan?.features,'premium_ads',false)
 const activeAds=useMemo(()=>s.ads.filter(a=>a.active&&(!a.ends_at||new Date(a.ends_at)>new Date())),[s.ads])
 const pending=s.requests.filter(r=>r.status==='pending').length
 const awaiting=s.requests.filter(r=>r.payment_status==='awaiting_payment').length
 async function submit(e){e.preventDefault();if(saving)return;setMessage({text:'',error:false});if(!premium)return notify('Publicidade Premium está disponível apenas para o plano Premium.',true);if(!form.title.trim())return notify('Informe o nome da campanha.',true);const budget=Number(form.monthly_budget);if(!Number.isFinite(budget)||budget<0)return notify('Informe um orçamento mensal válido.',true);const start=localIso(form.desired_start_at),end=localIso(form.desired_end_at);if(form.desired_start_at&&!start)return notify('Data inicial inválida.',true);if(form.desired_end_at&&!end)return notify('Data final inválida.',true);if(start&&end&&new Date(end)<=new Date(start))return notify('A data final precisa ser posterior à inicial.',true);if(form.creative_mode==='self'&&!file)return notify('Anexe a arte do banner ou escolha a opção para o VitrineLocal criar a arte.',true);if(file&&(!TYPES.has(file.type)||file.size>MAX_BYTES))return notify('A arte deve ser JPG, PNG ou WebP e ter até 10 MB.',true);setSaving(true);let requestId='';let uploadedPath='';try{const{data:r,error}=await db.from('advertising_requests').insert({business_id:s.businessId,requested_placement:'home_banner',title:form.title.trim(),description:form.description.trim()||null,target_url:form.target_url.trim()||null,desired_start_at:start,desired_end_at:end,monthly_budget:budget,creative_mode:form.creative_mode}).select('id').single();if(error)throw error;requestId=r.id;if(file){const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';uploadedPath=`${requestId}/${crypto.randomUUID()}.${ext}`;const upload=await db.storage.from(BUCKET).upload(uploadedPath,file,{cacheControl:'31536000',contentType:file.type,upsert:false});if(upload.error)throw upload.error;const url=db.storage.from(BUCKET).getPublicUrl(uploadedPath).data.publicUrl;const{error:creativeError}=await db.rpc('owner_set_advertising_request_creative',{p_request_id:requestId,p_creative_mode:'self',p_artwork_path:uploadedPath,p_artwork_url:url});if(creativeError)throw creativeError}else{const{error:creativeError}=await db.rpc('owner_set_advertising_request_creative',{p_request_id:requestId,p_creative_mode:'design',p_artwork_path:null,p_artwork_url:null});if(creativeError)throw creativeError}notify('Solicitação enviada. A equipe vai analisar o espaço, o período e o valor final.');setForm(empty);setFile(null);setOpen(false);await load()}catch(err){if(uploadedPath)await db.storage.from(BUCKET).remove([uploadedPath]).catch(()=>{});notify(err.message||'Não foi possível enviar a solicitação.',true)}finally{setSaving(false)}}
 async function pay(request){setBusy(request.id);notify('Preparando pagamento seguro…');const{data,error}=await db.functions.invoke('create-advertising-checkout-session',{body:{request_id:request.id}});if(error){notify(error.message||'Não foi possível abrir o pagamento.',true);setBusy('');return}if(data?.url){location.href=data.url;return}notify('O checkout não retornou um endereço válido.',true);setBusy('')}
 if(s.loading)return <main className="ma-sales"><div className="ma-sales-empty">Carregando publicidade Premium…</div></main>
 if(!s.session)return <main className="ma-sales"><div className="ma-sales-empty"><h1>Entre para anunciar</h1><p>Acesse sua conta para solicitar um banner Premium.</p><a href="/login?next=%2Fconta%2Fpublicidade">Entrar</a></div></main>
 if(!s.businesses.length)return <main className="ma-sales"><div className="ma-sales-empty"><h1>Cadastre sua empresa primeiro</h1><a href="/conta?new=business">Cadastrar empresa</a></div></main>
 if(s.error)return <main className="ma-sales"><div className="ma-sales-empty"><h1>Não foi possível carregar a publicidade</h1><p>{s.error}</p></div></main>
 if(!premium)return <main className="ma-sales"><div className="ma-sales-locked"><span>RECURSO PREMIUM</span><h1>Publicidade Premium</h1><p>Coloque sua empresa em destaque na Home e acompanhe impressões, cliques e CTR.</p><a href={`/planos?business_id=${encodeURIComponent(s.businessId)}`}>Conhecer o Premium →</a></div></main>
 return <main className="ma-sales"><div className="ma-sales-shell">
  {paymentMessage&&<div className="ma-sales-banner success">{paymentMessage}</div>}
  {message.text&&<div className={`ma-sales-banner ${message.error?'error':'success'}`}>{message.text}</div>}
  <header className="ma-sales-head"><div><span>PUBLICIDADE PREMIUM</span><h1>Venda mais com destaque na Home</h1><p>Solicite seu espaço, envie a arte, receba a proposta e pague pelo Stripe. A campanha só entra no ar depois da confirmação do pagamento e dentro do período contratado.</p></div><div className="ma-sales-actions"><select value={s.businessId} onChange={e=>{persistBusinessId(e.target.value);setS(x=>({...x,businessId:e.target.value}))}}>{s.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="ma-sales-primary" onClick={()=>setOpen(v=>!v)}>＋ Solicitar banner</button></div></header>
  <section className="ma-sales-kpis"><Kpi label="Campanhas ativas" value={activeAds.length}/><Kpi label="Solicitações" value={s.requests.length}/><Kpi label="Em análise" value={pending}/><Kpi label="Aguardando pagamento" value={awaiting}/></section>
  {open&&<section className="ma-sales-card"><div className="ma-sales-card-head"><div><span>NOVA SOLICITAÇÃO</span><h2>Quero anunciar na Home</h2><p>O orçamento informado é uma referência. O valor final será definido na aprovação administrativa.</p></div><button className="ma-sales-close" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit} className="ma-sales-form"><div className="ma-sales-grid"><label>Nome da campanha<input required maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Link de destino<input type="url" value={form.target_url} onChange={e=>setForm({...form,target_url:e.target.value})} placeholder="https://..."/></label><label>Início desejado<input type="datetime-local" value={form.desired_start_at} onChange={e=>setForm({...form,desired_start_at:e.target.value})}/></label><label>Fim desejado<input type="datetime-local" value={form.desired_end_at} onChange={e=>setForm({...form,desired_end_at:e.target.value})}/></label><label>Orçamento mensal de referência<input type="number" min="0" step="0.01" value={form.monthly_budget} onChange={e=>setForm({...form,monthly_budget:e.target.value})}/></label><label>Material criativo<select value={form.creative_mode} onChange={e=>setForm({...form,creative_mode:e.target.value})}><option value="self">Vou enviar minha arte</option><option value="design">Quero que o VitrineLocal crie a arte</option></select></label><label className="full">Arte do banner<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={form.creative_mode!=='self'}/><small>{form.creative_mode==='self'?'JPG, PNG ou WebP · até 10 MB.':'A equipe produzirá a arte antes da publicação.'}</small></label><label className="full">Descrição / objetivo<textarea rows="4" maxLength="500" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="ma-sales-form-foot"><small>Fuso horário: {TZ}. Enviar a solicitação não cria cobrança e não publica automaticamente.</small><div><button type="button" className="ma-sales-secondary" onClick={()=>setOpen(false)} disabled={saving}>Cancelar</button><button className="ma-sales-primary" disabled={saving}>{saving?'Enviando…':'Enviar solicitação'}</button></div></div></form></section>}
  <section className="ma-sales-card"><div className="ma-sales-card-head"><div><span>JORNADA COMERCIAL</span><h2>Como funciona</h2></div></div><div className="ma-sales-steps"><Step n="1" title="Solicite" text="Escolha período, orçamento e material criativo."/><Step n="2" title="Aprovação" text="Nossa equipe analisa disponibilidade e define o valor final."/><Step n="3" title="Pague" text="Quando aprovado, o checkout Stripe fica disponível para você."/><Step n="4" title="Entre no ar" text="Após o pagamento, a campanha é sincronizada e ativada no período contratado quando a arte estiver pronta."/></div></section>
  <section className="ma-sales-grid-2"><div className="ma-sales-card"><div className="ma-sales-card-head"><div><span>SEUS PEDIDOS</span><h2>Solicitações</h2></div></div>{s.requests.length?<div className="ma-sales-list">{s.requests.map(r=><div className="ma-sales-row" key={r.id}><div className="ma-sales-art">{r.artwork_url?<img src={r.artwork_url} alt=""/>:'★'}</div><div className="ma-sales-main"><strong>{r.title}</strong><small>{statusLabel(r)} · enviado em {dateTime(r.created_at)}</small><span>{r.final_price>0?`${money(r.final_price)}/mês`:'Valor a definir'} · {r.desired_start_at?dateTime(r.desired_start_at):'Início a definir'}</span>{r.admin_note&&<em>{r.admin_note}</em>}</div><div className="ma-sales-row-actions">{r.payment_status==='awaiting_payment'&&<button className="ma-sales-primary compact" disabled={busy===r.id} onClick={()=>pay(r)}>{busy===r.id?'Abrindo…':'Pagar e contratar'}</button>} {r.payment_status==='paid'&&<span className="ma-sales-paid">Pago</span>}</div></div>)}</div>:<div className="ma-sales-empty-inline">Nenhuma solicitação enviada ainda.</div>}</div><div className="ma-sales-card"><div className="ma-sales-card-head"><div><span>SUAS CAMPANHAS</span><h2>Banners</h2></div></div>{s.ads.length?<div className="ma-sales-list">{s.ads.map(a=><div className="ma-sales-row" key={a.id}><div className="ma-sales-art">{a.image_url?<img src={a.image_url} alt=""/>:'★'}</div><div className="ma-sales-main"><strong>{a.title}</strong><small>{a.active?'Ativo':'Aguardando início/publicação'} · {a.billing_status}</small><span>{money(a.monthly_price)}/mês · {a.starts_at?dateTime(a.starts_at):'sem início definido'}{a.ends_at?` · até ${dateTime(a.ends_at)}`:''}</span></div></div>)}</div>:<div className="ma-sales-empty-inline">Nenhuma campanha paga vinculada à empresa.</div>}</div></section>
 </div></main>
}
function Kpi({label,value}){return <div className="ma-sales-kpi"><span>{label}</span><strong>{value}</strong></div>}
function Step({n,title,text}){return <div className="ma-sales-step"><b>{n}</b><div><strong>{title}</strong><span>{text}</span></div></div>}
