import React,{useEffect,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import'./notification-center.css'
const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
function formatDate(value){if(!value)return '';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
export default function NotificationCenter({userId,onUnreadChange}){
 const[items,setItems]=useState([]),[preferences,setPreferences]=useState({promotions_enabled:true,business_enabled:true,system_enabled:true,city_id:'',category_ids:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({text:'',error:false})
 const notify=(text,error=false)=>setMessage({text,error})
 async function load(){if(!db||!userId)return;setLoading(true);const[notifications,prefs]=await Promise.all([db.from('notifications').select('id,title,body,url,type,status,created_at,read_at,business_id,promotion_id,image_url').eq('user_id',userId).order('created_at',{ascending:false}).limit(50),db.from('notification_preferences').select('promotions_enabled,business_enabled,system_enabled,city_id,category_ids').eq('user_id',userId).maybeSingle()]);if(notifications.error)notify(notifications.error.message,true);if(prefs.error)notify(prefs.error.message,true);const rows=notifications.data||[];setItems(rows);setPreferences(prefs.data||{promotions_enabled:true,business_enabled:true,system_enabled:true,city_id:'',category_ids:[]});onUnreadChange?.(rows.filter(row=>!row.read_at).length);setLoading(false)}
 useEffect(()=>{load()},[userId])
 async function markRead(id){if(!db||!userId)return;const now=new Date().toISOString();const{error}=await db.from('notifications').update({read_at:now}).eq('id',id).eq('user_id',userId);if(error)return notify(error.message,true);const next=items.map(row=>row.id===id?{...row,read_at:now}:row);setItems(next);onUnreadChange?.(next.filter(row=>!row.read_at).length)}
 async function markAllRead(){if(!db||!userId)return;const now=new Date().toISOString();const{error}=await db.from('notifications').update({read_at:now}).eq('user_id',userId).is('read_at',null);if(error)return notify(error.message,true);const next=items.map(row=>({...row,read_at:row.read_at||now}));setItems(next);onUnreadChange?.(0)}
 async function savePreferences(next){if(!db||!userId)return;setSaving(true);setMessage({text:'',error:false});const{error}=await db.from('notification_preferences').upsert({user_id:userId,...next},{onConflict:'user_id'});if(error)notify(error.message,true);else{setPreferences(next);notify('Preferências de notificações atualizadas.')}setSaving(false)}
 function openNotification(row){if(!row.read_at)markRead(row.id);if(row.url)location.href=row.url}
 if(loading)return <div className="account-card notification-center"><div className="notification-center-loading">Carregando notificações…</div></div>
 const unread=items.filter(row=>!row.read_at).length
 return <div className="notification-center">{message.text&&<div className={'account-alert '+(message.error?'error':'')}>{message.text}</div>}
  <section className="account-card notification-preferences-card"><div className="account-card-title"><div><h2>Preferências</h2><p>Escolha quais notificações da VitrineLocal você deseja receber.</p></div></div><div className="notification-preference-list">{[['promotions_enabled','Promoções','Receba ofertas e novidades das empresas.'],['business_enabled','Empresas','Atualizações e novidades de empresas acompanhadas.'],['system_enabled','Sistema','Informações importantes sobre sua conta e a VitrineLocal.']].map(([key,title,description])=><label className="notification-preference-row" key={key}><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={Boolean(preferences[key])} disabled={saving} onChange={e=>savePreferences({...preferences,[key]:e.target.checked})}/></label>)}</div><div className="notification-segmentation-note"><strong>Personalização preparada</strong><span>Cidade e categoria já estão estruturadas para a próxima etapa de segmentação.</span></div></section>
  <section className="account-card notification-history-card"><div className="account-card-title"><div><h2>Histórico</h2><p>{unread===0?'Tudo lido':unread===1?'1 não lida':unread+' não lidas'} · últimas 50 notificações</p></div>{unread>0&&<button type="button" className="account-secondary-btn small" onClick={markAllRead}>Marcar todas como lidas</button>}</div>{items.length?<div className="notification-history-list">{items.map(row=><article className={'notification-history-item '+(!row.read_at?'unread':'')} key={row.id} onClick={()=>openNotification(row)} role={row.url?'button':undefined} tabIndex={row.url?0:undefined} onKeyDown={e=>{if(row.url&&(e.key==='Enter'||e.key===' '))openNotification(row)}}>{row.image_url?<img src={row.image_url} alt="" className="notification-history-image"/>:<div className="notification-history-icon">🔔</div>}<div className="notification-history-copy"><div><strong>{row.title}</strong>{!row.read_at&&<i aria-label="Não lida"/>}</div><p>{row.body}</p><small>{formatDate(row.created_at)} · {row.type==='promotion'?'Promoção':row.type==='business'?'Empresa':'VitrineLocal'}</small></div>{row.url&&<span className="notification-history-arrow">→</span>}</article>)}</div>:<div className="account-empty-inline notification-empty"><span>🔔</span><strong>Nenhuma notificação ainda</strong><p>Quando uma empresa enviar uma novidade, ela aparecerá aqui.</p></div>}</section>
 </div>
}