import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import'./notification-center.css'
const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const DEFAULT_PREFERENCES={promotions_enabled:true,business_enabled:true,system_enabled:true,city_id:'',category_ids:[]}
const TYPE_OPTIONS=[['all','Todas'],['promotion','Promoções'],['business','Empresas'],['system','Sistema']]
function formatDate(value){if(!value)return '';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
function typeLabel(type){return type==='promotion'?'Promoção':type==='business'?'Empresa':type==='system'?'Sistema':'VitrineLocal'}
function statusLabel(status){return status==='delivered'?'Recebida':status==='sent'?'Enviada':status==='failed'?'Falhou':'Processando'}
export default function NotificationCenter({userId,onUnreadChange}){
 const[items,setItems]=useState([]),[preferences,setPreferences]=useState(DEFAULT_PREFERENCES),[cities,setCities]=useState([]),[categories,setCategories]=useState([]),[filters,setFilters]=useState({type:'all',city_id:'',category_id:'',unreadOnly:false}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({text:'',error:false})
 const notify=(text,error=false)=>setMessage({text,error})
 async function load(){if(!db||!userId)return;const[notifications,prefs,cityRes,categoryRes]=await Promise.all([db.from('notifications').select('id,title,body,url,type,status,created_at,read_at,business_id,promotion_id,image_url,target_city_id,target_category_id,delivered_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(100),db.from('notification_preferences').select('promotions_enabled,business_enabled,system_enabled,city_id,category_ids').eq('user_id',userId).maybeSingle(),db.from('cities').select('id,name,state').order('name').limit(500),db.from('categories').select('id,name').eq('active',true).order('name').limit(500)]);if(notifications.error)notify(notifications.error.message,true);if(prefs.error)notify(prefs.error.message,true);if(cityRes.error)notify(cityRes.error.message,true);if(categoryRes.error)notify(categoryRes.error.message,true);const rows=notifications.data||[];setItems(rows);setPreferences({...DEFAULT_PREFERENCES,...(prefs.data||{}),category_ids:Array.isArray(prefs.data?.category_ids)?prefs.data.category_ids:[]});setCities(cityRes.data||[]);setCategories(categoryRes.data||[]);onUnreadChange?.(rows.filter(row=>!row.read_at).length);setLoading(false)}
 useEffect(()=>{setLoading(true);load()},[userId])
 useEffect(()=>{if(!db||!userId)return;const channel=db.channel('notification-center-'+userId).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:'user_id=eq.'+userId},payload=>{if(payload.eventType==='INSERT')setItems(current=>[payload.new,...current].slice(0,100));else if(payload.eventType==='UPDATE')setItems(current=>current.map(row=>row.id===payload.new.id?{...row,...payload.new}:row));else if(payload.eventType==='DELETE')setItems(current=>current.filter(row=>row.id!==payload.old.id))});channel.subscribe(status=>{if(status==='CHANNEL_ERROR')notify('Não foi possível manter o contador de notificações em tempo real.',true)});return()=>{db.removeChannel(channel)}},[userId])
 useEffect(()=>{const unread=items.filter(row=>!row.read_at).length;onUnreadChange?.(unread)},[items,onUnreadChange])
 async function markRead(id){if(!db||!userId)return;const row=items.find(item=>item.id===id);if(!row||row.read_at)return;const now=new Date().toISOString();const{error}=await db.from('notifications').update({read_at:now}).eq('id',id).eq('user_id',userId);if(error)return notify(error.message,true);setItems(current=>current.map(item=>item.id===id?{...item,read_at:now}:item))}
 async function markAllRead(){if(!db||!userId)return;const now=new Date().toISOString();const{error}=await db.from('notifications').update({read_at:now}).eq('user_id',userId).is('read_at',null);if(error)return notify(error.message,true);setItems(current=>current.map(row=>({...row,read_at:row.read_at||now})))}
 async function savePreferences(next){if(!db||!userId)return;setSaving(true);setMessage({text:'',error:false});const{error}=await db.from('notification_preferences').upsert({user_id:userId,promotions_enabled:Boolean(next.promotions_enabled),business_enabled:Boolean(next.business_enabled),system_enabled:Boolean(next.system_enabled),city_id:next.city_id||null,category_ids:Array.isArray(next.category_ids)?next.category_ids:[]},{onConflict:'user_id'});if(error)notify(error.message,true);else{setPreferences(next);notify('Preferências de notificações atualizadas.')}setSaving(false)}
 function toggleCategory(id){const nextIds=preferences.category_ids.includes(id)?preferences.category_ids.filter(value=>value!==id):[...preferences.category_ids,id];savePreferences({...preferences,category_ids:nextIds})}
 function openNotification(row){markRead(row.id);if(row.url)location.href=row.url}
 const filtered=useMemo(()=>items.filter(row=>{if(filters.type!=='all'&&row.type!==filters.type)return false;if(filters.city_id&&row.target_city_id!==filters.city_id)return false;if(filters.category_id&&row.target_category_id!==filters.category_id)return false;if(filters.unreadOnly&&row.read_at)return false;return true}),[items,filters])
 const unread=items.filter(row=>!row.read_at).length
 const cityName=id=>cities.find(city=>city.id===id)?.name||''
 if(loading)return <div className="account-card notification-center"><div className="notification-center-loading">Carregando notificações…</div></div>
 return <div className="notification-center">{message.text&&<div className={'account-alert '+(message.error?'error':'')}>{message.text}</div>}
  <section className="account-card notification-preferences-card"><div className="account-card-title"><div><h2>Preferências</h2><p>Escolha quais notificações da VitrineLocal você deseja receber.</p></div></div><div className="notification-preference-list">{[['promotions_enabled','Promoções','Receba ofertas e novidades das empresas.'],['business_enabled','Empresas','Atualizações e novidades de empresas acompanhadas.'],['system_enabled','Sistema','Informações importantes sobre sua conta e a VitrineLocal.']].map(([key,title,description])=><label className="notification-preference-row" key={key}><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={Boolean(preferences[key])} disabled={saving} onChange={e=>savePreferences({...preferences,[key]:e.target.checked})}/></label>)}</div><div className="notification-preference-segmentation"><div><strong>Personalização</strong><small>Escolha uma cidade e categorias para receber promoções mais relevantes. Deixe vazio para não restringir.</small></div><div className="notification-segmentation-grid"><label><span>Cidade</span><select value={preferences.city_id||''} disabled={saving} onChange={e=>savePreferences({...preferences,city_id:e.target.value})}><option value="">Todas as cidades</option>{cities.map(city=><option key={city.id} value={city.id}>{city.name} - {city.state}</option>)}</select></label><div><span className="notification-segmentation-label">Categorias</span><div className="notification-category-chips"><button type="button" className={!preferences.category_ids.length?'active':''} disabled={saving} onClick={()=>savePreferences({...preferences,category_ids:[]})}>Todas</button>{categories.map(category=><button type="button" key={category.id} className={preferences.category_ids.includes(category.id)?'active':''} disabled={saving} onClick={()=>toggleCategory(category.id)}>{category.name}</button>)}</div></div></div></div></section>
  <section className="account-card notification-history-card"><div className="account-card-title"><div><h2>Histórico</h2><p>{unread===0?'Tudo lido':unread===1?'1 não lida':unread+' não lidas'} · últimas 100 notificações</p></div>{unread>0&&<button type="button" className="account-secondary-btn small" onClick={markAllRead}>Marcar todas como lidas</button>}</div><div className="notification-history-filters"><div className="notification-filter-tabs">{TYPE_OPTIONS.map(([value,label])=><button key={value} type="button" className={filters.type===value?'active':''} onClick={()=>setFilters(current=>({...current,type:value}))}>{label}</button>)}</div><div className="notification-filter-fields"><label><span>Cidade</span><select value={filters.city_id} onChange={e=>setFilters(current=>({...current,city_id:e.target.value}))}><option value="">Todas</option>{cities.map(city=><option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label><span>Categoria</span><select value={filters.category_id} onChange={e=>setFilters(current=>({...current,category_id:e.target.value}))}><option value="">Todas</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="notification-unread-filter"><input type="checkbox" checked={filters.unreadOnly} onChange={e=>setFilters(current=>({...current,unreadOnly:e.target.checked}))}/><span>Somente não lidas</span></label></div></div>{filtered.length?<div className="notification-history-list">{filtered.map(row=><article className={'notification-history-item '+(!row.read_at?'unread':'')} key={row.id} onClick={()=>openNotification(row)} role={row.url?'button':undefined} tabIndex={row.url?0:undefined} onKeyDown={e=>{if(row.url&&(e.key==='Enter'||e.key===' '))openNotification(row)}}>{row.image_url?<img src={row.image_url} alt="" className="notification-history-image"/>:<div className="notification-history-icon">{row.type==='promotion'?'🏷️':row.type==='business'?'🏪':row.type==='system'?'⚙️':'🔔'}</div>}<div className="notification-history-copy"><div><strong>{row.title}</strong>{!row.read_at&&<i aria-label="Não lida"/>}</div><p>{row.body}</p><small>{formatDate(row.created_at)} · {typeLabel(row.type)}{row.status?' · '+statusLabel(row.status):''}{row.target_city_id&&cityName(row.target_city_id)?' · '+cityName(row.target_city_id):''}</small></div>{row.url&&<span className="notification-history-arrow">→</span>}</article>)}</div>:<div className="account-empty-inline notification-empty"><span>🔔</span><strong>Nenhuma notificação encontrada</strong><p>Ajuste os filtros ou aguarde uma nova atualização.</p></div>}</section>
 </div>
}