import React,{useEffect,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import{getPlanCycleFeatureUsage,ADMIN_UNLIMITED_LIMIT}from'./plan-cycle-usage.js'
import{adaptImageFile}from'./media-adapter.js'
import'./owner-item-form.css'
const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const MEDIA_BUCKET='business-media'
const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/gif'])
const EMPTY={type:'product',name:'',description:'',price:'',active:true}
const normalizeType=value=>['service','services','servico','serviço','servicos','serviços'].includes(String(value||'').trim().toLowerCase())?'service':'product'
const itemToForm=item=>item?{type:normalizeType(item.type),name:item.name||'',description:item.description||'',price:item.price==null?'':String(item.price),active:item.active!==false}:EMPTY
export default function OwnerItemForm({businessId,onSaved,onClose,activeCount,limit,item=null}){
 const editing=Boolean(item?.id)
 const[form,setForm]=useState(()=>itemToForm(item)),[file,setFile]=useState(null),[preview,setPreview]=useState(item?.image_url||''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[adapting,setAdapting]=useState(false)
 useEffect(()=>{setForm(itemToForm(item));setFile(null);setPreview(item?.image_url||'');setError('')},[item?.id])
 const usedCount=Number(activeCount)||0,unlimited=limit<0||limit===ADMIN_UNLIMITED_LIMIT,reached=!editing&&(limit===0||(limit>0&&!unlimited&&usedCount>=limit))
 async function chooseImage(next){if(!next)return;setError('');if(!IMAGE_TYPES.has(next.type))return setError('Use JPG, PNG, WEBP ou GIF.');if(next.size>8*1024*1024)return setError('A imagem deve ter no máximo 8 MB.');setAdapting(true);try{const adapted=await adaptImageFile(next,'square');if(preview?.startsWith('blob:'))URL.revokeObjectURL(preview);setFile(adapted);setPreview(URL.createObjectURL(adapted))}catch{setError('Não foi possível adaptar a imagem. Tente outra imagem.')}finally{setAdapting(false)}}
 async function submit(e){e.preventDefault();if(saving||adapting)return;if(reached)return setError('Este recurso não está disponível no seu plano atual ou atingiu o capacidade atual atingida.');const name=form.name.trim();if(!name)return setError('Informe o nome do produto ou serviço.');let price=null;if(form.price!==''){price=Number(String(form.price).replace(',','.'));if(!Number.isFinite(price)||price<0)return setError('Informe um preço válido.')}setSaving(true);setError('');let uploadedPath=null;try{let latestUsage=null;if(!editing){const{usage,error:usageError}=await getPlanCycleFeatureUsage(businessId,'items');if(usageError)throw usageError;latestUsage=usage;if(!latestUsage||latestUsage.limit===0)throw new Error('Este recurso não está disponível no seu plano atual.');if(latestUsage.limit>0&&!latestUsage.unlimited&&latestUsage.limit!==ADMIN_UNLIMITED_LIMIT&&latestUsage.used>=latestUsage.limit)throw new Error(`Capacidade de ${latestUsage.limit} produtos/serviços atingida.`)}let sortOrder=Number(item?.sort_order)||0;if(!editing){const totalItems=await db.from('business_items').select('id',{count:'exact',head:true}).eq('business_id',businessId);if(totalItems.error)throw totalItems.error;sortOrder=Number(totalItems.count||0)}let image_url=item?.image_url||null,image_path=item?.image_path||null;if(file){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[file.type]||'bin';uploadedPath=`${businessId}/items/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from(MEDIA_BUCKET).upload(uploadedPath,file,{cacheControl:'31536000',contentType:file.type,upsert:false});if(up.error)throw up.error;image_path=uploadedPath;image_url=db.storage.from(MEDIA_BUCKET).getPublicUrl(uploadedPath).data.publicUrl}const payload={business_id:businessId,type:form.type,name,description:form.description.trim()||null,price,active:Boolean(form.active),sort_order:sortOrder,image_url,image_path};const result=editing?await db.from('business_items').update(payload).eq('id',item.id).eq('business_id',businessId):await db.from('business_items').insert(payload);if(result.error)throw result.error;if(uploadedPath&&editing&&item?.image_path&&item.image_path!==uploadedPath)await db.storage.from(MEDIA_BUCKET).remove([item.image_path]).catch(()=>{});onSaved?.();onClose?.()}catch(err){if(uploadedPath)await db.storage.from(MEDIA_BUCKET).remove([uploadedPath]).catch(()=>{});setError(err.message||`Não foi possível ${editing?'salvar':'adicionar'} o item.`)}finally{setSaving(false)}}
 return <section className="vl-item-form-card"><div className="vl-item-form-head"><div><span className="account-eyebrow">{editing?'EDITAR ITEM':'NOVO ITEM'}</span><h2>{editing?'Editar produto ou serviço':'Adicionar produto ou serviço'}</h2><p>{editing?'Atualize os dados que aparecem no perfil público da sua empresa.':'Cadastre um item para aparecer no perfil público da sua empresa.'}</p></div><button type="button" className="vl-item-close" onClick={onClose} disabled={saving||adapting}>×</button></div>{reached&&<div className="vl-item-limit-alert">🔒 <div><strong>{limit===0?'Recurso indisponível':'Limite do ciclo atingido'}</strong><span>{limit===0?'Este recurso não está incluído no seu plano atual.':`Seu plano permite ${limit} itens armazenados. Excluir um item libera capacidade para adicionar outro.`}</span></div></div>}
 <form onSubmit={submit}><div className="vl-item-form-grid"><label><span>Tipo</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="product">Produto</option><option value="service">Serviço</option></select></label><label><span>Nome</span><input autoFocus maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Pizza Grande" required/></label><label className="full"><span>Descrição</span><textarea rows="4" maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descreva o produto ou serviço…"/></label><label><span>Preço</span><input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Ex.: 49,90"/></label><label><span>Status</span><select value={form.active?'active':'inactive'} onChange={e=>setForm({...form,active:e.target.value==='active'})}><option value="active">Ativo — aparece no perfil</option><option value="inactive">Inativo — ainda consome 1 unidade do ciclo</option></select></label></div><div className="vl-item-image-row"><div className="vl-item-preview">{preview?<img src={preview} alt="Prévia"/>:<span>◇</span>}</div><div className="vl-item-image-copy"><span className="account-eyebrow">IMAGEM DO ITEM</span><h3>Mostre o que você oferece</h3><p>Recomendado: <strong>1200 × 1200 px</strong> (quadrado). JPG, PNG ou WEBP · máximo 8 MB.</p><p className="vl-item-image-adaptation">Não precisa redimensionar. Se enviar uma imagem maior ou menor, o VitrineLocal adapta automaticamente <strong>sem cortar o conteúdo principal</strong>.</p><label className="vl-item-file"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>chooseImage(e.target.files?.[0])} disabled={adapting||saving}/><span>{adapting?'Adaptando imagem…':'Escolher imagem'}</span></label>{file&&<small>{file.name} · {(file.size/1024/1024).toFixed(1)} MB · 1200 × 1200 px</small>}</div></div>{error&&<div className="vl-item-error">{error}</div>}<div className="vl-item-footer"><span>{editing?'Alterações não consomem nova unidade do ciclo.':unlimited?'Uso ilimitado para testes administrativos.':'Cada novo produto ou serviço ocupa 1 unidade da capacidade. Excluir um item libera essa unidade.'}</span><div><button type="button" className="account-secondary-btn" onClick={onClose} disabled={saving||adapting}>Cancelar</button><button className="account-primary-btn" disabled={saving||adapting||reached}>{saving?'Salvando…':adapting?'Adaptando…':editing?'Salvar alterações':'Adicionar item'}</button></div></div></form></section>
}
