import React,{useState}from'react'
import{createClient}from'@supabase/supabase-js'
import'./owner-item-form.css'

const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const MEDIA_BUCKET='business-media'
const TYPES=[['product','Produto'],['service','Serviço']]
const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/gif'])
const EMPTY={type:'product',name:'',description:'',price:'',active:true}

export default function OwnerItemForm({businessId,onSaved,onClose,activeCount,limit}){
 const[form,setForm]=useState(EMPTY),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const reached=limit<=0||activeCount>=limit
 function chooseImage(next){if(!next)return;setError('');if(!IMAGE_TYPES.has(next.type))return setError('Use JPG, PNG, WEBP ou GIF.');if(next.size>8*1024*1024)return setError('A imagem deve ter no máximo 8 MB.');if(preview?.startsWith('blob:'))URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next))}
 async function submit(e){e.preventDefault();if(saving)return;if(limit<=0)return setError('Este recurso não está disponível no seu plano atual. Faça upgrade para adicionar produtos ou serviços.');if(activeCount>=limit)return setError(`Seu plano permite até ${limit} produtos/serviços ativos.`);const name=form.name.trim();if(!name)return setError('Informe o nome do produto ou serviço.');let price=null;if(form.price!==''){price=Number(String(form.price).replace(',','.'));if(!Number.isFinite(price)||price<0)return setError('Informe um preço válido.')}setSaving(true);setError('');let uploadedPath=null;try{const latest=await db.from('business_items').select('id,active').eq('business_id',businessId).eq('active',true);if(latest.error)throw latest.error;if(limit<=0||(latest.data||[]).length>=limit)throw new Error(limit<=0?'Este recurso não está disponível no seu plano atual.':`Limite de ${limit} produtos/serviços ativos atingido.`);let image_url=null,image_path=null;if(file){const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[file.type]||'bin';uploadedPath=`${businessId}/items/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from(MEDIA_BUCKET).upload(uploadedPath,file,{cacheControl:'31536000',contentType:file.type,upsert:false});if(up.error)throw up.error;image_path=uploadedPath;image_url=db.storage.from(MEDIA_BUCKET).getPublicUrl(uploadedPath).data.publicUrl}const{error:insertError}=await db.from('business_items').insert({business_id:businessId,type:form.type,name,description:form.description.trim()||null,price,active:Boolean(form.active),sort_order:(latest.data||[]).length,image_url,image_path});if(insertError)throw insertError;onSaved?.();onClose?.()}catch(err){if(uploadedPath)await db.storage.from(MEDIA_BUCKET).remove([uploadedPath]).catch(()=>{});setError(err.message||'Não foi possível adicionar o item.')}finally{setSaving(false)}}
 return <section className="vl-item-form-card"><div className="vl-item-form-head"><div><span className="account-eyebrow">NOVO ITEM</span><h2>Adicionar produto ou serviço</h2><p>Cadastre um item para aparecer no perfil público da sua empresa.</p></div><button type="button" className="vl-item-close" onClick={onClose} disabled={saving}>×</button></div>{reached&&<div className="vl-item-limit-alert">🔒 <div><strong>{limit<=0?'Recurso indisponível':'Limite atingido'}</strong><span>{limit<=0?'Este recurso não está incluído no seu plano atual.':`Seu plano já utiliza ${activeCount} de ${limit} itens ativos.`}</span></div></div>}
 <form onSubmit={submit}><div className="vl-item-form-grid"><label><span>Tipo</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Nome</span><input autoFocus maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Pizza Grande" required/></label><label className="full"><span>Descrição</span><textarea rows="4" maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descreva o produto ou serviço…"/></label><label><span>Preço</span><input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Ex.: 49,90"/></label><label><span>Status</span><select value={form.active?'active':'inactive'} onChange={e=>setForm({...form,active:e.target.value==='active'})}><option value="active">Ativo — aparece no perfil</option><option value="inactive">Inativo — não conta no limite</option></select></label></div><div className="vl-item-image-row"><div className="vl-item-preview">{preview?<img src={preview} alt="Prévia"/>:<span>◇</span>}</div><div className="vl-item-image-copy"><span className="account-eyebrow">IMAGEM DO ITEM</span><h3>Mostre o que você oferece</h3><p>JPG, PNG, WEBP ou GIF · máximo 8 MB. A imagem é opcional.</p><label className="vl-item-file"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>chooseImage(e.target.files?.[0])}/><span>Escolher imagem</span></label>{file&&<small>{file.name} · {(file.size/1024/1024).toFixed(1)} MB</small>}</div></div>{error&&<div className="vl-item-error">{error}</div>}<div className="vl-item-footer"><span>Itens ativos ocupam seu limite do plano.</span><div><button type="button" className="account-secondary-btn" onClick={onClose} disabled={saving}>Cancelar</button><button className="account-primary-btn" disabled={saving||reached}>{saving?'Salvando…':'Adicionar item'}</button></div></div></form></section>
}
