import React,{useEffect,useMemo,useState}from'react'
import{createClient}from'@supabase/supabase-js'
import'./plan-usage.css'

const URL=import.meta.env.VITE_SUPABASE_URL
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const db=URL&&KEY?createClient(URL,KEY):null
const PLAN_NAMES={free:'Grátis',pro:'Pro',premium:'Premium'}
const LABELS={photos:'Fotos e mídias',items:'Produtos e serviços',promotions:'Promoções'}

function getLimit(features,key){const v=features?.[`${key}_limit`]??features?.[key];const n=Number(v);return Number.isFinite(n)&&n>=0?n:0}
function usagePercent(used,limit){if(limit<=0)return used>0?100:0;return Math.min(100,(used/limit)*100)}
function usageState(used,limit){const percent=usagePercent(used,limit);if(limit===0)return'unavailable';if(used>=limit)return'critical';if(percent>=80)return'warning';return'normal'}
function Donut({percent,state='normal',label='usado'}){const safe=Math.max(0,Math.min(100,percent));return <div className={`vl-plan-donut ${state}`} style={{'--progress':`${safe*3.6}deg`}} aria-label={`${Math.round(safe)}% ${label}`}><div className="vl-plan-donut-inner"><strong>{Math.round(safe)}%</strong><span>{label}</span></div></div>}
function UsageCard({icon,label,used,limit}){const percent=usagePercent(used,limit),state=usageState(used,limit),remaining=limit>0?Math.max(0,limit-used):0;return <article className={`vl-plan-usage-card ${state}`}><div className="vl-plan-usage-top"><span className="vl-plan-usage-icon">{icon}</span><div><strong>{label}</strong><small>{limit>0?`${remaining} restante${remaining===1?'':'s'}`:'Não incluído no plano'}</small></div></div><div className="vl-plan-usage-main"><Donut percent={percent} state={state}/><div className="vl-plan-usage-values"><strong>{used}<small> / {limit}</small></strong><span>utilizado</span></div></div><div className="vl-plan-track"><i style={{width:`${percent}%`}}/></div><div className="vl-plan-usage-foot"><span>{limit>0?`${used} de ${limit}`:'Recurso indisponível'}</span>{state==='critical'&&<b>Limite atingido</b>}{state==='warning'&&<b>Quase no limite</b>}</div></article>}
function saoPauloToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function nextMonthLabel(){const today=saoPauloToday();const[d,m,y]=today.split('-').map(Number);const nextMonth=m===12?1:m+1;const nextYear=m===12?y+1:y;const base=new Date(Date.UTC(nextYear,nextMonth-1,1,12));return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(base)}

export default function PlanUsagePanel({businessId}){
 const[data,setData]=useState(null),[error,setError]=useState('')
 useEffect(()=>{let live=true;async function load(){if(!db||!businessId)return;setError('');const{data:planId,error:planError}=await db.rpc('get_effective_plan_id',{p_business_id:businessId});if(planError||!planId){if(live)setError(planError?.message||'Não foi possível carregar o plano.');return}const{data:plan,error:planLoadError}=await db.from('plans').select('code,name,description,features,active').eq('id',planId).maybeSingle();if(planLoadError||!plan){if(live)setError(planLoadError?.message||'Plano não encontrado.');return}const[photos,items,promotions,ai]=await Promise.all([db.from('business_photos').select('id',{count:'exact',head:true}).eq('business_id',businessId),db.from('business_items').select('id',{count:'exact',head:true}).eq('business_id',businessId).eq('active',true),db.from('promotions').select('id,status,ends_at',{count:'exact',head:false}).eq('business_id',businessId).in('status',['pending_review','published','draft']),db.rpc('get_monthly_plan_usage',{p_business_id:businessId,p_feature:'ai_posts'})]);if(!live)return;if(photos.error||items.error||promotions.error)console.warn('Plan usage count error',{photos:photos.error?.message,items:items.error?.message,promotions:promotions.error?.message});const now=new Date();const promotionCount=(promotions.data||[]).filter(p=>!p.ends_at||new Date(p.ends_at)>now).length;setData({plan,counts:{photos:photos.count||0,items:items.count||0,promotions:promotionCount},monthlyAi:Number(ai.data)||0})}load();return()=>{live=false}},[businessId])
 const limits=useMemo(()=>data?{photos:getLimit(data.plan.features,'photos'),items:getLimit(data.plan.features,'items'),promotions:getLimit(data.plan.features,'promotions'),ai_posts:getLimit(data.plan.features,'ai_posts')}:null,[data])
 const summary=useMemo(()=>{if(!data||!limits)return null;const entries=Object.keys(LABELS).map(key=>({used:data.counts[key],limit:limits[key],percent:usagePercent(data.counts[key],limits[key])}));const usable=entries.filter(x=>x.limit>0);const avg=usable.length?usable.reduce((sum,x)=>sum+x.percent,0)/usable.length:0;const reached=usable.filter(x=>x.used>=x.limit).length;return{avg,reached,total:usable.length}},[data,limits])
 if(error)return <section className="vl-plan-panel vl-plan-panel-error"><div><strong>Meu plano</strong><p>{error}</p></div></section>
 if(!data||!limits||!summary)return <section className="vl-plan-panel"><div className="vl-plan-loading">Carregando seu plano…</div></section>
 const{plan,counts,monthlyAi}=data;const planCode=plan.code||'free';const isPremium=planCode==='premium';const aiLimit=limits.ai_posts;const aiPercent=usagePercent(monthlyAi,aiLimit);const aiState=usageState(monthlyAi,aiLimit);const analytics=Boolean(plan.features?.analytics);const featured=Boolean(plan.features?.featured);const verified=Boolean(plan.features?.verified);const upgradeLabel=planCode==='pro'?'Fazer upgrade para Premium':'Fazer upgrade';const upgradeCopy=planCode==='pro'?'Desbloqueie mais destaque, mais espaço e recursos avançados.':'Aumente os limites e desbloqueie recursos para sua empresa.'
 return <section className={`vl-plan-panel plan-${planCode}`}>
  <div className="vl-plan-hero"><div className="vl-plan-hero-copy"><span className="vl-plan-eyebrow">SEU PLANO ATUAL</span><div className="vl-plan-title-row"><h2>{PLAN_NAMES[planCode]||plan.name||planCode}</h2><span className="vl-plan-badge">{isPremium?'👑 Premium':planCode==='pro'?'⚡ Pro':'✓ Ativo'}</span></div><p>{plan.description||'Acompanhe seus recursos, limites e consumo da empresa.'}</p></div><div className="vl-plan-overview"><Donut percent={summary.avg} state={summary.avg>=90?'critical':summary.avg>=75?'warning':'normal'}/><div><strong>{Math.round(summary.avg)}%</strong><span>uso médio dos limites</span>{summary.total>0&&<small>{summary.reached} de {summary.total} limites atingidos</small>}</div></div></div>
  <div className="vl-plan-section-head"><div><span>CONSUMO</span><h3>Como você está usando seu plano</h3></div><span className="vl-plan-sync">Dados atualizados agora</span></div>
  <div className="vl-plan-usage-grid"><UsageCard icon="▣" label={LABELS.photos} used={counts.photos} limit={limits.photos}/><UsageCard icon="◇" label={LABELS.items} used={counts.items} limit={limits.items}/><UsageCard icon="✦" label={LABELS.promotions} used={counts.promotions} limit={limits.promotions}/></div>
  {aiLimit>0&&<div className="vl-plan-monthly"><div><span className="vl-plan-eyebrow">QUOTA MENSAL</span><h3>Recursos de IA</h3><p>{monthlyAi} de {aiLimit} usos neste mês. O contador reinicia em {nextMonthLabel()}.</p></div><div className="vl-plan-monthly-meter"><Donut percent={aiPercent} state={aiState} label="este mês"/><div><strong>{monthlyAi}/{aiLimit}</strong><span>{Math.round(aiPercent)}% utilizado</span><div className="vl-plan-track"><i style={{width:`${aiPercent}%`}}/></div></div></div></div>}
  <div className="vl-plan-features"><div><span className="vl-plan-feature-icon">✓</span><div><strong>Recursos incluídos</strong><p>{analytics?'Analytics habilitado':'Analytics no Pro ou superior'} · {featured?'Destaque habilitado':'Destaque no Pro ou superior'} · {verified?'Verificação habilitada':'Verificação no Pro ou superior'}</p></div></div><span className="vl-plan-feature-status">{isPremium?'Plano completo':planCode==='pro'?'Plano profissional':'Plano gratuito'}</span></div>
  {!isPremium&&<div className="vl-plan-upgrade"><div className="vl-plan-upgrade-icon">↗</div><div className="vl-plan-upgrade-copy"><span>APROVEITE MAIS A VITRINE</span><strong>{upgradeCopy}</strong></div><a href={`/planos?business_id=${encodeURIComponent(businessId)}`} className="vl-plan-upgrade-btn">{upgradeLabel}<span>→</span></a></div>}
 </section>
}
