import React,{useEffect,useMemo,useState}from'react'
import{supabase as db}from'./supabase-client.js'
import'./site-header.css'
const FALLBACK_CITY={id:'fallback',name:'Laguna',state:'SC',slug:'laguna',active:true}
const RESERVED=new Set(['login','planos','conta','admin','privacidade','termos','atualizar-senha','usuario'])
const CITY_CHILDREN=new Set(['empresas','promocoes','eventos'])
const CATEGORY_MENU=[['Restaurantes','🍽️'],['Lojas','🛍️'],['Serviços','🧰'],['Saúde','❤️'],['Beleza','✨'],['Turismo','📍'],['Automóveis','🚗'],['Imóveis','🏠'],['Pets','🐾'],['Outros','✦']]
const slugify=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
function pathParts(){return location.pathname.split('/').filter(Boolean).map(x=>{try{return decodeURIComponent(x)}catch{return x}})}
function getPathCitySlug(){const parts=pathParts();const first=parts[0]?.toLowerCase();return first&&!RESERVED.has(first)?first:null}
function getStoredCity(){try{return localStorage.getItem('vl_city_slug')||null}catch{return null}}
function setStoredCity(slug){try{localStorage.setItem('vl_city_slug',slug)}catch{}}
export default function SiteHeader(){
 const[path,setPath]=useState(location.pathname),[cities,setCities]=useState([FALLBACK_CITY]),[citySlug,setCitySlug]=useState(getPathCitySlug()||getStoredCity()||'laguna'),[session,setSession]=useState(null),[role,setRole]=useState('user'),[mobileOpen,setMobileOpen]=useState(false)
 const loadRole=async currentSession=>{if(!db||!currentSession?.user?.id){setRole('user');return}const{data,error}=await db.from('profiles').select('role').eq('id',currentSession.user.id).maybeSingle();setRole(error?'user':data?.role||'user')}
 useEffect(()=>{const sync=()=>{setPath(location.pathname);setMobileOpen(false);const fromPath=getPathCitySlug();if(fromPath){setCitySlug(fromPath);setStoredCity(fromPath)}};window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[])
 useEffect(()=>{let live=true;if(!db)return()=>{};(async()=>{try{const[{data:{session:s}},{data:citiesData}]=await Promise.all([db.auth.getSession(),db.from('cities').select('id,name,state,slug,active').eq('active',true).order('name')]);if(!live)return;setSession(s||null);if(citiesData?.length)setCities(citiesData);const fromPath=getPathCitySlug(),next=fromPath||getStoredCity()||citiesData?.[0]?.slug||'laguna';setCitySlug(next);setStoredCity(next)}catch{if(live)setSession(null)}})();const sub=db.auth.onAuthStateChange((_event,s)=>setSession(s||null));return()=>{live=false;sub?.data?.subscription?.unsubscribe()}},[])
 useEffect(()=>{let live=true;setRole('user');if(!session?.user?.id)return()=>{};(async()=>{try{await loadRole(session);if(!live)return}catch{if(live)setRole('user')}})();return()=>{live=false}},[session?.user?.id])
 const city=useMemo(()=>cities.find(c=>c.slug===citySlug)||cities[0]||FALLBACK_CITY,[cities,citySlug]),cityBase=`/${city?.slug||'laguna'}`
 const accountHref='/conta'
 const openAccount=e=>{e.preventDefault();location.assign('/conta')}
 const isActive=key=>{if(key==='home')return path===cityBase||path==='/';if(key==='businesses')return path.startsWith(`${cityBase}/empresas`);if(key==='promotions')return path.startsWith(`${cityBase}/promocoes`);if(key==='events')return path.startsWith(`${cityBase}/eventos`);if(key==='plans')return path==='/planos';if(key==='admin')return path.startsWith('/admin');if(key==='account')return path.startsWith('/conta')||path.startsWith('/usuario/perfil')||path==='/login';return false}
 const goCity=nextSlug=>{setCitySlug(nextSlug);setStoredCity(nextSlug);const parts=pathParts();const child=parts[0]?.toLowerCase()===nextSlug.toLowerCase()?parts[1]?.toLowerCase():null;if(child&&CITY_CHILDREN.has(child))location.href=`/${nextSlug}/${child}`;else if(path==='/planos'||path.startsWith('/admin')||path.startsWith('/conta')||path.startsWith('/usuario/perfil')||path==='/login'||path==='/privacidade'||path==='/termos'||path==='/atualizar-senha')setMobileOpen(false);else location.href=`/${nextSlug}`}
 const links=[['businesses','Explorar',`${cityBase}/empresas`],['promotions','Promoções',`${cityBase}/promocoes`],['events','Eventos',`${cityBase}/eventos`],['plans','Planos','/planos']]
 return <><header className="vl-site-header"><div className="vl-site-header-inner"><a className="vl-site-brand" href={cityBase} aria-label="VitrineLocal início"><img className="vl-site-brand-logo" src="/vitrine-local-header-logo.svg" alt="VitrineLocal — A cidade em um só lugar"/></a><label className="vl-site-city" aria-label="Selecionar cidade"><span className="vl-site-city-pin">⌖</span><select value={city?.slug||'laguna'} onChange={e=>goCity(e.target.value)}>{cities.map(c=><option key={c.id} value={c.slug}>{c.name} - {c.state||'SC'}</option>)}</select><span className="vl-site-city-chevron">⌄</span></label><nav className="vl-site-nav" aria-label="Navegação principal">{links.map(([key,label,href])=><a key={key} className={`vl-site-nav-link ${isActive(key)?'active':''}`} href={href}>{label}</a>)}<details className="vl-site-categories"><summary>Categorias⌄</summary><div className="vl-site-category-menu">{CATEGORY_MENU.map(([label,icon])=><a href={`${cityBase}/empresas?categoria=${encodeURIComponent(slugify(label))}`} key={label}><span>{icon}</span><span>{label}</span></a>)}</div></details>{role==='admin'&&<a className={`vl-site-nav-link vl-site-admin-link ${isActive('admin')?'active':''}`} href="/admin">Admin</a>}</nav><div className="vl-site-actions"><a className={`vl-site-account ${isActive('account')?'active':''}`} href={accountHref} onClick={openAccount}><span className="vl-site-avatar">V</span><span>Minha conta</span></a><a className="vl-site-menu-toggle" href="#menu" onClick={e=>{e.preventDefault();setMobileOpen(v=>!v)}} aria-expanded={mobileOpen} aria-label={mobileOpen?'Fechar menu':'Abrir menu'}><span></span><span></span><span></span></a></div></div>{mobileOpen&&<div className="vl-site-mobile-panel"><div className="vl-site-mobile-city"><span>Localização</span><label><span>⌖</span><select value={city?.slug||'laguna'} onChange={e=>goCity(e.target.value)}>{cities.map(c=><option key={c.id} value={c.slug}>{c.name} - {c.state||'SC'}</option>)}</select></label></div><nav aria-label="Navegação móvel"><a className={isActive('home')?'active':''} href={cityBase}>Início</a>{links.map(([key,label,href])=><a key={key} className={isActive(key)?'active':''} href={href}>{label}</a>)}<div className="vl-site-mobile-categories"><strong>Categorias</strong>{CATEGORY_MENU.map(([label,icon])=><a href={`${cityBase}/empresas?categoria=${encodeURIComponent(slugify(label))}`} key={label}><span>{icon}</span>{label}</a>)}</div>{role==='admin'&&<a className={isActive('admin')?'active':''} href="/admin">Administração</a>}</nav><div className="vl-site-mobile-actions"><a className="vl-site-mobile-account" href={accountHref} onClick={openAccount}><span className="vl-site-avatar">V</span>Minha conta</a></div></div>}</header></>
}
