import React,{useEffect,useState}from'react'
import{supabase as db}from'./supabase-client.js'
import'./user-profile.css'

const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp'])

export default function UserProfilePage(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[form,setForm]=useState({full_name:'',username:'',bio:''}),[avatarUrl,setAvatarUrl]=useState(''),[avatarPath,setAvatarPath]=useState(''),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({text:'',error:false})
 useEffect(()=>{let live=true;(async()=>{if(!db){if(live)setLoading(false);return}const{data:{session:s}}=await db.auth.getSession();if(!live)return;if(!s){setLoading(false);return}setSession(s);const{data:p,error}=await db.from('profiles').select('id,full_name,username,bio,avatar_url,avatar_path,role,account_status').eq('id',s.user.id).maybeSingle();if(!live)return;if(error){setMessage({text:error.message,error:true});setLoading(false);return}const next=p||{id:s.user.id,full_name:s.user.user_metadata?.full_name||'',username:'',bio:'',avatar_url:'',avatar_path:''};setProfile(next);setForm({full_name:next.full_name||'',username:next.username||'',bio:next.bio||''});setAvatarUrl(next.avatar_url||'');setAvatarPath(next.avatar_path||'');setLoading(false)})();return()=>{live=false;setPreview(v=>{if(v)URL.revokeObjectURL(v);return''})}},[])
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
 const chooseFile=e=>{const f=e.target.files?.[0];if(!f)return;if(!IMAGE_TYPES.has(f.type))return setMessage({text:'Use JPG, PNG ou WebP.',error:true});if(f.size>5*1024*1024)return setMessage({text:'A foto deve ter no máximo 5 MB.',error:true});if(preview)URL.revokeObjectURL(preview);setFile(f);setPreview(URL.createObjectURL(f));setMessage({text:'',error:false})}
 const uploadAvatar=async userId=>{if(!file)return{url:avatarUrl,path:avatarPath};const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('avatars').upload(path,file,{cacheControl:'31536000',contentType:file.type,upsert:false});if(up.error)throw up.error;const url=db.storage.from('avatars').getPublicUrl(path).data.publicUrl;if(avatarPath&&avatarPath!==path)await db.storage.from('avatars').remove([avatarPath]).catch(()=>{});return{url,path}}
 const save=async e=>{e.preventDefault();if(!db||!session)return;setSaving(true);setMessage({text:'',error:false});try{const username=form.username.trim().toLowerCase();if(username&&!/^[a-z0-9_\.]{3,24}$/.test(username))throw new Error('Usuário deve ter 3–24 caracteres e usar apenas letras, números, ponto ou _.');const{url,path}=await uploadAvatar(session.user.id);const{data:updated,error}=await db.from('profiles').update({full_name:form.full_name.trim()||null,username:username||null,bio:form.bio.trim()||null,avatar_url:url||null,avatar_path:path||null}).eq('id',session.user.id).select('id,full_name,username,bio,avatar_url,avatar_path,role,account_status').single();if(error){if(file&&path&&!avatarPath)await db.storage.from('avatars').remove([path]).catch(()=>{});if(error.code==='23505')throw new Error('Esse nome de usuário já está em uso.');throw error}setProfile(updated);setForm({full_name:updated.full_name||'',username:updated.username||'',bio:updated.bio||''});setAvatarUrl(updated.avatar_url||'');setAvatarPath(updated.avatar_path||'');setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview('');setMessage({text:'Perfil atualizado com sucesso.',error:false})}catch(err){setMessage({text:err.message||'Não foi possível salvar seu perfil.',error:true})}finally{setSaving(false)}}
 if(loading)return <main className="user-profile-page"><div className="user-profile-loading">Carregando perfil…</div></main>
 if(!session)return <main className="user-profile-page"><section className="user-profile-card"><span className="user-profile-kicker">ÁREA DO CLIENTE</span><h1>Entre para personalizar seu perfil</h1><p>Você precisa estar autenticado para editar seu perfil.</p><a className="user-profile-primary" href="/usuario/login?next=%2Fusuario%2Fperfil">Entrar</a></section></main>
 const displayName=form.full_name||'Seu nome';const avatar=preview||avatarUrl
 return <main className="user-profile-page"><div className="user-profile-shell"><div className="user-profile-top"><div><span className="user-profile-kicker">MEU PERFIL</span><h1>Personalize sua presença no VitrineLocal</h1><p>Seu nome, foto e bio aparecem junto das suas avaliações.</p></div><a className="user-profile-back" href="/laguna">Voltar ao VitrineLocal</a></div><div className="user-profile-grid"><section className="user-profile-card"><form onSubmit={save}><div className="user-avatar-row"><div className="user-profile-avatar">{avatar?<img src={avatar} alt="Pré-visualização do perfil"/>:<span>{displayName.trim().charAt(0).toUpperCase()||'U'}</span>}</div><div><label className="user-profile-upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile}/><span>Escolher foto</span></label><small>JPG, PNG ou WebP · até 5 MB</small></div></div><label><span>Nome</span><input value={form.full_name} onChange={e=>setForm(v=>({...v,full_name:e.target.value}))} maxLength={80} placeholder="Seu nome"/></label><label><span>Nome de usuário</span><input value={form.username} onChange={e=>setForm(v=>({...v,username:e.target.value.toLowerCase()}))} maxLength={24} placeholder="seunome"/><small>Use 3–24 caracteres: letras, números, ponto ou _.</small></label><label><span>Bio</span><textarea value={form.bio} onChange={e=>setForm(v=>({...v,bio:e.target.value}))} maxLength={180} rows={4} placeholder="Conte um pouco sobre você…"/><small>{form.bio.length}/180</small></label>{message.text&&<div className={`user-profile-message ${message.error?'error':'success'}`}>{message.text}</div>}<div className="user-profile-actions"><button type="submit" disabled={saving}>{saving?'Salvando…':'Salvar perfil'}</button></div></form></section><aside className="user-profile-card preview-card"><span className="user-profile-kicker">PRÉVIA NAS AVALIAÇÕES</span><div className="review-profile-preview"><div className="review-profile-preview-avatar">{avatar?<img src={avatar} alt=""/>:<span>{displayName.trim().charAt(0).toUpperCase()||'U'}</span>}</div><div><strong>{displayName}</strong>{form.username&&<small>@{form.username}</small>}<p>{form.bio||'Sua bio aparecerá aqui.'}</p></div></div><div className="preview-note">Quando você avaliar uma empresa, sua foto de perfil e seu nome de usuário poderão aparecer junto da avaliação.</div></aside></div></div></main>
}
