import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = path => fs.readFileSync(path,'utf8')

test('pré-lançamento possui SEO público e rotas privadas protegidas contra indexação',()=>{
 const html=read('index.html')
 const seo=read('src/seo-runtime.js')
 const robots=read('public/robots.txt')
 const htaccess=read('public/.htaccess')
 assert.match(html,/meta name="description"/)
 assert.match(html,/property="og:title"/)
 assert.match(html,/property="og:image"/)
 assert.match(html,/site\.webmanifest/)
 assert.match(html,/favicon\.svg/)
 assert.match(html,/src="\/src\/seo-runtime\.js"/)
 assert.match(seo,/document\.title=title/)
 assert.match(seo,/firstMeta\('name','robots'/)
 assert.match(seo,/linkRel\('canonical'/)
 assert.match(seo,/application\/ld\+json/)
 assert.match(seo,/noindex,nofollow,noarchive/)
 assert.match(robots,/Allow: \/sitemap\.xml/)
 assert.match(robots,/Disallow: \/admin/)
 assert.match(robots,/Disallow: \/api\//)
 assert.match(htaccess,/RewriteEngine On/)
 assert.doesNotMatch(htaccess,/vercel/i)
})

test('sitemap é gerado no build e cobre cidades, catálogos e perfis públicos sem expor rotas privadas',()=>{
 const pkg=JSON.parse(read('package.json'))
 const generator=read('scripts/generate-sitemap.mjs')
 assert.match(pkg.scripts.build,/generate-sitemap\.mjs/)
 assert.match(generator,/public\/sitemap\.xml/)
 assert.match(generator,/public_business_directory/)
 assert.match(generator,/active=eq\.true/)
 assert.match(generator,/\/empresas/)
 assert.match(generator,/\/promocoes/)
 assert.match(generator,/\/eventos/)
 assert.doesNotMatch(generator,/\/admin/)
 assert.doesNotMatch(generator,/\/conta/)
 assert.doesNotMatch(generator,/vercel/i)
})

test('analytics mede passos de conversão do funil comercial',()=>{
 const tracker=read('src/analytics-tracker.jsx')
 assert.match(tracker,/record\('plan_view'/)
 assert.match(tracker,/record\('business_signup_start'/)
 assert.match(tracker,/\/planos/)
 assert.match(tracker,/business_signup_start/)
 assert.match(tracker,/new=business/)
})

test('identidade de lançamento permanece com azul VitrineLocal',()=>{
 const css=read('src/vitrine-identity.css')
 const manifest=read('public/site.webmanifest')
 const favicon=read('public/favicon.svg')
 const robots=read('public/robots.txt')
 assert.match(css,/--vl-blue:#1677ff/)
 assert.match(manifest,/"theme_color": "#1677ff"/)
 assert.match(favicon,/#1677ff/)
 assert.match(robots,/Allow: \/sitemap\.xml/)
 assert.match(robots,/Disallow: \/admin/)
 assert.match(robots,/Disallow: \/api\//)
})
